import type {
  CryptoSystem,
  MaturityScenario,
  MigrationPattern,
  NavigationSection,
  QuestionGroup,
  SectionId,
} from "./model";
import { syntheticEvidenceFor } from "./syntheticEvidence.v1";

export const NAVIGATION_SECTIONS: readonly NavigationSection[] = [
  { id: "overview", shortLabel: "Overview", title: "Executive overview", eyebrow: "01 / Frame", interviewStep: 1 },
  { id: "architecture", shortLabel: "Architecture", title: "Enterprise reference architecture", eyebrow: "02 / Map", interviewStep: 2 },
  { id: "tvm-mapping", shortLabel: "TVM analogy", title: "TVM to PQC mapping", eyebrow: "03 / Transfer", interviewStep: 3 },
  { id: "inventory", shortLabel: "Inventory", title: "Seed inventory + evidence fusion", eyebrow: "04 / Discover", interviewStep: 4 },
  { id: "prioritization", shortLabel: "Prioritize", title: "Risk and migration prioritization", eyebrow: "05 / Explain", interviewStep: 5 },
  { id: "workflow", shortLabel: "Workflow", title: "Migration workflow", eyebrow: "06 / Orchestrate", interviewStep: 6 },
  { id: "scenarios", shortLabel: "Scenarios", title: "Environment maturity scenarios", eyebrow: "07 / Adapt", interviewStep: 7 },
  { id: "decisions", shortLabel: "Decide", title: "Capability gaps and build-vs-buy", eyebrow: "08 / Decide", interviewStep: 8 },
  { id: "patterns", shortLabel: "Patterns", title: "Migration patterns", eyebrow: "09 / Execute" },
  { id: "posture", shortLabel: "This demo", title: "The demo’s own PQC posture", eyebrow: "10 / Verify", interviewStep: 9 },
  { id: "dashboard", shortLabel: "Measure", title: "Migration dashboard", eyebrow: "11 / Measure" },
  { id: "questions", shortLabel: "Questions", title: "Convert architecture into a program", eyebrow: "12 / Discover", interviewStep: 10 },
] as const;

export const INTERVIEW_SECTION_IDS: readonly SectionId[] = NAVIGATION_SECTIONS.filter(
  (section) => section.interviewStep !== undefined,
).sort((a, b) => (a.interviewStep ?? 0) - (b.interviewStep ?? 0)).map((section) => section.id);

export function sectionById(id: SectionId): NavigationSection {
  const section = NAVIGATION_SECTIONS.find((candidate) => candidate.id === id);
  if (!section) throw new Error(`Unknown section: ${id}`);
  return section;
}

export const EXECUTIVE_LOOP = [
  "Discover",
  "Inventory",
  "Contextualize",
  "Prioritize",
  "Remediate",
  "Validate",
  "Measure",
] as const;

export const NIST_ALIGNED_LIFECYCLE = [
  {
    stage: "Awareness & Preparation",
    outcome: "Charter the program, define scope, assign ownership, and establish crypto-agility principles.",
  },
  {
    stage: "Discovery & Inventory",
    outcome: "Locate public-key cryptography and build a normalized, renewable inventory.",
  },
  {
    stage: "Risk Assessment & Planning",
    outcome: "Add business context, sequence migrations, and set vendor and dependency plans.",
  },
  {
    stage: "Migration Execution",
    outcome: "Pilot interoperable patterns, coordinate change, and retain controlled fallback paths.",
  },
  {
    stage: "Migration Testing",
    outcome: "Exercise compatibility, performance, failure, rollback, and mixed-estate behavior.",
  },
  {
    stage: "Validation & Monitoring",
    outcome: "Rediscover, verify outcomes, monitor drift, manage exceptions, and measure coverage.",
  },
] as const;

export const CSF_2_CONCURRENT_OVERLAY = [
  {
    function: "GOVERN",
    stageEmphasis: "Stages 1–6",
    contribution: "Risk strategy, policy, roles, supply-chain decisions, exceptions, and evidence gates remain active throughout.",
  },
  {
    function: "IDENTIFY",
    stageEmphasis: "Emphasis in stages 1–3 and 6",
    contribution: "Discover cryptography, assets, dependencies, owners, data lifetime, and material vendor constraints.",
  },
  {
    function: "PROTECT",
    stageEmphasis: "Emphasis in stages 3–6",
    contribution: "Design, migrate, and sustain controlled cryptographic protections with bounded fallback paths.",
  },
  {
    function: "DETECT",
    stageEmphasis: "Emphasis in stages 2, 5, and 6",
    contribution: "Rediscover drift, incompatibility, configuration regressions, and expired migration exceptions.",
  },
  {
    function: "RESPOND",
    stageEmphasis: "Emphasis in stages 4–6",
    contribution: "Triage failures, coordinate accountable change, contain exposure, and manage exceptions.",
  },
  {
    function: "RECOVER",
    stageEmphasis: "Emphasis in stages 4–6",
    contribution: "Exercise rollback, restore trusted service, and feed lessons back into governance and discovery.",
  },
] as const;

export const CRYPTO_SYSTEMS: readonly CryptoSystem[] = [
  {
    id: "syn-api-edge-01",
    synthetic: true,
    asset: "Customer API Gateway",
    application: "Northwind Account API",
    estateClass: "third-party-saas",
    issueTypes: ["tls-protocol", "certificate-trust", "algorithm-key-strength", "vendor-control"],
    businessService: "Digital servicing",
    environment: "Production",
    owner: "Platform Engineering",
    cryptographicUse: "External TLS termination and service authentication",
    protocol: "TLS 1.3 / mTLS",
    algorithm: "ECDHE + ECDSA",
    credential: "Edge and service certificates",
    issuer: "Enterprise issuing CA",
    runtime: "Managed gateway",
    exposure: "Internet",
    sensitivity: "High",
    retention: "7 years",
    dependencyCount: 18,
    vendorManaged: false,
    cryptoAgility: "Moderate",
    readiness: "Assessing",
    priority: "Urgent",
    status: "Assessment",
    migrationPattern: "Hybrid TLS pilot",
    evidence: syntheticEvidenceFor("syn-api-edge-01"),
  },
  {
    id: "syn-pay-java-02",
    synthetic: true,
    asset: "Internal Java Payment Service",
    application: "Ledger Relay",
    estateClass: "ots-cots",
    issueTypes: ["tls-protocol", "implementation-configuration", "source-code-crypto-use", "cryptographic-dependency", "algorithm-key-strength"],
    businessService: "Settlement processing",
    environment: "Production",
    owner: "Application Engineering",
    cryptographicUse: "Service TLS and payload signatures",
    protocol: "TLS 1.2 / JWS",
    algorithm: "RSA-2048 + SHA-256",
    credential: "Service certificate and signing key",
    issuer: "Enterprise issuing CA",
    runtime: "Java 17",
    exposure: "Internal",
    sensitivity: "Critical",
    retention: "10 years",
    dependencyCount: 24,
    vendorManaged: false,
    cryptoAgility: "Low",
    readiness: "Blocked",
    priority: "Urgent",
    status: "Planned",
    migrationPattern: "Runtime uplift + dual-sign validation",
    evidence: syntheticEvidenceFor("syn-pay-java-02"),
  },
  {
    id: "syn-vpn-03",
    synthetic: true,
    asset: "Corporate VPN",
    application: "Remote Workforce Access",
    estateClass: "ots-cots",
    issueTypes: ["tls-protocol", "certificate-trust", "vendor-control"],
    businessService: "Workforce connectivity",
    environment: "Production",
    owner: "Network Engineering",
    cryptographicUse: "Remote-access key exchange and authentication",
    protocol: "IKEv2 / IPsec",
    algorithm: "ECDH P-256 + RSA-3072",
    credential: "Gateway and device certificates",
    issuer: "Device issuing CA",
    runtime: "Network appliance",
    exposure: "Internet",
    sensitivity: "High",
    retention: "Session only",
    dependencyCount: 9,
    vendorManaged: true,
    cryptoAgility: "Low",
    readiness: "Unknown",
    priority: "High",
    status: "Discovery",
    migrationPattern: "Vendor readiness + staged client pilot",
    evidence: syntheticEvidenceFor("syn-vpn-03"),
  },
  {
    id: "syn-ca-04",
    synthetic: true,
    asset: "Certificate Authority",
    application: "Enterprise Trust Fabric",
    estateClass: "ots-cots",
    issueTypes: ["certificate-trust", "implementation-configuration", "algorithm-key-strength", "vendor-control"],
    businessService: "Digital trust",
    environment: "Production",
    owner: "PKI Engineering",
    cryptographicUse: "Certificate issuance and hierarchy signatures",
    protocol: "X.509 / CMP",
    algorithm: "RSA-4096 + SHA-384",
    credential: "Root and subordinate CA keys",
    issuer: "Offline root CA",
    runtime: "CA appliance + HSM",
    exposure: "Restricted",
    sensitivity: "Critical",
    retention: "20 years",
    dependencyCount: 42,
    vendorManaged: true,
    cryptoAgility: "Low",
    readiness: "Assessing",
    priority: "Urgent",
    status: "Assessment",
    migrationPattern: "Parallel hierarchy and trust-store transition",
    evidence: syntheticEvidenceFor("syn-ca-04"),
  },
  {
    id: "syn-k8s-05",
    synthetic: true,
    asset: "Kubernetes Ingress",
    application: "Container Service Edge",
    estateClass: "ots-cots",
    issueTypes: ["tls-protocol", "certificate-trust", "source-code-crypto-use", "cryptographic-dependency"],
    businessService: "Application hosting",
    environment: "Production",
    owner: "Cloud Platform",
    cryptographicUse: "Ingress TLS and workload identity",
    protocol: "TLS 1.3 / SPIFFE",
    algorithm: "ECDHE + ECDSA",
    credential: "Short-lived workload certificates",
    issuer: "Workload CA",
    runtime: "Kubernetes 1.34",
    exposure: "Partner",
    sensitivity: "High",
    retention: "90 days",
    dependencyCount: 31,
    vendorManaged: false,
    cryptoAgility: "High",
    readiness: "Ready",
    priority: "High",
    status: "Pilot",
    migrationPattern: "Hybrid-capable ingress canary",
    evidence: syntheticEvidenceFor("syn-k8s-05"),
  },
  {
    id: "syn-sign-06",
    synthetic: true,
    asset: "Code Signing Pipeline",
    application: "Artifact Assurance",
    estateClass: "source-code",
    issueTypes: ["certificate-trust", "source-code-crypto-use", "cryptographic-dependency"],
    businessService: "Software delivery",
    environment: "Production",
    owner: "DevSecOps",
    cryptographicUse: "Release artifact and provenance signatures",
    protocol: "CMS / in-toto",
    algorithm: "ECDSA P-384",
    credential: "HSM-backed signing key",
    issuer: "Code-signing CA",
    runtime: "CI runners + HSM",
    exposure: "Internal",
    sensitivity: "Critical",
    retention: "15 years",
    dependencyCount: 36,
    vendorManaged: false,
    cryptoAgility: "Moderate",
    readiness: "Assessing",
    priority: "Urgent",
    status: "Planned",
    migrationPattern: "Dual-sign and verifier compatibility pilot",
    evidence: syntheticEvidenceFor("syn-sign-06"),
  },
  {
    id: "syn-sftp-07",
    synthetic: true,
    asset: "Vendor File Transfer Gateway",
    application: "Partner Exchange",
    estateClass: "ots-cots",
    issueTypes: ["tls-protocol", "cryptographic-dependency", "vendor-control"],
    businessService: "Partner data exchange",
    environment: "Production",
    owner: "Integration Engineering",
    cryptographicUse: "SSH key exchange and file integrity",
    protocol: "SFTP / SSH",
    algorithm: "Curve25519 + Ed25519",
    credential: "Host and partner keys",
    issuer: "Locally managed",
    runtime: "Vendor appliance",
    exposure: "Partner",
    sensitivity: "High",
    retention: "5 years",
    dependencyCount: 14,
    vendorManaged: true,
    cryptoAgility: "Low",
    readiness: "Blocked",
    priority: "High",
    status: "Exception",
    migrationPattern: "Vendor roadmap with bounded exception",
    evidence: syntheticEvidenceFor("syn-sftp-07"),
  },
  {
    id: "syn-ssh-08",
    synthetic: true,
    asset: "Internal SSH Bastion",
    application: "Privileged Operations Entry",
    estateClass: "ots-cots",
    issueTypes: ["tls-protocol", "implementation-configuration", "cryptographic-dependency"],
    businessService: "Infrastructure operations",
    environment: "Production",
    owner: "Infrastructure Engineering",
    cryptographicUse: "Administrator authentication and session key exchange",
    protocol: "SSH v2",
    algorithm: "Curve25519 + Ed25519",
    credential: "Host and user keys",
    issuer: "SSH certificate authority",
    runtime: "Hardened Linux",
    exposure: "Restricted",
    sensitivity: "High",
    retention: "30 days",
    dependencyCount: 11,
    vendorManaged: false,
    cryptoAgility: "Moderate",
    readiness: "Assessing",
    priority: "Moderate",
    status: "Assessment",
    migrationPattern: "Client/server compatibility matrix",
    evidence: syntheticEvidenceFor("syn-ssh-08"),
  },
  {
    id: "syn-mobile-09",
    synthetic: true,
    asset: "Mobile Identity Broker",
    application: "Field Access Hub",
    estateClass: "third-party-saas",
    issueTypes: ["tls-protocol", "certificate-trust", "vendor-control"],
    businessService: "Mobile workforce",
    environment: "Pre-production",
    owner: "Identity Engineering",
    cryptographicUse: "Token signing and application TLS",
    protocol: "OIDC / TLS 1.3",
    algorithm: "ECDSA P-256 + ECDHE",
    credential: "Token-signing and TLS keys",
    issuer: "Cloud KMS and public CA",
    runtime: "Managed identity service",
    exposure: "Internet",
    sensitivity: "Moderate",
    retention: "24 hours",
    dependencyCount: 16,
    vendorManaged: true,
    cryptoAgility: "High",
    readiness: "Ready",
    priority: "Moderate",
    status: "Pilot",
    migrationPattern: "Provider-supported hybrid TLS evaluation",
    evidence: syntheticEvidenceFor("syn-mobile-09"),
  },
  {
    id: "syn-archive-10",
    synthetic: true,
    asset: "Research Archive Encryptor",
    application: "Long-Horizon Archive",
    estateClass: "source-code",
    issueTypes: ["implementation-configuration", "source-code-crypto-use", "cryptographic-dependency", "algorithm-key-strength"],
    businessService: "Records preservation",
    environment: "Development",
    owner: "Data Platform",
    cryptographicUse: "Long-lived envelope encryption key wrapping",
    protocol: "Object envelope encryption",
    algorithm: "RSA-OAEP-3072 + AES-256-GCM",
    credential: "Key-encryption key",
    issuer: "Cloud KMS",
    runtime: "Python 3.13",
    exposure: "Internal",
    sensitivity: "Critical",
    retention: "25 years",
    dependencyCount: 7,
    vendorManaged: false,
    cryptoAgility: "High",
    readiness: "Ready",
    priority: "High",
    status: "Migrating",
    migrationPattern: "Rewrap pilot with reversible key versioning",
    evidence: syntheticEvidenceFor("syn-archive-10"),
  },
] as const;

export const MATURITY_SCENARIOS: readonly MaturityScenario[] = [
  {
    id: "mature",
    label: "Scenario A",
    headline: "Mature environment",
    available: ["Strong CMDB", "Reliable ownership", "Certificate lifecycle tooling", "Crypto discovery", "ITSM automation", "TVM and cloud inventory"],
    strategy: "Integrate + orchestrate",
    customEngineering: "Low",
    manualEffort: "Low",
    integrationNeed: "Medium",
    timeToValue: "Faster",
    decision: "Preserve working systems of record; focus engineering on correlation, prioritization, and control-loop evidence.",
  },
  {
    id: "partial",
    label: "Scenario B",
    headline: "Partially mature",
    available: ["Useful enterprise tooling", "Incomplete inventories", "Inconsistent ownership", "Fragmented crypto visibility"],
    strategy: "Integrate + reconcile + close gaps",
    customEngineering: "Moderate",
    manualEffort: "Medium",
    integrationNeed: "High",
    timeToValue: "Balanced",
    decision: "Start with high-value sources, quantify unknowns, and automate reconciliation before expanding discovery breadth.",
  },
  {
    id: "fragmented",
    label: "Scenario C",
    headline: "Fragmented best-of-breed",
    available: ["Many overlapping tools", "Different schemas", "Weak correlation", "Siloed ownership"],
    strategy: "Normalize + correlate + orchestrate",
    customEngineering: "Moderate to high",
    manualEffort: "Medium",
    integrationNeed: "High",
    timeToValue: "Balanced",
    decision: "Create a thin canonical model and provenance graph; do not replace competent discovery products.",
  },
  {
    id: "low-visibility",
    label: "Scenario D",
    headline: "Low visibility / custom heavy",
    available: ["Limited crypto discovery", "Weak CMDB", "Little automation", "Incomplete ownership"],
    strategy: "Establish baseline + targeted discovery + custom ingestion",
    customEngineering: "High initially",
    manualEffort: "High",
    integrationNeed: "Medium",
    timeToValue: "Slower initially",
    decision: "Constrain scope, prioritize long-lived sensitive data, and build only the minimum collectors needed to establish evidence.",
  },
] as const;

export const MIGRATION_PATTERNS: readonly MigrationPattern[] = [
  {
    id: "tls",
    title: "TLS",
    scope: "Edge, gateway, service-to-service, and client compatibility",
    steps: ["Discover key exchange and signature dependencies", "Confirm platform support", "Test hybrid/PQC mode", "Pilot bounded traffic", "Stage rollout", "Rediscover and validate"],
    validation: "Handshake compatibility, performance, fallback behavior, certificate path, and observed configuration after rollout.",
    caveat: "Platform and client support determine the usable pattern; do not infer a visitor’s negotiated key exchange from TLS version alone.",
  },
  {
    id: "pki",
    title: "Enterprise PKI",
    scope: "CA hierarchy, profiles, enrollment, relying parties, and trust stores",
    steps: ["Inventory hierarchy", "Map certificate profiles", "Identify enrollment paths", "Assess clients and trust stores", "Run interoperability tests", "Stage hierarchy transition"],
    validation: "Issuance, path building, revocation, enrollment, verifier behavior, HSM support, and rollback rehearsal.",
    caveat: "Key establishment and digital signatures are different migrations with different dependencies.",
  },
  {
    id: "signing",
    title: "Code signing",
    scope: "Signing services, build pipelines, artifacts, and every verifier",
    steps: ["Inventory signers", "Map build and release paths", "Locate verifiers", "Select a target pattern", "Pilot dual-signing where supported", "Validate long-term verification"],
    validation: "Artifact verification across release, update, rollback, recovery, and archival paths.",
    caveat: "A standardized algorithm does not prove that a specific signing module or verifier implementation is validated or interoperable.",
  },
  {
    id: "vpn",
    title: "VPN / remote access",
    scope: "Gateways, clients, identity, device management, and network policy",
    steps: ["Inventory cryptographic dependencies", "Obtain vendor roadmap", "Build compatibility matrix", "Pilot managed cohort", "Stage rollout", "Monitor failures and drift"],
    validation: "Client coverage, authentication, session establishment, throughput, failover, and recovery.",
    caveat: "Vendor readiness and managed-client rollout constraints often dominate sequencing.",
  },
  {
    id: "vendor",
    title: "Vendor products",
    scope: "Products where algorithm and module choices are externally controlled",
    steps: ["Inventory product and version", "Request evidence-backed roadmap", "Map upgrade dependencies", "Set target and exception dates", "Pilot upgrade", "Replace if risk remains unacceptable"],
    validation: "Vendor evidence, installed-version readback, protocol observation, interoperability, and exception expiry.",
    caveat: "A roadmap is planning evidence, not proof that the installed product has migrated.",
  },
] as const;

export const CAPABILITY_QUESTIONS = [
  { capability: "Crypto discovery", yes: "Integrate and validate coverage", no: "Can an existing collector be extended?", fallback: "Targeted discovery" },
  { capability: "CMDB / asset truth", yes: "Enrich and reconcile", no: "Can cloud and endpoint inventory seed it?", fallback: "Minimum canonical asset index" },
  { capability: "Ownership", yes: "Route accountable work", no: "Can service catalog and repository CODEOWNERS help?", fallback: "Governed ownership campaign" },
  { capability: "PKI inventory", yes: "Correlate profiles and relying parties", no: "Can CA and lifecycle tooling export it?", fallback: "Targeted certificate census" },
  { capability: "ITSM workflow", yes: "Use existing work system", no: "Can an approved workflow tool carry evidence?", fallback: "Thin review queue, then integrate" },
  { capability: "HSM / KMS inventory", yes: "Map keys to workloads", no: "Can provider metadata be normalized?", fallback: "Read-only key-reference inventory" },
  { capability: "Cloud inventory", yes: "Correlate resources, termination points, keys, and owners", no: "Can account, subscription, and project APIs provide read-only metadata?", fallback: "Scoped cloud-resource census" },
  { capability: "Application inventory", yes: "Map applications to runtimes, repositories, libraries, and owners", no: "Can service catalogs and repositories seed the baseline?", fallback: "Targeted application census" },
  { capability: "Dependency mapping", yes: "Sequence producers, consumers, trust paths, and verifiers", no: "Can traffic, build, and configuration evidence establish critical edges?", fallback: "High-priority dependency workshops" },
  { capability: "Vendor readiness", yes: "Sequence upgrades and tests", no: "Is a supported roadmap available?", fallback: "Time-bound exception or replacement" },
] as const;

export const QUESTION_GROUPS: readonly QuestionGroup[] = [
  { category: "Scope", questions: ["Is the initial scope enterprise PKI, broader cryptographic discovery, or both?", "Which applications and business services enter the first migration wave?"] },
  { category: "Inventory", questions: ["Is there an existing cryptographic inventory?", "Which source is authoritative for assets, and how are conflicting records resolved?"] },
  { category: "PKI", questions: ["Which CA, certificate-lifecycle, HSM, and KMS technologies are material?", "How centralized are issuance, trust-store, and code-signing controls?"] },
  { category: "Infrastructure", questions: ["Which cloud, network, ingress, VPN, SSH, and service-mesh platforms terminate cryptography?", "Where are long-lived sensitive records protected or transported?"] },
  { category: "Vendors", questions: ["Which vendors, products, and installed versions control algorithms, modules, protocols, certificates, or keys?", "Which evidence-backed roadmaps, supported release dates, interoperability constraints, end-of-support dates, contractual commitments, and exception paths exist?"] },
  { category: "TVM context", questions: ["Which TVM or exposure-management sources can enrich assets, ownership, criticality, and Internet exposure?", "Where does TVM coverage stop being reliable?"] },
  { category: "Workflow", questions: ["Which system owns remediation work and exceptions?", "How are engineering owners assigned and how is validation evidence returned?"] },
  { category: "Engineering", questions: ["Is there an established crypto-agility standard?", "Which hybrid migration patterns and rollback paths are already being tested?"] },
  { category: "Success", questions: ["Which outcomes make the program successful: coverage, risk reduction, validated migration, or exception burn-down?", "What evidence is required before a migration can be called complete?"] },
] as const;
