import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { api, ApiError, dateLabel, humanize, selectedAssessmentId } from './api';
import { useApi } from './use-api';
import type { Session } from './contracts';
import type { AssessmentCatalog, AssessmentCommand, AssessmentDetail, AssessmentGate, AssessmentPackage, AssessmentSource, AssessmentSummary } from './assessment-contracts';
import './assessment.css';

type Fields = Record<string, unknown>;
type Command = (operation: string, targetId: string | undefined, fields: Fields) => Promise<void>;
type Navigate = (page: string, params?: Record<string, string>) => void;
const depthLabels: Record<string, string> = {
  routing: 'Route identification', inventory: 'Bounded inventory', dependency_cohort: 'Dependency cohort',
};
const statusLabels: Record<string, string> = {
  unanswered: 'Needs a first response', route_confirmed: 'Evidence route identified', unknown: 'Help identify the route',
  not_my_team: 'Needs a different team', blocked: 'Blocked', ready: 'Ready to work', in_progress: 'In progress',
  submitted: 'Waiting for review', accepted: 'Accepted for this demonstration', qualified: 'Qualified with limitations',
  changes_requested: 'Changes requested', not_submitted: 'Not submitted', needs_review: 'Needs re-review', rejected: 'Rejected',
};
const stagePurpose: Record<number, { task: string; effect: string; next: string }> = {
  1: { task: 'State the questions, included sources and information-handling boundary.', effect: 'Defines what this assessment may conclude and the boundaries of the Phase 1 report.', next: 'Sponsor and information owner review the boundary; the assessment lead identifies source routes.' },
  2: { task: 'Identify the responsible functions and permitted routes for selected sources.', effect: 'Records available and blocked routes without calling a supplied answer technical verification.', next: 'Assessment lead and sponsor review the source register, then investigators prepare bounded captures.' },
  3: { task: 'Review what each source package establishes and what remains unknown.', effect: 'Turns reviewed source records into defensible Phase 1 findings and limitations.', next: 'Technical reviewer examines each submitted package; lead and technical-review lead review the map gate.' },
  4: { task: 'Generate, read and submit an exact Phase 1 report snapshot.', effect: 'Freezes the current-state findings and qualifications that Phase 2 may rely on.', next: 'Sponsor and assessment lead review the handoff; the risk lead establishes the Phase 2 basis.' },
  5: { task: 'Describe the Phase 2 method and its treatment of uncertainty and priority.', effect: 'Makes consequence and recommendation reasoning explicit rather than inventing numerical scores.', next: 'Risk lead and sponsor review the method before risk analysis is relied upon.' },
  6: { task: 'Connect supported facts to attributed business context, constraints and recommendations.', effect: 'Creates the Phase 2 risk register entries and specific decisions needed.', next: 'Business reviewer challenges each analysis; risk and business-review leads review the analysis gate.' },
  7: { task: 'Choose the exact Phase 1 basis, generate Phase 2, read it and complete its final review.', effect: 'Freezes the risk and recommendation report, with limitations and traceable reliance.', next: 'Sponsor and risk lead review the exact Phase 2 deliverable. Migration execution remains outside this workflow.' },
};
function status(value: string) { return statusLabels[value] || humanize(value); }
function routeStage(): number { return Number(new URLSearchParams(window.location.hash.split('?')[1]).get('stage')) || 0; }
function Status({ value }: { value: string }) { return <span className={`assessment-status state-${value}`}>{status(value)}</span>; }
function Help({ children }: { children: ReactNode }) { return <p className="assessment-help">{children}</p>; }
function Field({ label, value, onChange, multiline = false, required = false, type = 'text', hint }: {
  label: string; value: string; onChange: (value: string) => void; multiline?: boolean; required?: boolean; type?: string; hint?: string;
}) {
  const id = useId();
  return <div className="assessment-field"><label htmlFor={id}>{label}{!required && <small> (optional at this step)</small>}</label>
    {multiline ? <textarea id={id} aria-describedby={hint ? `${id}-hint` : undefined} rows={3} value={value} maxLength={2048} onChange={event => onChange(event.target.value)} required={required} /> : <input id={id} aria-describedby={hint ? `${id}-hint` : undefined} type={type} value={value} maxLength={500} onChange={event => onChange(event.target.value)} required={required} />}
    {hint && <small id={`${id}-hint`}>{hint}</small>}</div>;
}

export function AssessmentWorkspace({ session, onNavigate }: { session: Session; onNavigate: Navigate }) {
  const [id, setId] = useState(selectedAssessmentId);
  const [stage, setStage] = useState(routeStage);
  const [fromIntake] = useState(() => new URLSearchParams(window.location.hash.split('?')[1]).get('from') === 'intake');
  const [fromDiscovery] = useState(() => new URLSearchParams(window.location.hash.split('?')[1]).get('from') === 'discovery');
  const [revision, setRevision] = useState(0);
  const [name, setName] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [receipt, setReceipt] = useState<{ operation: string; revision: number; targetId?: string }>();
  const pending = useRef<{ key: string; payload: string; command: AssessmentCommand } | undefined>(undefined);
  const pendingCreate = useRef<{ key: string; payload: string; mode: 'fresh' | 'worked_example' } | undefined>(undefined);
  const catalog = useApi<AssessmentCatalog>('/api/assessments/catalog');
  const assessments = useApi<AssessmentSummary[]>('/api/assessments', revision);
  const detail = useApi<AssessmentDetail>(id ? `/api/assessments/${encodeURIComponent(id)}` : '/api/assessments/catalog', revision);
  const lastDetail = useRef<AssessmentDetail | undefined>(undefined);
  if (detail.data && 'scope' in detail.data) lastDetail.current = detail.data;
  useEffect(() => { const update = () => { setId(selectedAssessmentId()); setStage(routeStage()); setError(''); setReceipt(undefined); pending.current = undefined; }; window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  const loaded = id && lastDetail.current?.id === id ? lastDetail.current : undefined;
  const current = loaded ? { ...loaded, sources: loaded.sources.filter(source => loaded.scope.includedFamilyIds.includes(source.familyId)), packages: loaded.packages.filter(item => loaded.scope.includedFamilyIds.includes(item.familyId)) } : undefined;
  const shownStage = stage || current?.stage || 1;
  function open(assessmentId: string, nextStage?: number) { onNavigate('assessments', { assessment: assessmentId, ...(nextStage ? { stage: String(nextStage) } : {}), ...(fromDiscovery ? { from: 'discovery' } : fromIntake ? { from: 'intake' } : {}) }); }
  async function create(mode: 'fresh' | 'worked_example', retry = false) {
    if (!session.csrfToken || busy) return;
    const payload = JSON.stringify({ name: name.trim() || (mode === 'fresh' ? 'New synthetic assessment' : 'Worked assessment example'), mode });
    if (!retry && pendingCreate.current && pendingCreate.current.payload !== payload) { setError('The previous creation result is uncertain. Retry that original request unchanged or refresh the assessment list before starting something different.'); return; }
    pendingCreate.current ||= { key: crypto.randomUUID(), payload, mode };
    setBusy(true); setError('');
    try {
      const result = await api<AssessmentDetail>('/api/assessments', { method: 'POST', headers: { 'X-PQC-CSRF': session.csrfToken, 'Idempotency-Key': pendingCreate.current.key }, body: pendingCreate.current.payload });
      pendingCreate.current = undefined;
      setRevision(value => value + 1); open(result.id, mode === 'fresh' ? 1 : undefined);
    } catch (reason) {
      if (reason instanceof ApiError && reason.status < 500) pendingCreate.current = undefined;
      setError(reason instanceof ApiError ? reason.message : 'The creation result is uncertain. Retry the unchanged request below; its identity is preserved to avoid duplicate assessments.');
    }
    finally { setBusy(false); }
  }
  async function send(command: AssessmentCommand) {
    if (!current || !session.csrfToken || busy) return;
    const payload = JSON.stringify(command);
    if (pending.current && pending.current.payload !== payload) { setError('A previous save is not confirmed. Retry that unchanged request before changing its content. Your entered answers remain on this page.'); return; }
    pending.current ||= { key: crypto.randomUUID(), payload, command };
    setBusy(true); setError('');
    try {
      const result = await api<AssessmentDetail>(`/api/assessments/${encodeURIComponent(current.id)}/commands`, { method: 'POST', headers: { 'X-PQC-CSRF': session.csrfToken, 'Idempotency-Key': pending.current.key }, body: payload });
      pending.current = undefined; setReceipt({ operation: command.operation, revision: result.revision, targetId: command.targetId ?? undefined }); setRevision(value => value + 1);
    } catch (reason) {
      if (reason instanceof ApiError && reason.status < 500) pending.current = undefined;
      if (reason instanceof ApiError && reason.status === 409) { setRevision(value => value + 1); setError(`${reason.message} Your entered answers have been kept; review the refreshed requirements before submitting again.`); }
      else setError(reason instanceof ApiError ? reason.message : 'The save result is uncertain. Retry the identical request below; it will not create a duplicate.');
    } finally { setBusy(false); }
  }
  const command: Command = async (operation, targetId, fields) => { if (current) await send({ operation, targetId: targetId ?? null, fields, expectedRevision: current.revision }); };
  const allowed = (operation: string) => !busy && !detail.loading && !!current?.availableOperations.includes(operation);
  const persona = catalog.data?.personas.find(item => item.principalId === `synthetic-demo:${session.role}`);
  return <div className="assessment-workspace">
    <header className="assessment-header"><div><p className="eyebrow">GUIDED ASSESSMENT / PHASES 1 & 2</p><h1>{current?.name || 'Build an assessment, one useful answer at a time.'}</h1><p>Find the right people and systems, establish defensible facts, and turn those facts into a reviewable assessment.</p></div>{id && <button className="button secondary" onClick={() => onNavigate('assessments', { assessment: '' })}>All assessments</button>}</header>
    <div className="assessment-boundary"><strong>Synthetic demonstration</strong><span>Responses and decisions are persisted locally. No enterprise acceptance, external request, or migration is performed.</span></div>
    {fromIntake && current && <section className="assessment-intake-return"><div><h2>Continue the source request journey</h2><p>This assessment now has a durable identity. You can identify sources and gather attributed responses in Discovery & intake; technical evidence admission and reports still follow the review gates below.</p></div><button className="button primary" disabled={busy} onClick={() => onNavigate('intake', { assessment: current.id })}>Return to Discovery & intake →</button></section>}
    {fromDiscovery && current && <section className="assessment-intake-return"><div><h2>Assign the first five-question request</h2><p>The assessment now has a durable identity. Ask for known products, useful contacts or an explicit unknown; technical collection and report acceptance retain their own gates.</p></div><button className="button primary" disabled={busy} onClick={() => onNavigate('discovery', { assessment: current.id })}>Return to discovery requests →</button></section>}
    {error && <div className="notice error" role="alert"><span>{error}</span>{pending.current && <button className="button secondary" disabled={busy} onClick={() => void send(pending.current!.command)}>Retry identical request</button>}{pendingCreate.current && <button className="button secondary" disabled={busy} onClick={() => void create(pendingCreate.current!.mode, true)}>Retry original assessment creation</button>}</div>}
    {receipt && <section className="assessment-receipt" role="status"><strong>Recorded: {humanize(receipt.operation)}</strong><span>Assessment revision {receipt.revision}. {receipt.targetId && `Reference: ${receipt.targetId}. `}See the current requirements and next task below.</span><button className="text-button" onClick={() => setReceipt(undefined)}>Dismiss receipt</button></section>}
    {(catalog.error || id && detail.error) && <div className="notice error" role="alert">{catalog.error || detail.error}<button className="button secondary" onClick={() => { catalog.reload(); detail.reload(); }}>Reload assessment</button></div>}
    {catalog.loading || id && detail.loading ? <div className="loading" role="status">Loading the assessment and its recorded requirements…</div> : null}
    {!id && <>
      <div className="assessment-entry-grid"><section className="analysis-panel assessment-start"><p className="eyebrow">PRIMARY PATH</p><h2>Start an assessment</h2><p>Begin with scope and the questions that need answering. Sample evidence is available later; no gates begin approved.</p><Field label="Assessment name" value={name} onChange={setName} hint="Use a synthetic service or cohort name. Do not enter real enterprise data." /><button className="button primary" disabled={busy || session.role !== 'analyst'} onClick={() => void create('fresh')}>{busy ? 'Creating…' : 'Start assessment →'}</button>{session.role !== 'analyst' && <Help>Sign in as the assessment lead (analyst) to create an assessment. Other personas can work within their assigned responsibilities.</Help>}</section>
        <section className="analysis-panel assessment-example"><p className="eyebrow">SECONDARY PATH</p><h2>Explore a worked example</h2><p>Inspect all seven stages using a documented synthetic scenario. Any preloaded decisions are explicitly simulated—not your approval.</p><button className="button secondary" disabled={busy || session.role !== 'analyst'} onClick={() => void create('worked_example')}>Create a separate worked example</button><Help>Every example gets its own history. Existing assessments are never reset or deleted.</Help></section></div>
      <section className="analysis-panel"><header className="block-heading"><div><p className="eyebrow">CONTINUE YOUR WORK</p><h2>Assessments</h2></div><button className="text-button" onClick={assessments.reload}>Refresh list</button></header>{assessments.loading && <p role="status">Loading assessments…</p>}{assessments.error && <p role="alert">{assessments.error}</p>}{assessments.data?.length === 0 && <p>No assessments yet. Start with one bounded application or service cohort.</p>}<div className="assessment-list">{assessments.data?.map(item => <button key={item.id} className="assessment-list-item" onClick={() => open(item.id)}><span><strong>{item.name}</strong><small>{item.mode === 'worked_example' ? 'Worked example · simulated history' : 'Fresh guided assessment'} · revision {item.revision}</small></span><span>Stage {item.stage} <span aria-hidden="true">→</span></span></button>)}</div></section>
    </>}
    {current && catalog.data && <>
      <div className="assessment-context"><span>Signed in: <strong>{persona?.label || humanize(session.role || 'viewer')}</strong></span><span>Revision {current.revision}</span>{current.mode === 'worked_example' && <strong className="badge attention">Worked example / simulated scenario history</strong>}<span className="mono">{current.id}</span></div>
      <nav className="assessment-stages" aria-label="Assessment stages">{catalog.data.stages.map(item => <button key={item.id} aria-label={`Stage ${item.id}: ${item.label}`} aria-current={shownStage === item.id ? 'step' : undefined} className={shownStage === item.id ? 'selected' : ''} onClick={() => open(current.id, item.id)}><span>{String(item.id).padStart(2, '0')}</span><strong>{item.label}</strong>{item.id === current.stage && <small>Current work</small>}</button>)}</nav>
      <div className="assessment-progress"><section><p className="eyebrow">ENABLEMENT / PEOPLE & ROUTES</p><strong>{current.sources.filter(source => source.state === 'route_confirmed').length} of {current.sources.length}</strong><span>source routes identified</span></section><section><p className="eyebrow">DATA / ADMITTED SAMPLE EVIDENCE</p><strong>{current.sources.filter(source => source.observationIds.length > 0).length} of {current.sources.length}</strong><span>sources with admitted observations</span></section><p>These are different dimensions. An identified route is not collected evidence, and synthetic evidence is not enterprise coverage.</p></div>
      {current.metrics && <div className="assessment-progress"><section><p className="eyebrow">QUESTION ANSWERABILITY</p><strong>{current.metrics.questionAnswerability.supported} of {current.metrics.questionAnswerability.total}</strong><span>supported · {current.metrics.questionAnswerability.qualified} qualified · {current.metrics.questionAnswerability.unanswered} unanswered</span></section><section><p className="eyebrow">DECISION BACKLOG</p><strong>{current.metrics.decisionBacklog.pendingSlots}</strong><span>review responsibilities pending · oldest {current.metrics.decisionBacklog.oldestAgeDays} days</span></section><p>{current.metrics.questionAnswerability.definition} {current.metrics.decisionBacklog.definition}</p></div>}
      <section className="assessment-next"><div><p className="eyebrow">NEXT USEFUL ACTION</p>{current.nextActions.length ? <><h2>{current.nextActions[0].label}</h2><button className="button primary" onClick={() => open(current.id, current.nextActions[0].stage)}>Go to this task →</button></> : <><h2>No immediate action is assigned to this view.</h2><p>Inspect the gate requirements or sign in as the designated reviewer. This does not assert that the assessment is complete.</p></>}</div><div><h3>Other work and dependencies</h3>{current.nextActions.slice(1, 4).map(action => <button className="text-button" key={`${action.operation}-${action.targetId}`} onClick={() => open(current.id, action.stage)}>{action.label} →</button>)}<p>{current.sources.filter(source => ['blocked', 'not_my_team', 'unknown', 'unanswered'].includes(source.state)).length} sources need a response or routing help. {current.packages.filter(item => item.state === 'submitted').length} packages await review.</p></div></section>
      <header className="assessment-stage-heading"><p className="eyebrow">STAGE {shownStage} / {shownStage <= 4 ? 'PHASE 1' : 'PHASE 2'}</p><h2>{catalog.data.stages.find(item => item.id === shownStage)?.question}</h2>{shownStage > current.stage && <p className="notice muted-notice">Look ahead and prepare draft work here. The server checks prerequisites before consequential transitions.</p>}</header>
      {stagePurpose[shownStage] && <section className="assessment-stage-purpose" aria-label="Task and report consequence"><dl><div><dt>Your task</dt><dd>{stagePurpose[shownStage].task}</dd></div><div><dt>What changes in the report</dt><dd>{stagePurpose[shownStage].effect}</dd></div><div><dt>Who acts next</dt><dd>{stagePurpose[shownStage].next}</dd></div></dl><button className="text-button" disabled={busy} onClick={() => onNavigate('assessment-work', { assessment: current.id })}>Return to received forms and record review →</button></section>}
      {shownStage === 1 && <ScopeStage assessment={current} catalog={catalog.data} command={command} enabled={allowed('update_scope')} />}
      {shownStage === 2 && <SourceStage assessment={current} command={command} allowed={allowed} />}
      {shownStage === 3 && <PackageStage assessment={current} command={command} allowed={allowed} onNavigate={onNavigate} />}
      {shownStage === 4 && <ReportStage assessment={current} phase="phase1" command={command} enabled={allowed('generate_report')} onNavigate={onNavigate} />}
      {shownStage === 5 && <MethodStage assessment={current} command={command} enabled={allowed('set_method')} onNavigate={onNavigate} />}
      {shownStage === 6 && <AnalysisStage assessment={current} command={command} allowed={allowed} onNavigate={onNavigate} />}
      {shownStage === 7 && <ReportStage assessment={current} phase="phase2" command={command} enabled={allowed('generate_report')} onNavigate={onNavigate} />}
      <section className="assessment-gates"><p className="eyebrow">CONSEQUENTIAL TRANSITIONS / C#-EVALUATED REQUIREMENTS</p><h2>Review gates for this stage</h2>{current.gates.filter(gate => gate.stage === shownStage).map(gate => <GateCard key={gate.id} gate={gate} assessment={current} role={persona?.role || ''} command={command} allowed={allowed} />)}{!current.gates.some(gate => gate.stage === shownStage) && <p>This stage prepares evidence for the next review gate; saving an answer is not acceptance.</p>}</section>
      <section className="assessment-stage-handoff"><h3>Continue the assessment</h3><p>Opening another stage does not submit work or satisfy a gate. Save the current form and complete the designated decisions before relying on its result.</p><div className="assessment-inline-actions">{shownStage > 1 && <button className="button secondary" disabled={busy} onClick={() => open(current.id, shownStage - 1)}>Previous: {catalog.data.stages.find(item => item.id === shownStage - 1)?.label}</button>}{shownStage < 7 ? <button className="button secondary" disabled={busy} onClick={() => open(current.id, shownStage + 1)}>Next: {catalog.data.stages.find(item => item.id === shownStage + 1)?.label}</button> : <button className="button secondary" disabled={busy} onClick={() => onNavigate('reports', { assessment: current.id })}>Open assessment report history</button>}</div></section>
      {current.questions.length > 0 && <details className="assessment-history"><summary>Questions this assessment must answer</summary><div className="assessment-question-list">{current.questions.map(question => <article key={question.id}><h3>{question.text}</h3><p>{question.whyItMatters}</p><p><strong>Complete when:</strong> {question.doneWhen}</p><Status value={question.state} /></article>)}</div></details>}
      <details className="assessment-history"><summary>Participants and immutable workflow history</summary><h3>Demonstration participants</h3><ul>{current.assignments.map(person => <li key={person.principalId}>{person.label} · {humanize(person.role)}</li>)}</ul><h3>Recorded events</h3><ol>{current.events.slice().reverse().map((event, index) => <li key={`${event.revision}-${index}`}><strong>r{event.revision} · {humanize(event.operation)}</strong> · {event.principalId} · {dateLabel(event.createdAt)}<span>{event.origin === 'simulated' || event.origin?.includes('scenario') ? 'Simulated scenario history' : humanize(event.origin || 'user-recorded')} · {event.targetId}</span></li>)}</ol></details>
    </>}
  </div>;
}

function ScopeStage({ assessment, catalog, command, enabled }: { assessment: AssessmentDetail; catalog: AssessmentCatalog; command: Command; enabled: boolean }) {
  const [scope, setScope] = useState(assessment.scope);
  const [area, setArea] = useState('');
  const set = (key: 'objective' | 'handling' | 'method' | 'cycleGoal' | 'reviewDate', value: string) => setScope(current => ({ ...current, [key]: value }));
  function toggle(id: string) {
    setScope(current => {
      const included = current.includedFamilyIds.includes(id);
      const depthByFamily = { ...current.depthByFamily };
      const excludedReasons = { ...current.excludedReasons };
      if (included) delete depthByFamily[id]; else { depthByFamily[id] = 'routing'; delete excludedReasons[id]; }
      return { ...current, includedFamilyIds: included ? current.includedFamilyIds.filter(item => item !== id) : [...current.includedFamilyIds, id], depthByFamily, excludedReasons };
    });
  }
  function saveScope() {
    const { objective, handling, method, cycleGoal, reviewDate, includedFamilyIds, excludedReasons, depthByFamily } = scope;
    void command('update_scope', undefined, { objective, handling, method, cycleGoal, reviewDate, includedFamilyIds, excludedReasons, depthByFamily });
  }
  return <form className="analysis-panel assessment-form" onSubmit={event => { event.preventDefault(); saveScope(); }}><h3>Define a bounded, useful assessment</h3><Help>Record a proposed boundary and handling route for review. Completed fields are not authorization. Depth expresses planned work—not evidence already achieved.</Help><fieldset disabled={!enabled}><div className="assessment-form-grid"><Field label="Assessment objective" value={scope.objective} onChange={value => set('objective', value)} multiline required /><Field label="Current cycle goal" value={scope.cycleGoal} onChange={value => set('cycleGoal', value)} multiline required hint="What useful result should this cycle produce?" /><Field label="Evidence-handling route" value={scope.handling} onChange={value => set('handling', value)} multiline required /><Field label="Assessment method / agreed approach" value={scope.method} onChange={value => set('method', value)} multiline required /><Field label="Next review date" value={scope.reviewDate} onChange={value => set('reviewDate', value)} type="date" required /></div>
      <div className="assessment-family-heading"><div><h3>Coverage boundary and expected depth</h3><p>Choose relevant source families. Excluded families need a reason; scope is not an investigation filter.</p></div><label>Show estate area<select value={area} onChange={event => setArea(event.target.value)}><option value="">All ten areas</option>{Array.from(new Set(catalog.sourceFamilies.map(source => source.areaId))).sort().map(id => <option key={id}>{id}</option>)}</select></label></div>
      <div className="assessment-scope-list">{catalog.sourceFamilies.filter(source => !area || source.areaId === area).map(source => { const included = scope.includedFamilyIds.includes(source.familyId); return <article key={source.familyId}><label className="assessment-check"><input type="checkbox" checked={included} onChange={() => toggle(source.familyId)} /><span><strong>{source.name}</strong><small>{source.areaId} · Recognition examples: {source.examples.join(', ') || 'Confirm the actual product with the responsible team.'}</small></span></label>{included ? <label className="assessment-field"><span>Expected evidence depth</span><select value={scope.depthByFamily[source.familyId] || 'routing'} onChange={event => setScope(current => ({ ...current, depthByFamily: { ...current.depthByFamily, [source.familyId]: event.target.value } }))}>{(catalog.depthOptions || Object.entries(depthLabels).map(([id, label]) => ({ id, label }))).map(item => <option key={item.id} value={item.id}>{depthLabels[item.id] || item.label}</option>)}</select></label> : <Field label="Reason outside this assessment" value={scope.excludedReasons[source.familyId] || ''} onChange={value => setScope(current => ({ ...current, excludedReasons: { ...current.excludedReasons, [source.familyId]: value } }))} required />}</article>; })}</div>
      <button className="button primary" type="submit">Save scope draft</button></fieldset>{!enabled && <Help>Only the assessment lead can edit scope. Recorded scope remains visible to other participants.</Help>}</form>;
}

function SourceStage({ assessment, command, allowed }: { assessment: AssessmentDetail; command: Command; allowed: (operation: string) => boolean }) {
  const [selected, setSelected] = useState(assessment.sources[0]?.familyId || '');
  const source = assessment.sources.find(item => item.familyId === selected);
  return <div className="assessment-task-layout"><section className="analysis-panel assessment-task-list"><h3>Identify teams and information sources</h3><Help>The first answer can be a team, a system of record, an existing reference, or a request for routing help.</Help>{assessment.sources.map(item => <button className={selected === item.familyId ? 'selected' : ''} key={item.familyId} onClick={() => setSelected(item.familyId)}><strong>{item.name}</strong><Status value={item.state} /><small>{item.ownerFunction || 'Owner not yet identified'}</small></button>)}{!assessment.sources.length && <p>Select at least one family in assessment scope first.</p>}</section>{source && <SourceForm key={source.familyId} source={source} command={command} allowed={allowed} />}</div>;
}

function SourceForm({ source, command, allowed }: { source: AssessmentSource; command: Command; allowed: (operation: string) => boolean }) {
  const [fields, setFields] = useState({ state: source.state === 'unanswered' ? 'unknown' : source.state, systemOfRecord: source.systemOfRecord, product: source.product, ownerFunction: source.ownerFunction, accessRoute: source.accessRoute, note: source.note, dueAt: source.dueAt, assertedBy: source.assertedBy || '' });
  const set = (key: keyof typeof fields, value: string) => setFields(current => ({ ...current, [key]: value }));
  return <section className="analysis-panel assessment-task-detail"><p className="eyebrow">SOURCE ENABLEMENT / {source.areaId}</p><h3>What is the system of record for {source.name.toLowerCase()}?</h3><p className="assessment-recognition"><strong>Recognition examples, not selected products:</strong> {source.examples.join(', ') || 'Ask the responsible function to identify the exact platform.'}</p><Help>Why we ask: locate existing information and the teams familiar with it. A name or referral can start the investigation. The coordinator records approval and technical details before marking a route confirmed; saving this response does not grant access or verify cryptographic behavior.</Help><form onSubmit={event => { event.preventDefault(); void command('source_response', source.familyId, fields); }}><fieldset disabled={!allowed('source_response')}><label className="assessment-field"><span>What can you establish now?</span><select value={fields.state} onChange={event => set('state', event.target.value)}><option value="unknown">I do not know yet — help identify the route</option><option value="route_confirmed">I can identify the source and responsible function</option><option value="not_my_team">Not my team — suggest the right function</option><option value="blocked">The route is blocked — explain the barrier</option></select></label><Field label="Person or function supplying this answer" value={fields.assertedBy} onChange={value => set('assertedBy', value)} required hint="Identify whose statement you are recording. The application separately records your signed-in identity as the recorder." /><Field label="System of record or existing reference" value={fields.systemOfRecord} onChange={value => set('systemOfRecord', value)} required={fields.state === 'route_confirmed'} /><Field label="Actual product / edition / version" value={fields.product} onChange={value => set('product', value)} required={fields.state === 'route_confirmed'} /><Field label={fields.state === 'not_my_team' ? 'Suggested responsible function' : 'Responsible function'} value={fields.ownerFunction} onChange={value => set('ownerFunction', value)} required={fields.state === 'route_confirmed'} /><Field label="Approved read-only evidence route" value={fields.accessRoute} onChange={value => set('accessRoute', value)} required={fields.state === 'route_confirmed'} /><Field label="What is known, missing, or blocked?" value={fields.note} onChange={value => set('note', value)} multiline required /><Field label="Expected follow-up date" value={fields.dueAt} onChange={value => set('dueAt', value)} type="date" required /><button className="button primary">Save source response</button></fieldset></form>{source.respondedBy && <Help>Previous response supplied by {source.assertedBy || 'not recorded'}; recorded by authenticated participant {source.respondedBy}.</Help>}
    <div className="assessment-sample"><h4>Admit bounded sample evidence</h4><p>{source.observationIds.length} admitted observations · {source.subjectIds.length} subjects. This is separate from the routing response.</p><button className="button secondary" disabled={!allowed('admit_sample') || source.state !== 'route_confirmed'} onClick={() => void command('admit_sample', source.familyId, {})}>Admit this source’s synthetic sample</button><Help>The C# application checks scope, authorization gates, and the confirmed route. No real source or credential is accessed.</Help></div></section>;
}

function PackageStage({ assessment, command, allowed, onNavigate }: { assessment: AssessmentDetail; command: Command; allowed: (operation: string) => boolean; onNavigate: Navigate }) {
  const [selected, setSelected] = useState(assessment.packages[0]?.familyId || '');
  const item = assessment.packages.find(value => value.familyId === selected);
  return <div className="assessment-task-layout"><section className="analysis-panel assessment-task-list"><h3>Evidence review packages</h3><Help>One coherent outcome per package—not a checkbox for every finding. Material disagreements remain visible.</Help>{assessment.packages.map(value => <button key={value.id} className={selected === value.familyId ? 'selected' : ''} onClick={() => setSelected(value.familyId)}><strong>{value.label}</strong><Status value={value.state} /><small>{value.evidenceCount} observations · {value.subjectCount} subjects</small></button>)}{!assessment.packages.length && <p>Review source records or record a missing-source limitation in Assessment work before preparing an inventory package.</p>}</section>{item && <PackageForm key={item.id} item={item} assessmentId={assessment.id} command={command} allowed={allowed} onNavigate={onNavigate} />}</div>;
}

function PackageForm({ item, assessmentId, command, allowed, onNavigate }: { item: AssessmentPackage; assessmentId: string; command: Command; allowed: (operation: string) => boolean; onNavigate: Navigate }) {
  const [conclusion, setConclusion] = useState(item.conclusion);
  const [qualification, setQualification] = useState(item.qualification);
  return <section className="analysis-panel assessment-task-detail">
    <p className="eyebrow">ESTABLISH DEFENSIBLE FACTS</p><h3>{item.label}</h3><Status value={item.state} />
    <p>{item.evidenceCount} observations and {item.subjectCount} subjects in the package. Review the evidence and material limitations before submitting.</p>
    {item.plannedDepth && <div className="assessment-recognition"><strong>Planned depth: {depthLabels[item.plannedDepth] || humanize(item.plannedDepth)}</strong>Established depth: {depthLabels[item.achievedDepth || ''] || humanize(item.achievedDepth || 'not_established')}.{item.depthLimitation && <p>{item.depthLimitation}</p>}</div>}
    {item.evidenceCount === 0 && <Help>No observations are admitted. This package can record an explicit missing-evidence limitation, not a supported technical conclusion. Qualified acceptance does not make the missing facts known.</Help>}
    <div className="assessment-inline-actions"><button className="button secondary" onClick={() => onNavigate('overview', { assessment: assessmentId, family: item.familyId })}>Inspect this source’s estate</button><button className="button secondary" onClick={() => onNavigate('actions', { assessment: assessmentId, family: item.familyId })}>Inspect findings and limitations</button></div>
    <form onSubmit={event => { event.preventDefault(); void command('submit_package', item.familyId, { conclusion, qualification }); }}><fieldset disabled={!allowed('submit_package')}>
      <Field label="What does the evidence establish?" value={conclusion} onChange={setConclusion} multiline required />
      <Field label="Unresolved limitations and consequences" value={qualification} onChange={setQualification} multiline required={item.evidenceCount === 0} />
      <Help>Submission freezes package membership and evidence references. A statement of completion is not a substitute for evidence.</Help>
      <button className="button primary">Submit package for technical review</button>
    </fieldset></form>
    <ReviewForm enabled={allowed('review_package') && item.state === 'submitted'} title="Technical reviewer disposition" onSubmit={fields => command('review_package', item.familyId, fields)} />
  </section>;
}

function ReviewForm({ enabled, title, onSubmit, gate = false }: { enabled: boolean; title: string; onSubmit: (fields: Fields) => Promise<void>; gate?: boolean }) {
  const [fields, setFields] = useState({ decision: '', rationale: '', qualification: '', reviewDate: '' });
  const [confirm, setConfirm] = useState(false);
  const set = (key: keyof typeof fields, value: string) => { setFields(current => ({ ...current, [key]: value })); setConfirm(false); };
  if (!enabled) return <div className="assessment-review-waiting"><strong>{title}</strong><Help>Available to the designated reviewer after submission. The server checks role, revision and separation of duties. An analyst’s submission does not supply reviewer acceptance.</Help></div>;
  return <form className="assessment-review-form" onSubmit={event => { event.preventDefault(); if (!confirm) setConfirm(true); else { void onSubmit(fields); setConfirm(false); } }}><h4>{title}</h4><fieldset><label className="assessment-field"><span>Decision requested for this exact revision</span><select value={fields.decision} onChange={event => set('decision', event.target.value)} required><option value="">Choose a disposition</option><option value="accepted">Accept the stated assessment position</option><option value="qualified">Accept with explicit limitations</option><option value={gate ? 'rejected' : 'changes_requested'}>{gate ? 'Reject this submission' : 'Request changes'}</option></select></label><Field label="Evidence-based decision rationale" value={fields.rationale} onChange={value => set('rationale', value)} multiline required /><Field label="Limitation, consequence and follow-up owner" value={fields.qualification} onChange={value => set('qualification', value)} multiline required={fields.decision === 'qualified'} /><Field label="Follow-up review date" value={fields.reviewDate} onChange={value => set('reviewDate', value)} type="date" required />{confirm && <div className="assessment-check-answers" role="region" aria-label="Check your decision"><strong>Check before recording</strong><p>{status(fields.decision)}: {fields.rationale}</p>{fields.qualification && <p>Limitation: {fields.qualification}</p>}<p>Next review: {fields.reviewDate}.</p><p>This records a synthetic assessment decision for the submitted revision. It does not authorize a migration or impersonate the owner’s acceptance. Qualifying missing evidence records an unresolved limitation; it does not answer the technical question.</p><button type="button" className="text-button" onClick={() => setConfirm(false)}>Change my answers</button></div>}<button className="button secondary">{confirm ? 'Confirm and record this decision' : 'Check decision before recording'}</button></fieldset></form>;
}

function GateCard({ gate, assessment, role, command, allowed }: { gate: AssessmentGate; assessment: AssessmentDetail; role: string; command: Command; allowed: (operation: string) => boolean }) {
  const [documentId, setDocumentId] = useState(gate.documentId || '');
  const requiresDocument = gate.id.endsWith('G03');
  const documents = assessment.documents.filter(document => document.phase === (gate.id.includes('P1') ? 'phase1' : 'phase2'));
  const satisfied = gate.requirements.every(requirement => requirement.satisfied);
  return <article className="analysis-panel assessment-gate">
    <header><div><p className="eyebrow">{gate.id}</p><h3>{gate.name}</h3></div><Status value={gate.state} /></header>
    <p>Required review functions: {gate.requiredRoles.map(humanize).join(', ')}.</p>
    <ul className="assessment-requirements">{gate.requirements.map((requirement, index) => <li key={index} className={requirement.satisfied ? 'satisfied' : ''}><span aria-hidden="true">{requirement.satisfied ? '✓' : '○'}</span><span>{requirement.label}<small>{requirement.satisfied ? 'Requirement met' : 'Still required'}</small></span></li>)}</ul>
    {requiresDocument && <label className="assessment-field"><span>Exact report to submit for this gate</span><select value={documentId} onChange={event => setDocumentId(event.target.value)}><option value="">Choose a report revision</option>{documents.map(document => <option value={document.id} key={document.id}>{dateLabel(document.createdAt)} · {document.id}</option>)}</select></label>}
    <button className="button secondary" disabled={!allowed('submit_gate') || (!requiresDocument && !satisfied) || ['submitted', 'accepted', 'qualified'].includes(gate.state) || requiresDocument && !documentId || (gate.stage >= 5 ? role !== 'risk-lead' : role !== 'assessment-lead')} onClick={() => void command('submit_gate', gate.id, requiresDocument ? { reportId: documentId } : {})}>Submit this gate for review</button>
    {requiresDocument && <Help>Selecting a report does not satisfy a gate by itself. On submission the server evaluates that exact report and all remaining requirements.</Help>}
    {!satisfied && <Help>The items above explain what must be established. Unrelated preparation can continue.</Help>}
    {gate.documentId && <p><strong>Submitted report:</strong> <code>{gate.documentId}</code></p>}
    <ReviewForm gate enabled={allowed('decide_gate') && gate.state === 'submitted' && gate.requiredRoles.includes(role) && !gate.decisions.some(decision => decision.role === role && decision.fingerprint === gate.fingerprint)} title="Review this submitted gate" onSubmit={fields => command('decide_gate', gate.id, fields)} />
    {gate.decisions.length > 0 && <details><summary>Recorded decisions for this gate</summary>{gate.decisions.map((decision, index) => <article className="assessment-decision" key={index}><strong>{status(decision.decision)}</strong><p>{decision.rationale}</p>{decision.qualification && <p>Limitation: {decision.qualification}</p>}<small>{decision.principalId} · {humanize(decision.role || '')} · {dateLabel(decision.createdAt)} · {decision.origin?.includes('scenario') ? 'Simulated scenario decision' : humanize(decision.origin || 'recorded participant decision')}</small></article>)}</details>}
  </article>;
}

function MethodStage({ assessment, command, enabled, onNavigate }: { assessment: AssessmentDetail; command: Command; enabled: boolean; onNavigate: Navigate }) {
  const [fields, setFields] = useState({ name: assessment.method.name, description: assessment.method.description, confidenceRules: assessment.method.confidenceRules, prioritizationRules: assessment.method.prioritizationRules });
  const basis = assessment.documents.find(document => document.phase === 'phase1' && document.id === assessment.phase1InputReportId);
  return <><section className="analysis-panel" aria-label="Exact Phase 1 reliance basis"><h3>Exact Phase 1 basis for this method</h3>{basis ? <><p><strong>{basis.id}</strong></p><p>{dateLabel(basis.createdAt)} · {status(basis.status)}</p><p>The Phase 1 handoff gate selected this immutable report. Its limitations remain part of Phase 2 reliance; a newer draft does not replace it automatically.</p><button className="button secondary" onClick={() => onNavigate('reports', { assessment: assessment.id, report: basis.id })}>Read selected Phase 1 basis →</button></> : <p>No qualified or accepted Phase 1 handoff has selected an input report yet. Method drafting can continue, but the Phase 2 basis gate cannot pass until that handoff is recorded.</p>}</section><form className="analysis-panel assessment-form" onSubmit={event => { event.preventDefault(); void command('set_method', undefined, fields); }}><h3>Establish the analysis basis</h3><p>Phase 2 uses a selected Phase 1 report and a versioned method. Evidence uncertainty, business impact, exposure and change readiness must remain distinguishable.</p><fieldset disabled={!enabled}><Field label="Method name" value={fields.name} onChange={value => setFields(current => ({ ...current, name: value }))} required /><Field label="Method and business-impact approach" value={fields.description} onChange={value => setFields(current => ({ ...current, description: value }))} multiline required /><Field label="Confidence and uncertainty rules" value={fields.confidenceRules} onChange={value => setFields(current => ({ ...current, confidenceRules: value }))} multiline required /><Field label="Prioritization rules" value={fields.prioritizationRules} onChange={value => setFields(current => ({ ...current, prioritizationRules: value }))} multiline required /><button className="button primary">Save analysis method for review</button></fieldset><Help>The risk-lead persona supplies this demonstration method. Saving it does not establish enterprise approval.</Help></form></>;
}

function AnalysisStage({ assessment, command, allowed, onNavigate }: { assessment: AssessmentDetail; command: Command; allowed: (operation: string) => boolean; onNavigate: Navigate }) {
  const [selected, setSelected] = useState(assessment.packages[0]?.familyId || '');
  const item = assessment.packages.find(value => value.familyId === selected);
  return <div className="assessment-task-layout"><section className="analysis-panel assessment-task-list"><h3>Consequences and recommendations</h3><Help>Convert supported facts into conditional risk scenarios and accountable recommendations. Do not rate missing evidence as low risk.</Help>{assessment.packages.map(value => <button key={value.id} className={selected === value.familyId ? 'selected' : ''} onClick={() => setSelected(value.familyId)}><strong>{value.label}</strong><Status value={value.analysis?.state || 'ready'} /></button>)}{!assessment.packages.length && <p>Source evidence packages will appear here when established.</p>}</section>{item && <AnalysisForm key={item.id} item={item} assessmentId={assessment.id} command={command} allowed={allowed} onNavigate={onNavigate} />}</div>;
}

function AnalysisForm({ item, assessmentId, command, allowed, onNavigate }: { item: AssessmentPackage; assessmentId: string; command: Command; allowed: (operation: string) => boolean; onNavigate: Navigate }) {
  const [fields, setFields] = useState({ scenario: item.analysis?.scenario || '', businessImpact: item.analysis?.businessImpact || '', recommendation: item.analysis?.recommendation || '', priority: item.analysis?.priority || 'planned_review', rationale: item.analysis?.rationale || '', confidence: item.analysis?.confidence || 'unknown', protectedInformation: item.analysis?.protectedInformation || '', lifetime: item.analysis?.lifetime || '', assertedBy: item.analysis?.assertedBy || '', statementDate: item.analysis?.statementDate || '', compatibilityConstraints: item.analysis?.compatibilityConstraints || '', vendorConstraints: item.analysis?.vendorConstraints || '', operationalConstraints: item.analysis?.operationalConstraints || '', responsibleFunction: item.analysis?.responsibleFunction || '', nextDecision: item.analysis?.nextDecision || '' });
  const set = (key: keyof typeof fields, value: string) => setFields(current => ({ ...current, [key]: value }));
  return <section className="analysis-panel assessment-task-detail">
    <p className="eyebrow">EVIDENCE → CONSEQUENCE → RECOMMENDATION</p><h3>{item.label}</h3><p><strong>Phase 1 conclusion:</strong> {item.conclusion || 'Not established yet.'}</p>{item.qualification && <p className="notice muted-notice">Carried-forward limitation: {item.qualification}</p>}
    <button className="text-button" onClick={() => onNavigate('actions', { assessment: assessmentId, family: item.familyId })}>Inspect supporting findings →</button>
    <form onSubmit={event => { event.preventDefault(); void command('submit_analysis', item.familyId, fields); }}><fieldset disabled={!allowed('submit_analysis')}>
      <h4>Supported scenario</h4><Field label="Conditional risk scenario" value={fields.scenario} onChange={value => set('scenario', value)} multiline required /><Field label="Business consequence and what needs confirmation" value={fields.businessImpact} onChange={value => set('businessImpact', value)} multiline required />
      <h4>Attributed business context</h4><Help>These statements are supplied business context, not facts established by a certificate or network observation. Use fictional functions for this synthetic demonstration. Unknown information remains a limitation.</Help>
      <Field label="Protected information and affected business service" value={fields.protectedInformation} onChange={value => set('protectedInformation', value)} multiline />
      <Field label="Confidentiality or trust lifetime and basis" value={fields.lifetime} onChange={value => set('lifetime', value)} multiline />
      <div className="assessment-form-grid"><Field label="Business context asserted by" value={fields.assertedBy} onChange={value => set('assertedBy', value)} hint="Name the fictional person or responsible function supplying the statement; this does not make them an authenticated approver." /><Field label="Business statement date" value={fields.statementDate} onChange={value => set('statementDate', value)} type="date" /></div>
      <h4>Constraints on the recommendation</h4><Field label="Compatibility and relying-party constraints" value={fields.compatibilityConstraints} onChange={value => set('compatibilityConstraints', value)} multiline /><Field label="Vendor dependencies and commitments" value={fields.vendorConstraints} onChange={value => set('vendorConstraints', value)} multiline /><Field label="Operational and change constraints" value={fields.operationalConstraints} onChange={value => set('operationalConstraints', value)} multiline />
      <h4>Recommended action and decision</h4><Field label="Recommended treatment or next investigation" value={fields.recommendation} onChange={value => set('recommendation', value)} multiline required /><Field label="Responsible function for the recommendation" value={fields.responsibleFunction} onChange={value => set('responsibleFunction', value)} /><Field label="Next decision and who must make it" value={fields.nextDecision} onChange={value => set('nextDecision', value)} multiline />
      <div className="assessment-form-grid"><label className="assessment-field"><span>Proposed review priority</span><select value={fields.priority} onChange={event => set('priority', event.target.value)}><option value="prioritize_review">Prioritize review</option><option value="planned_review">Planned review</option><option value="defer">Defer with rationale</option></select></label><label className="assessment-field"><span>Evidence confidence</span><select value={fields.confidence} onChange={event => set('confidence', event.target.value)}><option value="unknown">Unknown</option><option value="limited">Limited</option><option value="supported">Supported</option></select></label></div><Field label="Rationale tied to the agreed method" value={fields.rationale} onChange={value => set('rationale', value)} multiline required />
      <button className="button primary">Submit analysis for business review</button>
    </fieldset></form><ReviewForm enabled={allowed('review_analysis') && item.analysis?.state === 'submitted'} title="Business reviewer disposition" onSubmit={review => command('review_analysis', item.familyId, review)} />
  </section>;
}

function ReportStage({ assessment, phase, command, enabled, onNavigate }: { assessment: AssessmentDetail; phase: 'phase1' | 'phase2'; command: Command; enabled: boolean; onNavigate: Navigate }) {
  const [phase1Id, setPhase1Id] = useState('');
  const phase1 = assessment.documents.filter(document => document.phase === 'phase1');
  return <section className="analysis-panel assessment-report-stage">
    <p className="eyebrow">{phase === 'phase1' ? 'CURRENT-STATE ASSESSMENT & INPUT PACKAGE' : 'RISK REGISTER & DECISION-READY RECOMMENDATIONS'}</p><h3>{phase === 'phase1' ? 'Assemble the Phase 1 handoff' : 'Assemble the Phase 2 deliverable'}</h3>
    <p>{phase === 'phase1' ? 'Explain what exists, what supports it, where investigation stopped, and what the next phase can rely on.' : 'Explain supported exposure, conditional business consequences, priorities, decisions and unresolved limitations.'}</p>
    {phase === 'phase2' && <label className="assessment-field"><span>Select the exact Phase 1 input report</span><select value={phase1Id} onChange={event => setPhase1Id(event.target.value)}><option value="">Choose the reviewed Phase 1 basis</option>{phase1.map(document => <option key={document.id} value={document.id} disabled={document.id !== assessment.phase1InputReportId}>{dateLabel(document.createdAt)} · {document.id}{document.id === assessment.phase1InputReportId ? ' · selected handoff basis' : ' · not the selected handoff'}</option>)}</select><small>Only the exact Phase 1 handoff basis is eligible. Never automatically substitute the latest report. The server repeats this check.</small></label>}
    <button className="button primary" disabled={!enabled || phase === 'phase2' && (!phase1Id || phase1Id !== assessment.phase1InputReportId)} onClick={() => void command('generate_report', undefined, { phase, ...(phase === 'phase2' ? { phase1ReportId: phase1Id } : {}) })}>Generate {phase === 'phase1' ? 'Phase 1' : 'Phase 2'} draft</button>
    <Help>Draft generation is not acceptance. Unmet prerequisites remain visible; the exact report must go through its gate below.</Help>
    <div className="assessment-document-list">{assessment.documents.filter(document => document.phase === phase).map(document => <article key={document.id}><div><strong>{phase === 'phase1' ? 'Current-state report' : 'Risk and recommendation report'}</strong><p>{dateLabel(document.createdAt)} · {status(document.status)} · {document.id}</p></div><button className="button secondary" onClick={() => onNavigate('reports', { assessment: assessment.id, report: document.id })}>Read report →</button></article>)}</div>
    {!assessment.documents.some(document => document.phase === phase) && <p>No snapshot generated for this phase yet. The report will reflect only admitted evidence and recorded conclusions.</p>}
  </section>;
}
