import { useCallback, useEffect, useId, useRef, useState } from 'react';
import { api, ApiError, dateLabel, humanize, selectedAssessmentId } from './api';
import { useApi } from './use-api';
import type { Session } from './contracts';
import type { AssessmentSummary } from './assessment-contracts';
import type { DiscoveryList } from './discovery-contracts';
import type { ImpactPreview, OperationalReceipt, ReceivedProduct, WorkCase, WorkConsequence, WorkQueue, WorkState, WorkStep } from './assessment-work-contracts';
import './assessment-work.css';

type Navigate = (page: string, params?: Record<string, string>) => void;
type Send = (operation: string, targetId: string, fields: Record<string, unknown>, legacy?: boolean) => Promise<boolean>;
type Dirty = (value: boolean) => void;
type Operation = { path: string; body: BodyInit; headers: Record<string, string>; changed: boolean; receipt: string; onResult?: (result: unknown) => void };
const steps: { id: WorkStep; label: string }[] = [
  { id: 'returned', label: 'Returned information' }, { id: 'systems', label: 'Systems and sources' },
  { id: 'technical', label: 'Technical records' }, { id: 'consequence', label: 'Assessment consequence' }, { id: 'history', label: 'History' },
];
const lanes: { id: WorkState; label: string }[] = [{ id: 'needs_action', label: 'Needs my action' }, { id: 'in_progress', label: 'In progress' }, { id: 'waiting', label: 'Waiting' }, { id: 'recorded', label: 'Recorded' }];
const query = () => new URLSearchParams(window.location.hash.split('?')[1]);
const named = (value?: string) => value ? humanize(value.replace('synthetic-demo:', '')) : 'Not established';
const text = (value: unknown) => typeof value === 'string' && value.trim() ? value : 'Not supplied';
const sourceLines = (value: string) => value.split('\n').map(line => line.trim()).filter(Boolean);
type ReportedProduct = ReceivedProduct & { returnNumber: number; reportedRow: number; receiptFilename: string; receiptReceivedAt: string };
const appliedProductRows = (receipts: OperationalReceipt[]): ReportedProduct[] => receipts.flatMap((receipt, receiptIndex) => receipt.status === 'applied' ? receipt.products.map((product, rowIndex) => ({ ...product, returnNumber: receiptIndex + 1, reportedRow: rowIndex + 1, receiptFilename: receipt.filename, receiptReceivedAt: receipt.receivedAt })) : []);
const recordLabel = (value: ReportedProduct) => `Return ${value.returnNumber} · reported row ${value.reportedRow} · ${value.product || 'Product not named'} — ${value.deployment || 'Deployment not named'} · ${value.environment || 'Environment unknown'}${value.provenance ? ` · ${value.provenance}` : ''}${value.reference ? ` · ${value.reference}` : ''}`;
const fieldLabel = (key: string) => humanize(key.replace(/([a-z0-9])([A-Z])/g, '$1 $2'));

function Field({ label, value, change, multiline = false, disabled = false, help, maxLength = 2048, required = false }: { label: string; value: string; change: (value: string) => void; multiline?: boolean; disabled?: boolean; help?: string; maxLength?: number; required?: boolean }) {
  const id = useId();
  return <div className="aw-field"><div className="aw-label-row"><label htmlFor={id}>{label}</label>{required && <span className="aw-required">Required</span>}</div>{multiline ? <textarea id={id} value={value} onChange={event => change(event.target.value)} disabled={disabled} maxLength={maxLength} aria-required={required || undefined} aria-describedby={help ? `${id}-help` : undefined} /> : <input id={id} value={value} onChange={event => change(event.target.value)} disabled={disabled} maxLength={maxLength} aria-required={required || undefined} aria-describedby={help ? `${id}-help` : undefined} />}{help && <small className="aw-help" id={`${id}-help`}>{help}</small>}</div>;
}
function RequiredNotice({ items }: { items: string[] }) { return items.length ? <p className="aw-required-notice" role="status">Still required: {items.join('; ')}.</p> : null; }
function Facts({ values }: { values: [string, unknown][] }) { return <dl className="aw-facts">{values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{text(value)}</dd></div>)}</dl>; }
function ReadableSourceValue({ value }: { value: unknown }) {
  if (value == null || value === '') return <span>Not established</span>;
  if (typeof value !== 'object') return <span>{String(value)}</span>;
  if (Array.isArray(value)) return value.length ? <ul className="aw-source-list">{value.map((item, index) => <li key={index}><ReadableSourceValue value={item} /></li>)}</ul> : <span>No values supplied</span>;
  const entries = Object.entries(value);
  return entries.length ? <dl className="aw-source-facts">{entries.map(([key, item]) => <div key={key}><dt>{fieldLabel(key)}</dt><dd><ReadableSourceValue value={item} /></dd></div>)}</dl> : <span>No fields supplied</span>;
}
function ObservationRead({ value }: { value: Record<string, unknown> }) {
  const labels: Record<string, string> = { keyExchange: 'Key establishment', authentication: 'Certificate authentication/signature', basis: 'Evidence basis', collectedAt: 'Collected at', observedAt: 'Observed at', application: 'Application as recorded', service: 'Business service as recorded', applicationService: 'Application/service as recorded', owner: 'Responsible function as recorded', notAfter: 'Certificate expiry', signatureAlgorithm: 'Certificate signature algorithm', facts: 'Source facts, cryptographic uses and relationships', supports: 'What this record can support', cannotEstablish: 'What this record cannot establish' };
  const provenance = new Set(['id', 'systemId', 'sourceSystemId', 'requestId', 'bundleId', 'productId', 'canonicalId', 'artifactSha256', 'sourceRawSha256', 'normalizerVersion', 'nativeSubjectRef']);
  const renderFields = (identity: boolean) => <dl className="aw-facts">{Object.entries(value).filter(([key]) => provenance.has(key) === identity).map(([key, item]) => <div className={item !== null && typeof item === 'object' ? 'aw-wide-fact' : undefined} key={key}><dt>{labels[key] || fieldLabel(key)}</dt><dd><ReadableSourceValue value={item} /></dd></div>)}</dl>;
  return <section className="aw-panel"><h4>{text(value.hostname || value.label || value.nativeId || 'Source observation')}</h4>{renderFields(false)}<p className="aw-help">Recorded configuration, observed behavior and independent verification are different bases. Hybrid key establishment does not establish post-quantum certificate authentication.</p><details className="aw-references"><summary>Record and source identities</summary>{renderFields(true)}</details></section>;
}
function useDirty(value: boolean, report: Dirty) { useEffect(() => { report(value); return () => report(false); }, [value, report]); }

export function AssessmentWork({ session, onNavigate, onDirtyChange }: { session: Session; onNavigate: Navigate; onDirtyChange?: Dirty }) {
  const [assessment, setAssessment] = useState(selectedAssessmentId);
  const [route, setRoute] = useState(query);
  const [dirty, setDirty] = useState(false);
  const assessments = useApi<AssessmentSummary[]>('/api/assessments');
  const reportDirty = useCallback((value: boolean) => { setDirty(value); onDirtyChange?.(value); }, [onDirtyChange]);
  useEffect(() => { const update = () => { setAssessment(selectedAssessmentId()); setRoute(query()); }; window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  useEffect(() => { if (!dirty) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  return <div className="assessment-work"><header className="aw-heading"><p className="eyebrow">RESPONSE → REVIEW → REPORT</p><h1>Assessment work</h1><p>Review what people supplied, establish what the records support, and explain the consequence for the assessment. Each handoff names the next responsible function.</p></header>
    <p className="aw-boundary">Synthetic development candidate. No enterprise acceptance, source access, email delivery or migration is enabled.</p>
    <section className="aw-context"><label className="aw-field"><span>Assessment for this work</span><select value={assessment} disabled={dirty || assessments.loading} onChange={event => onNavigate('assessment-work', { assessment: event.target.value })}><option value="">Choose an assessment</option>{assessments.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button secondary" disabled={dirty} onClick={() => onNavigate('assessments', { assessment })}>{assessment ? 'Scope and review gates' : 'Set up an assessment'}</button></section>
    {assessments.error && <p role="alert">{assessments.error} <button className="text-button" onClick={assessments.reload}>Reload assessments</button></p>}
    {!assessment ? <section className="aw-empty"><h2>Choose the assessment you are helping complete</h2><p>This selects the work, not a dashboard filter. A coordinator can establish a fresh assessment; respondents use their exact five-question links.</p></section> : <WorkSession key={assessment} assessment={assessment} route={route} session={session} onNavigate={onNavigate} onDirtyChange={reportDirty} />}
  </div>;
}

function WorkSession({ assessment, route, session, onNavigate, onDirtyChange }: { assessment: string; route: URLSearchParams; session: Session; onNavigate: Navigate; onDirtyChange: Dirty }) {
  const [refresh, setRefresh] = useState(0); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [conflict, setConflict] = useState(false);
  const [duplicateRequest, setDuplicateRequest] = useState('');
  const [pendingState, setPendingState] = useState(false); const pending = useRef<Operation | null>(null); const acting = useRef(false);
  const requestId = route.get('request') || ''; const lane = lanes.some(item => item.id === route.get('lane')) ? route.get('lane') as WorkState : 'needs_action';
  const step = steps.some(item => item.id === route.get('step')) ? route.get('step') as WorkStep : 'returned';
  const base = `/api/assessments/${encodeURIComponent(assessment)}`;
  const queue = useApi<WorkQueue>(`${base}/work`, refresh);
  const detail = useApi<WorkCase | WorkQueue>(requestId ? `${base}/work/${encodeURIComponent(requestId)}` : `${base}/work`, refresh);
  const discovery = useApi<DiscoveryList>(`${base}/discovery`, refresh);
  const current = detail.data && 'request' in detail.data ? detail.data : undefined;
  const locked = busy || pendingState || conflict;
  const reportDirty = useCallback((value: boolean) => setDirty(value), []);
  useEffect(() => { onDirtyChange(dirty || busy || pendingState); return () => onDirtyChange(false); }, [dirty, busy, pendingState, onDirtyChange]);
  const open = (params: Record<string, string>) => { if (!dirty && !locked) onNavigate('assessment-work', { assessment, lane, ...params }); };
  async function execute(action: Operation, retry = false): Promise<boolean> {
    if (acting.current || conflict || pending.current && !retry) return false;
    acting.current = true; pending.current = action; setPendingState(true); setBusy(true); setError('');
    try {
      const result = await api<unknown>(action.path, { method: 'POST', headers: action.headers, body: action.body });
      pending.current = null; setPendingState(false); setNotice(action.receipt); action.onResult?.(result);
      if (action.changed) { setDirty(false); setRefresh(value => value + 1); }
      return true;
    } catch (reason) {
      if (reason instanceof ApiError && reason.status < 500) { pending.current = null; setPendingState(false); }
      if (reason instanceof ApiError && reason.status === 409) { setConflict(true); setError('The saved work changed. Your entered information remains visible. Preserve anything needed, then explicitly reload the saved case before trying again.'); }
      else setError(reason instanceof ApiError ? reason.message : 'Delivery was interrupted. Retry the identical operation to reconcile its outcome; no second submission is needed.');
      return false;
    } finally { acting.current = false; setBusy(false); }
  }
  const headers = (type = 'application/json') => ({ 'X-PQC-CSRF': session.csrfToken || '', 'Idempotency-Key': crypto.randomUUID(), 'Content-Type': type });
  const send: Send = async (operation, targetId, fields, legacy = false) => !!current && execute({ path: `${base}/${legacy ? 'discovery' : 'work'}/commands`, headers: headers(), body: JSON.stringify({ operation, targetId, fields, expectedRevision: current.revision }), changed: true, receipt: `Recorded: ${humanize(operation)}. The next step below reflects saved state; this is not report acceptance.` });
  async function upload(file: File) {
    if (!current) return false;
    setDuplicateRequest('');
    return execute({ path: `${base}/receipts?${new URLSearchParams({ requestId: current.request.id, expectedRevision: String(current.revision), filename: file.name })}`, headers: headers('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'), body: file, changed: true, receipt: 'Workbook received for review. Its information has not been applied to the response, admitted as technical evidence or submitted as approval.', onResult: value => { const result = value as { duplicate?: boolean; existingRequestId?: string }; if (result.duplicate === true) { setNotice('This exact file was already received in this assessment. No duplicate response or source artifact was created. Your selected request has not been silently changed.'); if (typeof result.existingRequestId === 'string') setDuplicateRequest(result.existingRequestId); } } });
  }
  async function stage(investigationId: string, productRefId: string, sourceLabel: string, file: File) {
    if (!current) return false;
    const path = investigationId === 'workspace'
      ? `${base}/work/${encodeURIComponent(current.request.id)}/evidence?${new URLSearchParams({ productId: productRefId, expectedRevision: String(current.revision) })}`
      : `${base}/discovery/investigations/${encodeURIComponent(investigationId)}/evidence?${new URLSearchParams({ productRefId, sourceLabel, expectedRevision: String(current.revision) })}`;
    return execute({ path, headers: headers(), body: file, changed: true, receipt: 'Synthetic records staged. A different technical reviewer must review the contents before lead admission.' });
  }
  async function preview(fields: WorkConsequence, callback: (value: ImpactPreview) => void) {
    if (!current) return false;
    return execute({ path: `${base}/report-impact/preview`, headers: headers(), body: JSON.stringify({ operation: 'record_consequence', targetId: current.request.id, fields, expectedRevision: current.revision }), changed: false, receipt: 'Preview only. No conclusion or report was changed.', onResult: value => callback(value as ImpactPreview) });
  }
  const item = current?.task || queue.data?.items.find(row => row.requestId === requestId);
  return <>
    {notice && <section className="aw-preview" role="status"><strong>{notice}</strong>{duplicateRequest && <p><button className="button secondary" disabled={dirty || locked} onClick={() => open({ request: duplicateRequest, step: 'returned' })}>Open the original receipt request</button></p>}<button className="text-button" onClick={() => { setNotice(''); setDuplicateRequest(''); }}>Dismiss receipt</button></section>}
    {error && <section className="notice error" role="alert"><p>{error}</p>{pending.current && <button className="button secondary" disabled={busy} onClick={() => pending.current && void execute(pending.current, true)}>Retry identical operation</button>}{conflict && <button className="button secondary" onClick={() => { setConflict(false); setDirty(false); setError(''); setRefresh(value => value + 1); }}>Discard local edits and reload saved case</button>}</section>}
    {(queue.error || detail.error) && <section className="notice error" role="alert"><p>{queue.error || detail.error}</p><p>No case or queue result has been assumed from this failure.</p><button className="button secondary" disabled={dirty || locked} onClick={() => setRefresh(value => value + 1)}>Reload work</button></section>}
    {queue.loading || requestId && detail.loading ? <p role="status">Loading saved assessment work…</p> : null}
    {!requestId && queue.data && <><nav className="aw-filters" aria-label="Work states">{lanes.map(value => <button key={value.id} aria-pressed={lane === value.id} onClick={() => open({ lane: value.id })}>{value.label} <span>({queue.data!.items.filter(row => row.state === value.id).length})</span></button>)}</nav>
      <ul className="aw-work-list">{queue.data.items.filter(row => row.state === lane).map(row => <li key={row.requestId}><span className="aw-status">{row.familyName}</span><h3>{row.title}</h3><p><strong>Task:</strong> {row.task}</p><p>{row.why}</p><p className="aw-help"><strong>Next responsible function:</strong> {row.nextFunction}</p><button className="button primary" onClick={() => open({ request: row.requestId, step: row.step || (row.state === 'recorded' ? 'history' : 'returned') })}>{row.canAct ? 'Open this task' : 'Read work and blocking reason'}</button></li>)}</ul>
      {!queue.data.items.some(row => row.state === lane) && <section className="aw-empty"><h2>No work in {lanes.find(value => value.id === lane)?.label.toLowerCase()}</h2><p>This does not mean the assessment is complete. Check another work state or its scope and review gates.</p></section>}
      <div className="aw-actions"><button className="button secondary" onClick={() => onNavigate('discovery', { assessment })}>Request catalog and individual Excel forms</button><button className="button secondary" onClick={() => onNavigate('reports', { assessment })}>Reports and accepted history</button></div></>}
    {current && <><button className="text-button" disabled={dirty || locked} onClick={() => open({ request: '', step: '' })}>← All assessment work</button>{queue.data && queue.data.items.length > 1 && <label className="aw-field"><span>Continue another source case</span><select value={current.request.id} disabled={dirty || locked} onChange={event => { const next = queue.data?.items.find(value => value.requestId === event.target.value); if (next) open({ request: next.requestId, step: next.step || 'returned' }); }}>{queue.data.items.map(value => <option key={value.requestId} value={value.requestId}>{value.familyName} — {value.title} · {named(value.state)}</option>)}</select></label>}<section className="aw-panel aw-task"><p className="eyebrow">{current.request.familyName} / {current.request.title}</p><h2>{item?.task || 'Review this assessment case'}</h2><dl className="aw-context-grid"><div><dt>Why it matters</dt><dd>{item?.why || 'Separate supplied information, technical knowledge and the decisions needed for a defensible report.'}</dd></div><div><dt>What your action changes</dt><dd>{item?.effect || 'Only the explicitly confirmed action changes saved work. Reading does not submit or accept anything.'}</dd></div><div><dt>Who acts next</dt><dd>{item?.nextFunction || 'Review the named role for the selected action.'}</dd></div></dl></section>
      <nav className="aw-steps" aria-label="Case sections">{steps.map(value => <button key={value.id} disabled={dirty || locked} aria-current={step === value.id ? 'step' : undefined} onClick={() => open({ request: current.request.id, step: value.id })}>{value.label}</button>)}</nav>
      {dirty && <p className="aw-boundary">Unsaved work is protected. Save or discard the visible edits before changing sections.</p>}
      <CaseBody key={`${current.request.id}-${current.revision}-${step}`} current={current} step={step} selectedInvestigation={route.get('investigation') || ''} selectedBatch={route.get('batch') || ''} discovery={discovery.data} locked={locked || !session.csrfToken} onDirty={reportDirty} send={send} upload={upload} stage={stage} preview={preview} onNavigate={onNavigate} />
    </>}
  </>;
}

function CaseBody({ current, step, selectedInvestigation, selectedBatch, discovery, locked, onDirty, send, upload, stage, preview, onNavigate }: { current: WorkCase; step: WorkStep; selectedInvestigation: string; selectedBatch: string; discovery?: DiscoveryList; locked: boolean; onDirty: Dirty; send: Send; upload: (file: File) => Promise<boolean>; stage: (id: string, product: string, source: string, file: File) => Promise<boolean>; preview: (fields: WorkConsequence, callback: (value: ImpactPreview) => void) => Promise<boolean>; onNavigate: Navigate }) {
  if (step === 'returned') return <Returned current={current} locked={locked} onDirty={onDirty} send={send} upload={upload} />;
  if (step === 'systems') return <Systems current={current} locked={locked} onDirty={onDirty} send={send} />;
  if (step === 'technical') return <Technical current={current} discovery={discovery} initialInvestigation={selectedInvestigation} initialBatch={selectedBatch} locked={locked} onDirty={onDirty} send={send} stage={stage} onNavigate={onNavigate} />;
  if (step === 'consequence') return <Consequence current={current} locked={locked} onDirty={onDirty} send={send} preview={preview} onNavigate={onNavigate} />;
  return <section className="aw-panel"><h2>Recorded handoffs and reports</h2><p>Earlier submissions and decisions remain historical. A new conclusion does not rewrite an accepted report.</p><ul className="aw-history">{current.history.map((event, index) => <li key={`${event.revision}-${index}`}><strong>{humanize(event.operation)} · revision {event.revision}</strong><p>{named(event.principalId)} · {event.createdAt ? dateLabel(event.createdAt) : 'Date not established'}</p><small>{event.origin?.includes('scenario') || event.origin === 'simulated' ? 'Scenario-generated synthetic history' : 'Recorded development action — not enterprise acceptance'}</small></li>)}</ul>{!current.history.length && <p>No recorded case history yet.</p>}<h3>Immutable report snapshots</h3>{current.documents.map(document => <article className="aw-record" key={document.id}><h4>{document.phase === 'phase1' ? 'Phase 1 current state' : 'Phase 2 risk and recommendations'}</h4><p>{named(document.status)} · {dateLabel(document.createdAt)}</p><button className="button secondary" onClick={() => onNavigate('reports', { assessment: current.assessmentId, report: document.id })}>Read this exact report</button></article>)}{!current.documents.length && <p>No report snapshot has been created. Recorded response work does not imply a completed deliverable.</p>}</section>;
}

function Returned({ current, locked, onDirty, send, upload }: { current: WorkCase; locked: boolean; onDirty: Dirty; send: Send; upload: (file: File) => Promise<boolean> }) {
  const [file, setFile] = useState<File>(); const [confirmed, setConfirmed] = useState(false); const [fileError, setFileError] = useState('');
  const [selected, setSelected] = useState(current.receipts.at(-1)?.id || ''); const [choices, setChoices] = useState<Record<string, 'current' | 'returned'>>({}); const [note, setNote] = useState('');
  const dirty = !!file || confirmed || !!note || Object.keys(choices).length > 0; useDirty(dirty, onDirty);
  const receipt = current.receipts.find(value => value.id === selected);
  const priorReceipt = receipt ? current.receipts.filter(value => value.id !== receipt.id && value.status === 'applied' && value.receivedAt < receipt.receivedAt).sort((a, b) => a.receivedAt.localeCompare(b.receivedAt)).at(-1) : undefined;
  const canReceive = current.allowedActions.includes('receive_operational_return') || current.allowedActions.includes('receipt_receive');
  const canApply = current.allowedActions.includes('receipt_apply');
  const missingReceipt = receipt ? [...receipt.comparison.filter(value => !choices[value.questionId]).map(value => `answer choice for ${value.questionId}`), ...(!note.trim() ? ['receipt review note'] : [])] : [];
  const discard = () => { setFile(undefined); setConfirmed(false); setChoices({}); setNote(''); setFileError(''); };
  return <section className="aw-panel"><h2>What was supplied</h2><p>A received questionnaire is attributed information. It does not prove technical behavior, authorize access or complete the assessment.</p>
    <details className="aw-references"><summary>Read saved web response and attribution</summary>{current.request.questions.map(question => { const answer = current.request.answers[question.id]; return <article className="aw-record" key={question.id}><h3>{question.id} · {question.prompt}</h3><p>{named(answer?.status)} — {text(answer?.text)}</p><Facts values={[["Existing reference", answer?.reference], ['Asserted by', answer?.assertedBy], ['Recorded by', answer?.recordedBy]]} /></article>; })}</details>
    <section className="aw-record"><h3>Receive a completed operational Excel form</h3><p>Select the individual five-question <strong>email-return edition</strong>. This is separate from the original server-bound web/Excel exchange. No ZIPs, macros or sensitive source exports.</p><Facts values={[["Bind to assessment", current.assessmentName], ['Bind to request', current.request.title], ['Software class', current.request.familyName]]} />
      {!canReceive && <p className="aw-boundary">The assessment coordinator receives operational returns. Your role can read the saved handoff.</p>}
      <label className="aw-field"><span>Completed operational questionnaire (.xlsx, maximum 1 MiB)</span><input key={file ? 'selected' : 'empty'} type="file" accept=".xlsx" disabled={locked || !canReceive || !!note || Object.keys(choices).length > 0} onChange={event => { const value = event.target.files?.[0]; setConfirmed(false); if (value && (!value.name.toLowerCase().endsWith('.xlsx') || value.size > 1048576)) { setFileError('Choose one .xlsx workbook no larger than 1 MiB. ZIP and macro-enabled workbooks are not accepted.'); setFile(undefined); } else { setFileError(''); setFile(value); } }} /></label>
      {file && <p>{file.name}</p>}{fileError && <p role="alert" className="notice error">{fileError}</p>}
      <label className="aw-check"><input type="checkbox" checked={confirmed} disabled={locked || !canReceive || !file} onChange={event => setConfirmed(event.target.checked)} /><span>I confirm this return belongs to <strong>{current.request.title}</strong> in <strong>{current.assessmentName}</strong>. The server will also verify its internal software-class and question definitions.</span></label>
      <button className="button primary" disabled={locked || !canReceive || !file || !confirmed} onClick={() => file && void upload(file)}>Receive and preview information</button>
    </section>
    <section className="aw-record"><h3>Review received versions</h3>{!current.receipts.length && <p>No operational return has been received for this request. A web response remains a valid starting point.</p>}{current.receipts.length > 0 && <label className="aw-field"><span>Received workbook version</span><select value={selected} disabled={locked || dirty} onChange={event => setSelected(event.target.value)}>{current.receipts.map(value => <option key={value.id} value={value.id}>{value.filename} · {named(value.status)} · {dateLabel(value.receivedAt)}</option>)}</select></label>}
      {receipt && <><ReceiptRead receipt={receipt} />{priorReceipt ? <p className="aw-help">Prior recorded operational return: {priorReceipt.filename} · {dateLabel(priorReceipt.receivedAt)}. It is a historical reported version, not a server export baseline.</p> : <p className="aw-help">No earlier recorded operational return is available for this comparison. Current web answers may still exist.</p>}<h3>Choose what to record as the offline response</h3><p>No server export baseline existed for this operational edition. These are reported changes versus current saved information—not authenticated approvals or automatic three-way synchronization. Blank returned cells retain existing knowledge. Recording this response marks the coordinator handoff, not an authenticated respondent signature, technical review or source readiness.</p>{receipt.comparison.map(value => <article className="aw-record" key={value.questionId}><h4>{value.questionId} · {named(value.state)}</h4><div className={priorReceipt ? 'aw-columns aw-three-columns' : 'aw-columns'}>{priorReceipt && <div><h4>Prior recorded return</h4><p>{named(priorReceipt.answers.find(answer => answer.questionId === value.questionId)?.status)}: {text(priorReceipt.answers.find(answer => answer.questionId === value.questionId)?.text)}</p><p className="aw-help">Reference: {text(priorReceipt.answers.find(answer => answer.questionId === value.questionId)?.reference)}</p></div>}<div><h4>Current saved answer</h4><p>{named(String(value.current.status || 'unanswered'))}: {text(value.current.text)}</p><p className="aw-help">Reference: {text(value.current.reference)}</p></div><div><h4>Returned answer</h4><p>{named(String(value.returned.status || 'unanswered'))}: {text(value.returned.text)}</p><p className="aw-help">Reference: {text(value.returned.reference)}</p></div></div><label className="aw-field"><span>Retain which answer for {value.questionId}?</span><select aria-required="true" value={choices[value.questionId] || ''} disabled={locked || !canApply || receipt.status === 'applied' || !!file} onChange={event => setChoices(previous => ({ ...previous, [value.questionId]: event.target.value as 'current' | 'returned' }))}><option value="">Choose explicitly</option><option value="current">Keep current saved answer</option><option value="returned">Use returned answer</option></select></label></article>)}<Field required label="Receipt review note" value={note} change={setNote} multiline disabled={locked || !canApply || receipt.status === 'applied' || !!file} help="Preserve the reason for accepting a reported correction or retaining a conflict. This is not technical qualification." />
        {canApply && receipt.status !== 'applied' && <RequiredNotice items={missingReceipt} />}
        {receipt.status === 'applied' ? <p className="aw-boundary">This receipt has already been applied. Its history remains intact; receive a new version for later corrections.</p> : <button className="button primary" disabled={locked || !canApply || !!file || !note.trim() || receipt.comparison.some(value => !choices[value.questionId])} onClick={() => void send('receipt_apply', receipt.id, { choices, note })}>Record reviewed offline response</button>}
      </>}
    </section>{dirty && <div className="aw-actions"><button className="text-button" disabled={locked} onClick={discard}>Discard unsaved receipt choices</button></div>}
  </section>;
}

function ReceiptRead({ receipt }: { receipt: OperationalReceipt }) {
  return <><Facts values={[["Declared respondent (unverified)", receipt.respondent], ['Declared team', receipt.team], ['Response date supplied', receipt.responseDate], ['Reported scope', receipt.scope], ['Authenticated receiver', receipt.receivedBy], ['Received at', receipt.receivedAt]]} /><p className="aw-help">Named owners and workbook attribution are reported assertions, not confirmed authority. The authenticated receiver is recorded separately.</p><details className="aw-references"><summary>All returned answers, referrals and references</summary>{receipt.answers.map(answer => <article className="aw-record" key={answer.questionId}><h4>{answer.questionId} · {answer.prompt}</h4><p>{named(answer.status)} — {text(answer.text)}</p><Facts values={[["Reference", answer.reference], ['Attribution exactly as supplied', answer.attribution], ['Follow-up or referral', answer.followUp]]} /></article>)}</details><section className="aw-record" aria-label="Returned products and deployments"><h3>Products and deployments supplied in this return</h3><p>These rows will be retained as reported information. They are not yet duplicate-checked enterprise identities.</p>{receipt.products.map((product, index) => <article className="aw-record" key={product.id}><h4>{index + 1}. {product.product || 'Product not named'} — {product.deployment || 'Deployment not named'}</h4><Facts values={[["Environment", product.environment], ['Application or service', product.applicationService], ['Team', product.team], ['Dependencies', product.dependencies], ['Reference', product.reference], ['Notes and unknowns', product.notes]]} /></article>)}{!receipt.products.length && <p>No product rows were supplied. A referral or explicit unknown can still be useful.</p>}</section><details className="aw-references"><summary>Original receipt identity</summary><Facts values={[["Filename", receipt.filename], ['Format profile', receipt.profile], ['Content SHA-256', receipt.artifactSha256]]} /></details></>;
}

function Systems({ current, locked, onDirty, send }: { current: WorkCase; locked: boolean; onDirty: Dirty; send: Send }) {
  const products = appliedProductRows(current.receipts);
  const [selected, setSelected] = useState(products[0]?.id || '');
  const product = products.find(value => value.id === selected);
  const [decision, setDecision] = useState<'distinct' | 'same_system' | 'unresolved'>('unresolved'); const [canonicalId, setCanonicalId] = useState('');
  const [label, setLabel] = useState(''); const [applicationService, setApplicationService] = useState(''); const [team, setTeam] = useState(''); const [rationale, setRationale] = useState('');
  const dirty = !!rationale || !!label || !!applicationService || !!team || !!canonicalId || decision !== 'unresolved'; useDirty(dirty, onDirty);
  const canEdit = current.allowedActions.includes('reconcile_product');
  const latestDecisions = [...new Map(current.identityDecisions.map(value => [value.productId, value])).values()];
  const eligibleTargets = latestDecisions.filter(value => value.productId !== selected && value.decision !== 'unresolved' && value.canonicalId);
  const missingIdentity = [...(!label.trim() ? ['reviewed system label'] : []), ...(!rationale.trim() ? ['identity rationale and evidence basis'] : []), ...(decision === 'same_system' && !canonicalId ? ['the existing reviewed system identity'] : [])];
  const currentDecision = [...current.identityDecisions].reverse().find(value => value.productId === selected);
  return <section className="aw-panel"><h2>Which systems does this information describe?</h2><p>A product name is not an enterprise identity. Keep separate deployments separate. An inventory repository supplying information is not automatically the application it describes.</p>
    {!products.length && <p>No products were reported yet. A referral or unknown remains useful; engineering can establish deployments after investigation.</p>}
    {products.length > 0 && <><label className="aw-field"><span>Reported product or deployment</span><select value={selected} disabled={locked || dirty} onChange={event => setSelected(event.target.value)}>{products.map(value => <option key={value.id} value={value.id}>{recordLabel(value)}</option>)}</select></label><p className="aw-help">Each option is a separate reported row, not necessarily a different deployment. Return numbers distinguish received files; row numbers are positions within that return, not worksheet row numbers. Compare the source cell, existing reference and notes before deciding whether two rows describe the same system.</p>{product && <Facts values={[["Received return", `Return ${product.returnNumber} · ${product.receiptFilename}`], ['Return received at', product.receiptReceivedAt], ['Original worksheet/cell reference', product.provenance], ["Product as reported", product.product], ['Deployment as reported', product.deployment], ['Environment', product.environment], ['Application/service as reported', product.applicationService], ['Team as reported', product.team], ['Dependencies as reported', product.dependencies], ['Existing reference', product.reference], ['Unknowns or suspected duplicates', product.notes]]} />}
      {currentDecision && <aside className="aw-preview"><strong>Latest recorded identity determination: {named(currentDecision.decision)}</strong><p>{currentDecision.label} · {currentDecision.rationale}</p><p>Recording a correction adds history; it does not delete the previous assertion or rewrite accepted reports.</p></aside>}
      {!canEdit && <p className="aw-boundary">The assessment coordinator records identity determinations. Reported relationships remain unconfirmed until reviewed.</p>}
      <label className="aw-field"><span>Identity determination</span><select disabled={locked || !canEdit} value={decision} onChange={event => { setDecision(event.target.value as typeof decision); setCanonicalId(''); }}><option value="unresolved">Identity remains unresolved</option><option value="distinct">This is a distinct assessed system</option><option value="same_system" disabled={!eligibleTargets.length}>This refers to the same system as another record</option></select></label>
      {!eligibleTargets.length && <p className="aw-boundary">No other reviewed system is available to match yet. First select the original reported row, record it as a distinct assessed system if supported, then select the suspected duplicate and choose “same system.” If the identity is uncertain, keep it unresolved.</p>}
      {decision === 'same_system' && <><label className="aw-field"><span>Same system as</span><select disabled={locked || !canEdit} value={canonicalId} onChange={event => setCanonicalId(event.target.value)}><option value="">Choose the other reviewed system</option>{eligibleTargets.filter((value, index, values) => values.findIndex(other => other.canonicalId === value.canonicalId) === index).map(value => { const target = products.find(item => item.id === value.productId); return <option key={value.canonicalId} value={value.canonicalId}>{value.label} · reviewed identity{target ? ` · ${recordLabel(target)}` : ''}</option>; })}{products.filter(value => value.id !== selected && !eligibleTargets.some(target => target.productId === value.id)).map(value => <option key={value.id} disabled value={`unreviewed:${value.id}`}>{recordLabel(value)} · {latestDecisions.some(target => target.productId === value.id && target.decision === 'unresolved') ? 'reviewed as unresolved; establish identity first' : 'identity not yet established'}</option>)}</select></label><p className="aw-help">Only established identities can be selected. Rows are excluded only when they are the currently selected assertion—not because their deployment names match. An unavailable original row must be reviewed first; discard these unsaved edits before switching rows. Choosing a different deployment merely to continue would record an incorrect relationship.</p>{canonicalId && <aside className="aw-preview" aria-label="Reviewed match basis"><strong>Existing identity review basis</strong>{eligibleTargets.filter(value => value.canonicalId === canonicalId).map(value => <p key={value.productId}>{products.find(item => item.id === value.productId) ? recordLabel(products.find(item => item.id === value.productId)!) : value.label} — {value.rationale}</p>)}</aside>}</>}
      <Field required label="Reviewed system label" value={label} change={setLabel} disabled={locked || !canEdit} help="Supply a readable provisional label; the determination can remain unresolved." /><Field label="Reviewed application or business service" value={applicationService} change={setApplicationService} disabled={locked || !canEdit} /><Field label="Responsible team or function" value={team} change={setTeam} disabled={locked || !canEdit} /><Field required label="Identity rationale and evidence basis" value={rationale} change={setRationale} multiline disabled={locked || !canEdit} help="Explain the basis and uncertainty. A suspected match is not a confirmed merge." />
      {canEdit && <RequiredNotice items={missingIdentity} />}
      <div className="aw-actions"><button className="button primary" disabled={locked || !canEdit || !rationale.trim() || !label.trim() || decision === 'same_system' && !canonicalId} onClick={() => void send('reconcile_product', current.request.id, { productId: selected, decision, canonicalId, label, applicationService, team, rationale })}>Record identity determination</button>{dirty && <button className="text-button" disabled={locked} onClick={() => { setDecision('unresolved'); setCanonicalId(''); setLabel(''); setApplicationService(''); setTeam(''); setRationale(''); }}>Discard identity edits</button>}</div>
    </>}
    <h3>Current identity determinations</h3>{current.identityDecisions.map(value => <p key={value.id}>{value.label || value.productId} — {named(value.decision)}. {value.rationale}</p>)}{!current.identityDecisions.length && <p>No identity decisions have been recorded. Reported products are not duplicate-checked enterprise assets.</p>}
  </section>;
}

function Technical({ current, discovery, initialInvestigation, initialBatch, locked, onDirty, send, stage, onNavigate }: { current: WorkCase; discovery?: DiscoveryList; initialInvestigation: string; initialBatch: string; locked: boolean; onDirty: Dirty; send: Send; stage: (id: string, product: string, source: string, file: File) => Promise<boolean>; onNavigate: Navigate }) {
  const investigations = current.investigations.map(value => discovery?.investigations.find(row => row.id === value.id) || value);
  const [selected, setSelected] = useState(investigations.some(value => value.id === initialInvestigation) ? initialInvestigation : investigations[0]?.id || '');
  const investigation = investigations.find(value => value.id === selected);
  const [purpose, setPurpose] = useState(''); const [assignedTo, setAssignedTo] = useState('');
  const [research, setResearch] = useState(''); const [method, setMethod] = useState(''); const [documentation, setDocumentation] = useState(''); const [limitation, setLimitation] = useState(''); const [status, setStatus] = useState('researching');
  const [productId, setProductId] = useState(''); const [source, setSource] = useState(''); const [file, setFile] = useState<File>(); const [fileError, setFileError] = useState('');
  const [rationale, setRationale] = useState<Record<string, string>>({}); const [confirmation, setConfirmation] = useState('');
  const [reviewBatch, setReviewBatch] = useState(initialBatch || current.technicalRecords[0]?.bundleId || '');
  const [recordDecisions, setRecordDecisions] = useState<Record<string, { determination: string; rationale: string }>>({});
  const [researchEdited, setResearchEdited] = useState(false);
  const dirty = !!purpose || !!assignedTo || researchEdited || !!productId || !!source || !!file || Object.values(rationale).some(Boolean) || Object.keys(recordDecisions).length > 0 || !!confirmation; useDirty(dirty, onDirty);
  useEffect(() => { if (!investigation) return; setResearch(investigation.researchSummary); setMethod(investigation.proposedMethod); setDocumentation(investigation.documentationRefs.join('\n')); setLimitation(investigation.limitation); setStatus(investigation.status); setResearchEdited(false); }, [investigation?.id]); // The case remounts after a confirmed revision.
  const canCreate = discovery?.canCoordinate === true; const products = investigation?.productRefs || current.request.productRefs;
  const records = current.technicalRecords.filter(value => value.bundleId.startsWith('wbundle-') || !selected || value.investigationId === selected).slice().sort((a, b) => Number(b.bundleId === initialBatch) - Number(a.bundleId === initialBatch));
  const reviewEdited = Object.values(rationale).some(Boolean) || Object.keys(recordDecisions).length > 0 || !!confirmation;
  const otherTechnicalEdits = !!purpose || !!assignedTo || researchEdited || !!productId || !!source || !!file;
  const canStageWorkspace = current.allowedActions.includes('workspace_stage_evidence') && current.canStageEvidence === true && !reviewEdited && !purpose && !assignedTo && !researchEdited;
  const appliedProducts = appliedProductRows(current.receipts);
  return <section className="aw-panel"><h2>Review the technical contents</h2><p>Reported answers, configuration records and observed behavior have different evidential weight. Read the actual values and their basis before making a determination.</p>
    <section className="aw-record"><h3>Stage a bounded source capture</h3><p>Use a prepared synthetic context, certificate or TLS capture, or a registered all-domain source bundle. Registered bundles are checked against the installed synthetic source registry and retain the original-source reference and normalizer identity. Selecting a deployment does not make its evidence source the assessed application.</p>
      {!canStageWorkspace && <aside className="aw-boundary"><p>Staging requires the assessment lead, an applied operational return, a submitted response and valid G00 / P1-G01 boundaries. Other investigation can continue.</p>{current.stageEvidenceBlockingReasons && <ul>{current.stageEvidenceBlockingReasons.map(value => <li key={value}>{value}</li>)}</ul>}</aside>}
      <label className="aw-field"><span>Reviewed return deployment for this capture</span><select value={productId} disabled={locked || !canStageWorkspace} onChange={event => setProductId(event.target.value)}><option value="">Choose an applied receipt product</option>{appliedProducts.map(value => <option key={value.id} value={value.id}>{recordLabel(value)}</option>)}</select></label>
      <label className="aw-field"><span>Controlled synthetic source JSON (maximum 32 KiB)</span><input key={file ? 'workspace-selected' : 'workspace-empty'} type="file" accept=".json" disabled={locked || !canStageWorkspace} onChange={event => { const value = event.target.files?.[0]; if (value && (!value.name.toLowerCase().endsWith('.json') || value.size > 32768)) { setFileError('Choose one controlled JSON fixture no larger than 32 KiB.'); setFile(undefined); } else { setFileError(''); setFile(value); } }} /></label>{fileError && <p role="alert">{fileError}</p>}<button className="button secondary" disabled={locked || !canStageWorkspace || !productId || !file || researchEdited} onClick={() => file && void stage('workspace', productId, '', file)}>Stage source capture for review</button>
    </section>
    {!investigations.length && <p>No bounded investigation has been created yet. Use the returned information to specify the question engineering must answer.</p>}
    {canCreate && <details className="aw-references"><summary>Create a bounded investigation</summary><fieldset className="aw-field-group" disabled={reviewEdited || !!file || !!productId || researchEdited}><Field required label="Question this investigation must answer" value={purpose} change={setPurpose} multiline disabled={locked} /><label className="aw-field"><span>Assigned investigator</span><select value={assignedTo} disabled={locked} onChange={event => setAssignedTo(event.target.value)}><option value="">Choose an assigned assessment investigator</option>{discovery?.investigators?.map(value => <option key={value.id} value={value.id}>{named(value.label)}</option>)}</select></label><button className="button secondary" disabled={locked || !purpose.trim() || !assignedTo || current.request.status !== 'submitted'} onClick={() => void send('discovery_create_investigation', current.request.id, { purpose, assignedTo, productRefIds: current.request.productRefs.map(value => value.id) }, true)}>Create investigation from this response</button>{current.request.status !== 'submitted' && <p className="aw-boundary">A useful submitted web response or coordinator-recorded reviewed offline response is required. Receiving the file alone does not complete that handoff.</p>}</fieldset></details>}
    {investigations.length > 0 && <><label className="aw-field"><span>Bounded investigation</span><select value={selected} disabled={locked || dirty} onChange={event => setSelected(event.target.value)}>{investigations.map(value => <option key={value.id} value={value.id}>{value.purpose} · {named(value.status)}</option>)}</select></label>
      {investigation && <><p><strong>Assigned to:</strong> {named(investigation.assignedTo)}</p><details className="aw-references"><summary>Engineering research and limitations</summary><fieldset className="aw-field-group" disabled={reviewEdited || !!file || !!productId || !!purpose || !!assignedTo}><Field label="Product and interface research" value={research} change={value => { setResearch(value); setResearchEdited(true); }} multiline disabled={locked || !investigation.canEditResearch} /><Field label="Official documentation references" value={documentation} change={value => { setDocumentation(value); setResearchEdited(true); }} multiline disabled={locked || !investigation.canEditResearch} /><Field label="Proposed bounded method" value={method} change={value => { setMethod(value); setResearchEdited(true); }} multiline disabled={locked || !investigation.canEditResearch} /><Field label="Unknowns, constraints and next decisions" value={limitation} change={value => { setLimitation(value); setResearchEdited(true); }} multiline disabled={locked || !investigation.canEditResearch} /><label className="aw-field"><span>Research status</span><select value={status} disabled={locked || !investigation.canEditResearch} onChange={event => { setStatus(event.target.value); setResearchEdited(true); }}>{['planned', 'researching', 'ready_for_review', 'blocked'].map(value => <option key={value} value={value}>{named(value)}</option>)}</select></label><button className="button secondary" disabled={locked || !investigation.canEditResearch || !researchEdited} onClick={() => void send('discovery_update_investigation', investigation.id, { status, researchSummary: research, proposedMethod: method, documentationRefs: sourceLines(documentation), limitation }, true)}>Save engineering investigation</button></fieldset></details>
        <details className="aw-references"><summary>Stage controlled synthetic TLS records</summary><fieldset className="aw-field-group" disabled={reviewEdited || researchEdited || !!purpose || !!assignedTo}><p className="aw-boundary">Only the bounded synthetic TLS format is qualified. No arbitrary vendor export, live source connector or network access is enabled.</p>{!investigation.canStageEvidence && <p>{investigation.evidenceBlockingReason || 'This action requires the assessment lead and current scope/access gate prerequisites.'}</p>}<label className="aw-field"><span>Assessed deployment for this capture</span><select value={productId} disabled={locked || !investigation.canStageEvidence} onChange={event => setProductId(event.target.value)}><option value="">Choose the subject, not its evidence source</option>{products.map(value => <option key={value.id} value={value.id}>{value.label || value.product}</option>)}</select></label><Field label="Separate source supplying these observations" value={source} change={setSource} disabled={locked || !investigation.canStageEvidence} maxLength={256} /><label className="aw-field"><span>Controlled synthetic TLS JSON (maximum 32 KiB)</span><input key={file ? 'selected' : 'empty'} type="file" accept=".json" disabled={locked || !investigation.canStageEvidence} onChange={event => { const value = event.target.files?.[0]; if (value && (!value.name.toLowerCase().endsWith('.json') || value.size > 32768)) { setFileError('Choose one controlled JSON fixture no larger than 32 KiB.'); setFile(undefined); } else { setFileError(''); setFile(value); } }} /></label>{fileError && <p role="alert">{fileError}</p>}<button className="button secondary" disabled={locked || !investigation.canStageEvidence || !productId || !source.trim() || !file || researchEdited} onClick={() => file && void stage(investigation.id, productId, source, file)}>Stage records for independent review</button></fieldset></details>
      </>}
    </>}
    {records.length > 1 && <><label className="aw-field"><span>Technical bundle to review or admit</span><select value={reviewBatch} disabled={locked || dirty} onChange={event => setReviewBatch(event.target.value)}>{records.map(value => <option key={value.bundleId} value={value.bundleId}>{value.productLabel} — {value.sourceLabel} · {named(value.status)}</option>)}</select></label><small className="aw-help">Complete or discard one bundle's edits before reviewing another. All records remain readable below.</small></>}
    {records.map(bundle => { const permission = investigations.find(value => value.id === bundle.investigationId); const workspace = bundle.bundleId.startsWith('wbundle-'); const selectedForReview = bundle.bundleId === reviewBatch; const canReview = selectedForReview && !otherTechnicalEdits && (workspace ? bundle.canReview === true : permission?.canReviewEvidence); const canAdmit = selectedForReview && !otherTechnicalEdits && (workspace ? bundle.canAdmit === true : permission?.canAdmitEvidence); return <article className="aw-record" key={bundle.bundleId}><span className="aw-status">{named(bundle.status)}</span><h3>{bundle.productLabel} ← {bundle.sourceLabel}</h3>{bundle.status === 'identity_review_required' && <aside className="aw-boundary"><strong>Identity correction requires new technical review and lead admission.</strong><p>{bundle.identityChangeReason || 'The current system association changed. Earlier admitted records cannot support current map or report inputs until this association is reviewed.'}</p><details><summary>Proposed reviewed identity</summary><p>{bundle.proposedCanonicalId || 'Identity remains unresolved'}</p></details></aside>}<p>Subject and evidence source are separate identities. Conflicting records remain visible; a later or more favorable value is not automatically preferred.</p>{bundle.observations.map(observation => <div key={observation.id}><ObservationRead value={observation} />{workspace && (bundle.status === 'staged' || bundle.status === 'identity_review_required') && <><label className="aw-field"><span>Record determination for {observation.nativeId}</span><select value={recordDecisions[observation.id]?.determination || ''} disabled={locked || !canReview} onChange={event => { setRecordDecisions(previous => ({ ...previous, [observation.id]: { rationale: previous[observation.id]?.rationale || '', determination: event.target.value } })); setConfirmation(''); }}><option value="">Choose what this record establishes</option><option value="supports_claim">Supports the stated claim within its evidence basis</option><option value="conflict">Conflicts with other supplied information</option><option value="cannot_establish">Cannot establish the technical claim</option></select></label><Field label={`Record rationale for ${observation.nativeId}`} value={recordDecisions[observation.id]?.rationale || ''} change={value => { setRecordDecisions(previous => ({ ...previous, [observation.id]: { determination: previous[observation.id]?.determination || '', rationale: value } })); setConfirmation(''); }} multiline disabled={locked || !canReview} /></>}</div>)}{!bundle.observations.length && <p className="aw-boundary">No readable observations were returned for this bundle. Do not qualify it from counts or file identity alone.</p>}{bundle.reviewRationale && <p><strong>Recorded review:</strong> {bundle.reviewRationale}</p>}
      {(bundle.status === 'staged' || bundle.status === 'identity_review_required') && <><p className="aw-help">Qualification requires a determination and rationale for every displayed record, plus the bundle review rationale. A clarification request requires the bundle rationale but may leave record-level determinations incomplete.</p><Field required label={`Technical review rationale for ${bundle.productLabel}`} value={rationale[bundle.bundleId] || ''} change={value => { setRationale(previous => ({ ...previous, [bundle.bundleId]: value })); setConfirmation(''); }} multiline disabled={locked || !canReview} help="Explain what the actual records support, what differs from reported information, and what remains unverified." />{!canReview && <p className="aw-help">A designated technical reviewer different from the stager must supply this determination.</p>}<div className="aw-actions">{(['qualified', 'needs_clarification'] as const).map(determination => { const key = `${bundle.bundleId}:${determination}`; return <button key={determination} className="button secondary" disabled={locked || !canReview || !rationale[bundle.bundleId]?.trim() || !bundle.observations.length || workspace && determination === 'qualified' && bundle.observations.some(value => !recordDecisions[value.id]?.determination || !recordDecisions[value.id]?.rationale.trim())} onClick={() => confirmation !== key ? setConfirmation(key) : void send(workspace ? 'workspace_review_evidence' : 'discovery_review_evidence', workspace ? bundle.bundleId : bundle.investigationId, { ...(!workspace ? { batchId: bundle.bundleId } : {}), determination, rationale: rationale[bundle.bundleId], ...(workspace ? { recordDecisions: bundle.observations.filter(value => recordDecisions[value.id]?.determination).map(value => ({ observationId: value.id, ...recordDecisions[value.id] })) } : {}) }, !workspace)}>{confirmation === key ? `Confirm ${determination === 'qualified' ? 'qualified determination' : 'clarification request'}` : determination === 'qualified' ? 'Review qualified determination' : 'Request technical clarification'}</button>; })}</div>{confirmation.startsWith(bundle.bundleId) && <p className="aw-boundary">Confirming records the stated determination for this exact bundle. It does not admit the records or accept a report.</p>}</>}
      {bundle.status === 'needs_clarification' && <p className="aw-boundary">Clarification is required. Record the investigation limitation and supply a corrected capture as a new bundle; this determination remains in history.</p>}
      {bundle.status === 'qualified' && <><p>Next: the assessment lead checks current scope and gates, then admits only this reviewed bundle.</p><button className="button primary" disabled={locked || !canAdmit} onClick={() => confirmation !== bundle.bundleId ? setConfirmation(bundle.bundleId) : void send(workspace ? 'workspace_admit_evidence' : 'discovery_admit_evidence', workspace ? bundle.bundleId : bundle.investigationId, workspace ? {} : { batchId: bundle.bundleId }, !workspace)}>{confirmation === bundle.bundleId ? 'Confirm admission to assessment inputs' : 'Review lead admission'}</button>{!canAdmit && <p className="aw-help">Admission requires the lead role and valid G00 / P1-G01 boundaries.</p>}</>}
      {bundle.status === 'admitted' && <p>These records are admitted to the map and future report inputs. Historical report bytes are unchanged. Review the assessment consequence next.</p>}
    </article>; })}
    {!records.length && <p>No technical records have been staged for this investigation. Submitted answers are not a substitute for technical observations.</p>}
    <div className="aw-actions"><button className="button secondary" disabled={dirty || locked} onClick={() => onNavigate('assessments', { assessment: current.assessmentId, stage: '2' })}>Read scope and evidence gates</button>{dirty && <button className="text-button" disabled={locked} onClick={() => { setPurpose(''); setAssignedTo(''); setResearch(investigation?.researchSummary || ''); setMethod(investigation?.proposedMethod || ''); setDocumentation(investigation?.documentationRefs.join('\n') || ''); setLimitation(investigation?.limitation || ''); setStatus(investigation?.status || 'planned'); setResearchEdited(false); setProductId(''); setSource(''); setFile(undefined); setRationale({}); setRecordDecisions({}); setConfirmation(''); }}>Discard unsaved technical review edits</button>}</div>
  </section>;
}

function consequenceFields(value?: WorkConsequence): WorkConsequence {
  return { phase1Conclusion: value?.phase1Conclusion || '', limitation: value?.limitation || '', nextDecision: value?.nextDecision || '', responsibleFunction: value?.responsibleFunction || '', phase2Consequence: value?.phase2Consequence || '', lifetime: value?.lifetime || '', confidence: value?.confidence || 'unknown', productId: value?.productId || '', cryptographicPurpose: value?.cryptographicPurpose || 'unknown', supportingObservationIds: value?.supportingObservationIds || [], contradictingObservationIds: value?.contradictingObservationIds || [] };
}
function Consequence({ current, locked, onDirty, send, preview, onNavigate }: { current: WorkCase; locked: boolean; onDirty: Dirty; send: Send; preview: (fields: WorkConsequence, callback: (value: ImpactPreview) => void) => Promise<boolean>; onNavigate: Navigate }) {
  const recorded = current.consequences || (current.consequence ? [current.consequence] : []);
  const [selectedId, setSelectedId] = useState(current.consequence?.id || '');
  const selected = recorded.find(value => value.id === selectedId);
  const initial = consequenceFields(selected);
  const [fields, setFields] = useState(initial); const [impact, setImpact] = useState<ImpactPreview>();
  const dirty = JSON.stringify(fields) !== JSON.stringify(initial); useDirty(dirty, onDirty);
  const canEdit = current.allowedActions.includes('record_consequence');
  const update = (key: keyof WorkConsequence, value: string) => { setFields(previous => ({ ...previous, [key]: value })); setImpact(undefined); };
  const products = current.receipts.filter(value => value.status === 'applied').flatMap(value => value.products);
  const canonical = current.identityDecisions.find(value => value.productId === fields.productId)?.canonicalId;
  const admitted = current.technicalRecords.filter(value => value.status === 'admitted').flatMap(bundle => bundle.observations.map(observation => ({ ...observation, productId: observation.productId || bundle.productId, canonicalId: observation.canonicalId || bundle.canonicalId, productLabel: bundle.productLabel, sourceLabel: bundle.sourceLabel }))).filter(observation => !fields.productId || observation.productId === fields.productId || !!canonical && observation.canonicalId === canonical);
  const unavailableReferences = [...(fields.supportingObservationIds || []), ...(fields.contradictingObservationIds || [])].filter(id => !admitted.some(value => value.id === id));
  const hasSelectedEvidence = (fields.supportingObservationIds?.length || 0) + (fields.contradictingObservationIds?.length || 0) > 0;
  const missingConsequence = [...(!fields.phase1Conclusion.trim() ? ['Phase 1 conclusion'] : []), ...(!fields.nextDecision.trim() ? ['next decision'] : []), ...(!fields.responsibleFunction.trim() ? ['next responsible function'] : []), ...(!hasSelectedEvidence && !fields.limitation.trim() ? ['a limitation explaining the lack of selected evidence'] : []), ...(fields.confidence === 'supported' && !fields.supportingObservationIds?.length ? ['explicitly selected supporting evidence for supported confidence'] : [])];
  const evidenceChoice = (id: string, value: string) => {
    setFields(previous => ({ ...previous, supportingObservationIds: [...(previous.supportingObservationIds || []).filter(item => item !== id), ...(value === 'supporting' ? [id] : [])], contradictingObservationIds: [...(previous.contradictingObservationIds || []).filter(item => item !== id), ...(value === 'contradicting' ? [id] : [])] })); setImpact(undefined);
  };
  return <section className="aw-panel"><h2>What will this change in the assessment?</h2><p>Write the bounded conclusion, not a transcription of all records. Separate established facts from uncertainty and recommendations. Proposed standards cannot create retrospective noncompliance findings.</p>
    {recorded.length > 0 && <section className="aw-record"><h3>Recorded conclusions by deployment and use</h3><p>Key establishment, authentication and other purposes retain separate conclusions. Choose one to revise, or start another; historical report snapshots remain unchanged.</p><label className="aw-field"><span>Conclusion to review or revise</span><select value={selectedId} disabled={locked || dirty} onChange={event => { const value = recorded.find(item => item.id === event.target.value); setSelectedId(event.target.value); setFields(consequenceFields(value)); setImpact(undefined); }}><option value="">Start a separate conclusion</option>{recorded.map(value => <option key={value.id} value={value.id}>{products.find(product => product.id === value.productId)?.deployment || 'Whole case'} — {named(value.cryptographicPurpose)} — {named(value.confidence)}</option>)}</select></label><ul className="aw-history">{recorded.map(value => <li key={value.id}><strong>{products.find(product => product.id === value.productId)?.deployment || 'Whole case'} · {named(value.cryptographicPurpose)}</strong><p>{value.phase1Conclusion}</p>{value.limitation && <p className="aw-help">Limitation: {value.limitation}</p>}</li>)}</ul></section>}
    {selected && <p className="aw-status">Current determination: {named(selected.status)}</p>}
    {selected?.status === 'needs_review' && <p className="aw-boundary">This conclusion needs re-review because a relevant input changed. Its prior version remains history; do not treat it as a currently supported report conclusion.</p>}
    {unavailableReferences.length > 0 && <aside className="aw-boundary"><p>{unavailableReferences.length} previously selected record reference(s) are no longer admitted within this deployment scope. Re-review and re-admit the affected bundle, or explicitly remove those references and record a limitation.</p><button className="button secondary" disabled={locked || !canEdit} onClick={() => { setFields(previous => ({ ...previous, supportingObservationIds: previous.supportingObservationIds?.filter(id => !unavailableReferences.includes(id)), contradictingObservationIds: previous.contradictingObservationIds?.filter(id => !unavailableReferences.includes(id)) })); setImpact(undefined); }}>Remove references needing re-review</button></aside>}
    {!canEdit && <p className="aw-boundary">Your role can read these consequences. The assigned assessment authority records the next revision; formal technical, business and deliverable review remains separate.</p>}
    <label className="aw-field"><span>Affected deployment for this conclusion</span><select value={fields.productId} disabled={locked || !canEdit} onChange={event => { setFields(previous => ({ ...previous, productId: event.target.value, supportingObservationIds: [], contradictingObservationIds: [] })); setImpact(undefined); }}><option value="">Whole case / deployment not yet established</option>{products.map(value => <option key={value.id} value={value.id}>{value.product} — {value.deployment}</option>)}</select></label>
    <label className="aw-field"><span>Cryptographic purpose being assessed</span><select value={fields.cryptographicPurpose} disabled={locked || !canEdit} onChange={event => update('cryptographicPurpose', event.target.value)}><option value="unknown">Not established</option><option value="context">Enterprise context</option><option value="key_establishment">Key establishment</option><option value="authentication">Authentication signatures</option><option value="data_protection">Data protection</option><option value="software_signing">Software signing</option></select></label>
    <section className="aw-record"><h3>Evidence supporting or contradicting this conclusion</h3><p>Select the actual admitted records relied upon. Admission does not mean every record supports the conclusion. Changing the affected deployment clears this selection for explicit re-review.</p>{!admitted.length && <p className="aw-boundary">No technical evidence is admitted. Record the limitation and use unknown or limited confidence; do not manufacture support.</p>}{admitted.map(observation => <article className="aw-record" key={observation.id}><h4>{observation.productLabel} — {observation.hostname || observation.nativeId}</h4><p>{observation.sourceLabel} · {named(observation.basis)} · {text(observation.keyExchange || observation.authentication || observation.label)}</p><label className="aw-field"><span>Use record {observation.nativeId} in this conclusion</span><select value={fields.supportingObservationIds?.includes(observation.id) ? 'supporting' : fields.contradictingObservationIds?.includes(observation.id) ? 'contradicting' : ''} disabled={locked || !canEdit} onChange={event => evidenceChoice(observation.id, event.target.value)}><option value="">Not relied upon</option><option value="supporting">Supporting evidence</option><option value="contradicting">Contradicting evidence / unresolved difference</option></select></label></article>)}</section>
    <Field required label="Phase 1 conclusion supported by this case" value={fields.phase1Conclusion} change={value => update('phase1Conclusion', value)} multiline disabled={locked || !canEdit} /><Field required={!hasSelectedEvidence} label="Material limitation and what cannot be concluded" value={fields.limitation} change={value => update('limitation', value)} multiline disabled={locked || !canEdit} /><Field required label="Next decision needed" value={fields.nextDecision} change={value => update('nextDecision', value)} multiline disabled={locked || !canEdit} /><Field required label="Next responsible function" value={fields.responsibleFunction} change={value => update('responsibleFunction', value)} disabled={locked || !canEdit} /><Field label="Conditional Phase 2 business consequence" value={fields.phase2Consequence} change={value => update('phase2Consequence', value)} multiline disabled={locked || !canEdit} help="Identify the consequence and the reviewer who must confirm it. Do not invent financial loss, probabilities or enterprise risk acceptance." /><Field label="Confidentiality or trust lifetime and its basis" value={fields.lifetime} change={value => update('lifetime', value)} multiline disabled={locked || !canEdit} help="Record known information lifetime and who supplied it; otherwise leave it explicitly unknown." />
    <label className="aw-field"><span>Evidence confidence for this conclusion</span><select value={fields.confidence} disabled={locked || !canEdit} onChange={event => update('confidence', event.target.value)}><option value="unknown">Unknown</option><option value="limited">Limited</option><option value="supported">Supported by reviewed evidence</option></select></label>
    {canEdit && <RequiredNotice items={missingConsequence} />}
    <div className="aw-actions"><button className="button secondary" disabled={locked || !canEdit || unavailableReferences.length > 0 || missingConsequence.length > 0} onClick={() => void preview(fields, setImpact)}>Preview exact report consequence</button>{dirty && <button className="text-button" disabled={locked} onClick={() => { setFields(initial); setImpact(undefined); }}>Discard consequence edits</button>}</div>
    {impact && <section className="aw-preview" aria-label="Report consequence preview"><p className="eyebrow">PREVIEW ONLY / NO REPORT CHANGED</p><h3>Phase 1 will explain</h3><p>{impact.phase1Text}</p><h3>Phase 2 may rely on</h3><p>{impact.phase2Text}</p><h3>Remaining limitations</h3><ul>{impact.limitations.map((value, index) => <li key={index}>{value}</li>)}</ul><p><strong>Next decision:</strong> {impact.nextDecision}</p><p>Recording creates a traceable conclusion revision. It does not accept a deliverable, adopt a standard or authorize a migration. Changed inputs require a fresh preview.</p><button className="button primary" disabled={locked || !canEdit || impact.revision !== current.revision} onClick={() => void send('record_consequence', current.request.id, { ...fields, previewFingerprint: impact.previewFingerprint })}>Record this reviewed consequence</button></section>}
    <section className="aw-record"><h3>Continue from conclusions to a reviewed report</h3><p>A recorded conclusion is report input, not a finished assessment. The assessment lead prepares the package; the designated technical reviewer reviews it; sponsor and lead review the exact Phase 1 report. The risk lead then selects that Phase 1 basis and prepares Phase 2 analysis for business review.</p><div className="aw-actions"><button className="button secondary" disabled={dirty || locked} onClick={() => onNavigate('assessments', { assessment: current.assessmentId, stage: '3' })}>Continue technical package review</button><button className="button secondary" disabled={dirty || locked} onClick={() => onNavigate('assessments', { assessment: current.assessmentId, stage: '4' })}>Phase 1 report and handoff</button><button className="button secondary" disabled={dirty || locked} onClick={() => onNavigate('assessments', { assessment: current.assessmentId, stage: '5' })}>Phase 2 method and reliance</button><button className="button secondary" disabled={dirty || locked} onClick={() => onNavigate('reports', { assessment: current.assessmentId })}>Read report snapshots</button></div><p className="aw-help">These links change the view only. They do not complete a gate, select a reliance package or record a decision.</p></section>
  </section>;
}
