import { useEffect, useId, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { api, ApiError, humanize, selectedAssessmentId } from './api';
import { useApi } from './use-api';
import type { Session } from './contracts';
import type { AssessmentCatalog, AssessmentSummary } from './assessment-contracts';
import type { IntakeCommand, IntakeExport, IntakeImport, IntakeRequest, IntakeSystem, IntakeView } from './intake-contracts';
import './intake.css';

type Navigate = (page: string, params?: Record<string, string>) => void;
type Command = (operation: string, targetId: string | undefined, fields: Record<string, unknown>) => Promise<boolean>;
type Pending = { path: string; options: RequestInit; success: (value: unknown) => void };
const isContributor = (session: Session) => session.role === 'contributor' || session.role === 'contributor-two';
const statusLabels: Record<string, string> = { draft: 'Needs a first response', responding: 'Response in progress', assigned: 'Needs a first response', returned: 'With the coordinator / reviewer', closed_with_limitation: 'Reviewed with limitations', clarification_needed: 'Clarification requested', qualified: 'Usable with limitations', needs_clarification: 'Clarification requested', awaiting_review: 'Not yet reviewed' };
const statusLabel = (value: string) => statusLabels[value] || humanize(value);
function Field({ label, value, onChange, help, required = false, multiline = false }: { label: string; value: string; onChange: (value: string) => void; help?: string; required?: boolean; multiline?: boolean }) {
  const id = useId();
  return <div className="intake-field"><label htmlFor={id}>{label}{!required && <small> · optional</small>}</label>{multiline ? <textarea id={id} value={value} onChange={event => onChange(event.target.value)} rows={3} maxLength={512} required={required} aria-describedby={help ? `${id}-help` : undefined} /> : <input id={id} value={value} onChange={event => onChange(event.target.value)} maxLength={500} required={required} aria-describedby={help ? `${id}-help` : undefined} />}{help && <p id={`${id}-help`} className="intake-help">{help}</p>}</div>;
}
function Panel({ title, children, className = '' }: { title: string; children: ReactNode; className?: string }) { return <section className={`intake-panel ${className}`}><h2>{title}</h2>{children}</section>; }

/** This surface projects server-owned assignments; it does not evaluate assessment gates. */
export function IntakeWorkspace({ session, onNavigate, onDirtyChange }: { session: Session; onNavigate: Navigate; onDirtyChange?: (dirty: boolean) => void }) {
  const [id, setId] = useState(selectedAssessmentId);
  const [selected, setSelected] = useState(() => new URLSearchParams(window.location.hash.split('?')[1]).get('request') || '');
  const [refresh, setRefresh] = useState(0);
  const [view, setView] = useState<IntakeView>();
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [accessUnavailable, setAccessUnavailable] = useState(false);
  const [conflict, setConflict] = useState(false);
  const [epoch, setEpoch] = useState(0);
  const [exported, setExported] = useState<IntakeExport>();
  const [preview, setPreview] = useState<IntakeImport>();
  const [unsavedAnswers, setUnsavedAnswers] = useState(false);
  const pending = useRef<Pending | undefined>(undefined);
  const acting = useRef(false);
  const assessments = useApi<AssessmentSummary[]>('/api/assessments', refresh);
  useEffect(() => { onDirtyChange?.(unsavedAnswers); return () => onDirtyChange?.(false); }, [unsavedAnswers, onDirtyChange]);
  useEffect(() => {
    if (!unsavedAnswers) return;
    const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; };
    window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn);
  }, [unsavedAnswers]);
  useEffect(() => { const update = () => { setId(selectedAssessmentId()); setSelected(new URLSearchParams(window.location.hash.split('?')[1]).get('request') || ''); }; window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  useEffect(() => {
    setView(undefined); setError(''); setAccessUnavailable(false); setConflict(false); setPreview(undefined); setExported(undefined); pending.current = undefined;
    if (!id) { setLoading(false); return; }
    const abort = new AbortController(); setLoading(true);
    api<IntakeView>(`/api/assessments/${encodeURIComponent(id)}/intake`, { signal: abort.signal }).then(value => { if (!abort.signal.aborted) setView(value); }).catch(reason => {
      if (abort.signal.aborted) return;
      if (reason instanceof ApiError && [403, 404].includes(reason.status)) { setAccessUnavailable(true); setError('This assessment is not available to your signed-in persona. The link may belong to another contributor or an assignment may have changed. Choose one of your assigned assessments; an unavailable request does not mean the assessment is complete.'); }
      else setError(reason instanceof ApiError ? reason.message : 'This request workspace could not be loaded. No answers have been changed.');
    }).finally(() => { if (!abort.signal.aborted) setLoading(false); });
    return () => abort.abort();
  }, [id, refresh]);
  useEffect(() => { setPreview(undefined); setExported(undefined); }, [selected]);
  const request = view?.requests.find(item => item.id === selected) || (!selected ? view?.requests[0] : undefined);
  const locked = busy || !!pending.current || conflict;
  const requestOutOfScope = !!request && !(view?.eligibleFamilyIds || []).includes(request.familyId);
  const requestLocked = locked || requestOutOfScope;
  const basePath = `/api/assessments/${encodeURIComponent(id)}/intake`;
  async function execute(action: Pending, retry = false): Promise<boolean> {
    if (acting.current || conflict || (!retry && pending.current)) return false;
    acting.current = true; pending.current = action; setBusy(true); setError('');
    try {
      const result = await api<unknown>(action.path, action.options);
      pending.current = undefined; action.success(result); return true;
    } catch (reason) {
      if (reason instanceof ApiError && reason.status < 500) pending.current = undefined;
      if (reason instanceof ApiError && ['assessment_revision_changed', 'intake_preview_stale', 'intake_export_stale'].includes(reason.code || '')) { setConflict(true); setError(`${reason.message} Your entered answers are still visible. Copy anything you need before loading the saved revision; no competing edit was overwritten.`); }
      else setError(reason instanceof ApiError ? reason.message : 'Delivery was interrupted. Keep this page open and retry the original operation; the same request identity will prevent a duplicate.');
      return false;
    } finally { acting.current = false; setBusy(false); }
  }
  function headers(type = 'application/json') { return { 'X-PQC-CSRF': session.csrfToken || '', 'Idempotency-Key': crypto.randomUUID(), 'Content-Type': type }; }
  const command: Command = async (operation, targetId, fields) => {
    if (!view || !session.csrfToken) return false;
    if (unsavedAnswers && operation !== 'intake_save_response') { setError('Save or explicitly discard the unsaved web answers before another operation. They are not in the assessment yet.'); return false; }
    const body: IntakeCommand = { operation, targetId: targetId ?? null, fields, expectedRevision: view.revision };
    return execute({ path: `${basePath}/commands`, options: { method: 'POST', headers: headers(), body: JSON.stringify(body) }, success: result => { setView(result as IntakeView); setPreview(undefined); setExported(undefined); } });
  };
  async function exportRequest() {
    if (!request || !view || unsavedAnswers) return;
    await execute({ path: `${basePath}/exports/${encodeURIComponent(request.id)}`, options: { method: 'POST', headers: headers(), body: JSON.stringify({ expectedRevision: view.revision }) }, success: value => { const result = value as IntakeExport; setExported(result); setView(current => current ? { ...current, revision: result.revision } : current); } });
  }
  async function importRequest(file: File | undefined) {
    if (!file || !view || !request || unsavedAnswers) return;
    if (!file.name.toLowerCase().endsWith('.xlsx') || file.size > 1024 * 1024) { setError('Choose an .xlsx questionnaire no larger than 1 MiB. The server independently checks the file contents.'); return; }
    await execute({ path: `${basePath}/imports/${encodeURIComponent(request.id)}?expectedRevision=${view.revision}`, options: { method: 'POST', headers: headers('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'), body: file }, success: value => { const result = value as IntakeImport; setPreview(result); setView(current => current ? { ...current, revision: result.revision } : current); } });
  }
  async function stageEvidence(file: File, systemId: string, sourceSystemId: string) {
    if (!view || !request || unsavedAnswers) return false;
    if (!file.name.toLowerCase().endsWith('.json') || file.size > 32 * 1024) { setError('Choose a qualified synthetic TLS source-page JSON no larger than 32 KiB. Arbitrary exports are not supported.'); return false; }
    const query = new URLSearchParams({ systemId, sourceSystemId, expectedRevision: String(view.revision) });
    return execute({ path: `${basePath}/evidence/${encodeURIComponent(request.id)}?${query}`, options: { method: 'POST', headers: headers(), body: file }, success: value => setView(value as IntakeView) });
  }
  function openRequest(requestId: string) { if (!unsavedAnswers) onNavigate('intake', { assessment: id, request: requestId }); }
  return <div className="intake-workspace">
    <header className="intake-header"><div><p className="eyebrow">{isContributor(session) ? 'SOURCE DISCOVERY' : 'DISCOVERY & EVIDENCE INTAKE'}</p><h1>{isContributor(session) ? 'My requests' : 'Turn useful answers into a defensible map.'}</h1><p>Identify the systems. Explain what is known. Hand off what needs help. See the consequence in the assessment.</p></div><span className="badge attention">Synthetic development slice</span></header>
    <ol className="intake-journey" aria-label="How your contribution becomes useful"><li><span>01</span><strong>Find the right source</strong><small>Known systems or a useful referral</small></li><li><span>02</span><strong>Share what you know</strong><small>Web form or returned Excel</small></li><li><span>03</span><strong>Review and hand off</strong><small>Knowledge and gaps stay distinct</small></li><li><span>04</span><strong>Explain the result</strong><small>Map and draft report inputs</small></li></ol>
    <div className="intake-boundary">Use synthetic information only. No messages are sent, no enterprise approval is recorded, and no source system is changed.</div>
    <label className="intake-assessment-selector"><span>Assessment workspace</span><select value={id} disabled={busy || !!pending.current || unsavedAnswers} onChange={event => onNavigate('intake', { assessment: event.target.value, request: '' })}><option value="">Choose an assessment</option>{assessments.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    {assessments.error && <div role="alert" className="notice error">{assessments.error}<button className="button secondary" onClick={assessments.reload}>Reload assessment choices</button></div>}
    {!id && <Panel title={isContributor(session) ? 'Start with an assigned request' : 'Choose where this intake belongs'}><p>{isContributor(session) ? 'Choose an assessment above to see the requests assigned to your signed-in persona. If none are available, ask the coordinator to establish the assignment; an empty list is not a completed assessment.' : 'Every answer, deployment and report contribution belongs to an assessment. Select one above, or establish a fresh boundary first.'}</p>{!isContributor(session) && session.role === 'analyst' && <button className="button primary" onClick={() => onNavigate('assessments', { assessment: '', from: 'intake' })}>Create or set up an assessment</button>}</Panel>}
    {loading && <p role="status" className="loading">Loading your authorized requests…</p>}
    {error && <div className="notice error intake-error" role="alert"><p>{error}</p>{pending.current && <button disabled={busy} className="button secondary" onClick={() => void execute(pending.current!, true)}>Retry original operation</button>}{conflict && <button className="button secondary" onClick={() => { setEpoch(value => value + 1); setRefresh(value => value + 1); }}>Discard local draft and load saved revision</button>}{accessUnavailable && <button className="button secondary" onClick={() => onNavigate('intake', { assessment: '', request: '' })}>Clear this link and choose my assignments</button>}{!view && !loading && !pending.current && id && !accessUnavailable && <button className="button secondary" onClick={() => setRefresh(value => value + 1)}>Reload requests</button>}</div>}
    {view && <>
      {unsavedAnswers && <section className="intake-unsaved" role="status"><strong>Your web answers have unsaved edits.</strong><p>Use “Save partial response” below, or explicitly discard the edits here. Excel export/import, adding systems and changing workspaces are paused so your visible answers cannot silently disappear or be omitted.</p><button disabled={busy || !!pending.current} className="button secondary" onClick={() => { setEpoch(value => value + 1); setUnsavedAnswers(false); }}>Discard unsaved web edits</button></section>}
      <div className="intake-context"><strong>{view.assessmentName}</strong><span>Revision {view.revision}</span><span>{view.requests.length} visible requests · not a coverage denominator</span></div>
      {view.receipt && <section className="intake-receipt" role="status"><p className="eyebrow">WHAT CHANGED</p><h2>{view.receipt.effect}</h2><p><strong>Next responsible:</strong> {view.receipt.nextResponsible.replace('synthetic-demo:', 'Demo ')}</p>{view.requests.some(item => item.id === view.receipt?.nextAction) ? <button className="text-button" onClick={() => openRequest(view.receipt!.nextAction)}>Open the updated request → {view.requests.find(item => item.id === view.receipt?.nextAction)?.title}</button> : <p><strong>Next action:</strong> {view.receipt.nextAction}</p>}</section>}
      {view.canCoordinate && <CreateRequest disabled={locked || unsavedAnswers} command={command} eligibleFamilyIds={view.eligibleFamilyIds || []} />}
      <div className="intake-layout"><aside className="intake-request-list" aria-label="Assigned requests"><h2>{isContributor(session) ? 'Your contribution' : 'Tracked requests'}</h2>{view.requests.map(item => <button disabled={busy || !!pending.current || unsavedAnswers} key={item.id} aria-current={request?.id === item.id ? 'true' : undefined} onClick={() => openRequest(item.id)}><strong>{item.title}</strong><span className="badge">{statusLabel(item.status)}</span><small>{item.systemIds.length} system records · {item.assignedTo.replace('synthetic-demo:', 'Demo ')}</small></button>)}{!view.requests.length && <p>No requests are assigned here. {view.canCoordinate ? 'Create a focused request above; no questionnaire has been sent automatically.' : 'Ask the coordinator for a request, or select another assessment. This does not mean the evidence is complete.'}</p>}</aside>
        <div className="intake-task">{selected && !request && <Panel title="Request unavailable"><p>This request is not available to your current identity. Choose one of the requests in your list.</p></Panel>}{request && <>
          <Panel title={request.title} className="intake-purpose"><p className="eyebrow">WHY THIS REQUEST MATTERS</p><p>{request.whyItMatters}</p><div className="intake-recognition"><strong>Recognition examples—not confirmed enterprise selections</strong><p>{request.examples.length ? request.examples.join(' · ') : 'Use the software class described in this request; the coordinator can help identify examples.'}</p></div><p>Help us locate existing information: name a product, document reference, team or unknown. You do not need to create documents or demonstrate compliance. Do not submit credentials or sensitive files. Any later collection or system access must be agreed separately with the appropriate owner.</p></Panel>
          {requestOutOfScope && <div className="intake-empty" role="status"><strong>This request is outside the current assessment boundary.</strong><p>Its history remains visible, but answers, exports, imports, review and evidence admission are read-only. Ask the assessment lead to review the scope before resuming this work.</p>{view.canCoordinate && <button className="text-button" onClick={() => onNavigate('assessments', { assessment: id, stage: '1' })}>Review the assessment boundary →</button>}</div>}
          <SystemMap systems={view.systems.filter(system => system.requestId === request.id)} />
          {(view.canCoordinate || request.assignedTo === `synthetic-demo:${session.role}`) && <AddSystem key={`system-${request.id}-${epoch}`} request={request} systems={view.systems} command={command} disabled={requestLocked || unsavedAnswers} />}
          <ResponseForm key={`response-${request.id}-${epoch}`} request={request} view={view} session={session} command={command} onDirtyChange={setUnsavedAnswers} disabled={requestLocked || !(view.canCoordinate || request.assignedTo === `synthetic-demo:${session.role}`)} />
          <Panel title="Use the same questionnaire in Excel"><p>Export a server-linked copy, fill it out offline, then preview the changes before applying them. An export is not an email delivery. Spreadsheet acceptance cells cannot grant approval.</p><div className="intake-buttons"><button className="button secondary" disabled={requestLocked || unsavedAnswers || !(view.canCoordinate || request.assignedTo === `synthetic-demo:${session.role}`)} onClick={() => void exportRequest()}>Prepare Excel questionnaire</button>{exported && !unsavedAnswers && exported.downloadUrl.startsWith(`${basePath}/`) && <a className="button secondary" href={exported.downloadUrl} download>Download prepared Excel file</a>}</div><label className="intake-file"><span>Preview a returned questionnaire (.xlsx)</span><input type="file" accept=".xlsx" disabled={requestLocked || unsavedAnswers || !(view.canCoordinate || request.assignedTo === `synthetic-demo:${session.role}`)} onChange={event => { void importRequest(event.target.files?.[0]); event.target.value = ''; }} /></label>{unsavedAnswers && <p className="intake-help">Excel is paused: save or explicitly discard your unsaved web answers first. An exported file contains saved answers only.</p>}<p className="intake-help">Maximum workbook size: 1 MiB. Use the generated questionnaire; arbitrary workbooks and legacy layouts are not qualified in this slice.</p>{preview && <ImportPreview key={preview.previewId} preview={preview} systems={view.systems} command={command} requestId={request.id} disabled={requestLocked || unsavedAnswers} />}</Panel>
          {view.canReview && <ReviewResponse key={`review-${request.id}-${epoch}`} request={request} command={command} disabled={requestLocked || unsavedAnswers} />}
          <EvidenceReadback view={view} request={request} />
          <EvidenceIntake key={`evidence-${request.id}-${epoch}`} view={view} request={request} disabled={requestLocked || unsavedAnswers} canStage={view.canCoordinate || request.assignedTo === `synthetic-demo:${session.role}`} stage={stageEvidence} command={command} onNavigate={onNavigate} />
        </>}</div>
      </div>
      <ReportEffect view={view} onNavigate={onNavigate} disabled={locked || unsavedAnswers} />
      <p className="intake-help">{view.boundary}</p>
    </>}
  </div>;
}

function CreateRequest({ disabled, command, eligibleFamilyIds }: { disabled: boolean; command: Command; eligibleFamilyIds: string[] }) {
  const catalog = useApi<AssessmentCatalog>('/api/assessments/catalog');
  const [title, setTitle] = useState(''); const [familyId, setFamilyId] = useState(''); const [assignedTo, setAssignedTo] = useState('synthetic-demo:contributor');
  useEffect(() => { if (familyId && !eligibleFamilyIds.includes(familyId)) setFamilyId(''); }, [familyId, eligibleFamilyIds]);
  const families = catalog.data?.sourceFamilies.filter(item => eligibleFamilyIds.includes(item.familyId)) || [];
  return <details className="intake-panel intake-create"><summary>Create a focused source request</summary><p>Assign one useful contribution. Only source families inside this assessment’s current boundary are offered. The catalog names software classes; it does not establish that those products exist in the enterprise.</p><form onSubmit={event => { event.preventDefault(); void command('intake_create_request', undefined, { title, familyId, assignedTo }).then(ok => { if (ok) setTitle(''); }); }}><fieldset disabled={disabled || catalog.loading || !!catalog.error || !families.length}><Field label="Request title" value={title} onChange={setTitle} required help="For example: Help us identify the customer portal software and the teams familiar with it." /><label className="intake-field"><span>Source family</span><select value={familyId} onChange={event => setFamilyId(event.target.value)} required><option value="">Choose the software class</option>{families.map(item => <option key={item.familyId} value={item.familyId}>{item.name}</option>)}</select></label><label className="intake-field"><span>Assigned synthetic contributor</span><select value={assignedTo} onChange={event => setAssignedTo(event.target.value)}><option value="synthetic-demo:contributor">Source contributor 1</option><option value="synthetic-demo:contributor-two">Source contributor 2</option></select></label><button className="button primary">Create request—not send an email</button></fieldset>{!catalog.loading && !catalog.error && !families.length && <p className="intake-help">No source family is currently eligible for a new request. Review the assessment boundary before assigning work; this is not an absence of enterprise systems.</p>}{catalog.error && <p role="alert">The source catalog is unavailable. <button type="button" onClick={catalog.reload}>Reload catalog</button></p>}</form></details>;
}

function SystemMap({ systems }: { systems: IntakeSystem[] }) {
  return <Panel title="Systems and deployments in this request"><p>A deployment is a system being assessed. An evidence source supplies information about a system. Keep separate deployments separate—even when they use the same product.</p><div className="intake-system-map">{systems.map(system => <article key={system.id}><span className={`badge ${system.systemRole === 'source' ? '' : 'teal'}`}>{system.systemRole === 'subject' ? 'System being assessed' : system.systemRole === 'source' ? 'Evidence source' : 'Assessed system + evidence source'}</span><h3>{system.label}</h3><p>{system.product || 'Product not yet identified'} · {system.environment || 'Environment not yet identified'}</p>{system.aboutSystemId && <p className="intake-linkage">Provides evidence about → <strong>{systems.find(item => item.id === system.aboutSystemId)?.label || 'A linked system outside this request'}</strong></p>}</article>)}</div>{!systems.length && <p className="intake-empty">No systems recorded yet. Add the first known deployment or evidence source below; unknown product details can remain blank.</p>}</Panel>;
}
function AddSystem({ request, systems, command, disabled }: { request: IntakeRequest; systems: IntakeSystem[]; command: Command; disabled: boolean }) {
  const [fields, setFields] = useState({ label: '', product: '', environment: '', systemRole: 'subject', aboutSystemId: '' });
  return <details className="intake-panel"><summary>Add a deployment or evidence source</summary><form onSubmit={event => { event.preventDefault(); void command('intake_add_system', request.id, fields).then(ok => { if (ok) setFields({ label: '', product: '', environment: '', systemRole: 'subject', aboutSystemId: '' }); }); }}><fieldset disabled={disabled}><Field label="System or deployment name" value={fields.label} onChange={label => setFields(current => ({ ...current, label }))} required help="Use an instance name, such as Portal East or Portal West—not just the software vendor." /><div className="intake-two-fields"><Field label="Software product" value={fields.product} onChange={product => setFields(current => ({ ...current, product }))} /><Field label="Environment" value={fields.environment} onChange={environment => setFields(current => ({ ...current, environment }))} /></div><label className="intake-field"><span>This record describes</span><select value={fields.systemRole} onChange={event => setFields(current => ({ ...current, systemRole: event.target.value, aboutSystemId: '' }))}><option value="subject">A system being assessed</option><option value="source">An evidence source</option><option value="both">Both an assessed system and evidence source</option></select></label>{fields.systemRole !== 'subject' && <label className="intake-field"><span>Provides evidence about</span><select value={fields.aboutSystemId} onChange={event => setFields(current => ({ ...current, aboutSystemId: event.target.value }))}><option value="">Relationship not yet established</option>{systems.filter(system => system.systemRole !== 'source').map(system => <option key={system.id} value={system.id}>{system.label}</option>)}</select></label>}<button className="button secondary">Add this separate system record</button></fieldset></form></details>;
}

function ResponseForm({ request, view, session, command, disabled, onDirtyChange }: { request: IntakeRequest; view: IntakeView; session: Session; command: Command; disabled: boolean; onDirtyChange: (dirty: boolean) => void }) {
  const directContributor = isContributor(session);
  const [answers, setAnswers] = useState(request.answers); const [assertedBy, setAssertedBy] = useState(request.assertedBy); const [confirm, setConfirm] = useState(false);
  const savedAnswers = JSON.stringify(request.answers);
  const synchronizedAnswers = useRef(savedAnswers);
  const synchronizedAttribution = useRef(request.assertedBy);
  // State already starts from the server snapshot. Do not replay that initial
  // snapshot after a fast first edit; only synchronize genuinely new readback.
  useLayoutEffect(() => {
    if (synchronizedAnswers.current === savedAnswers) return;
    synchronizedAnswers.current = savedAnswers; setAnswers(JSON.parse(savedAnswers)); setConfirm(false);
  }, [savedAnswers]);
  useLayoutEffect(() => {
    if (synchronizedAttribution.current === request.assertedBy) return;
    synchronizedAttribution.current = request.assertedBy; setAssertedBy(request.assertedBy);
  }, [request.assertedBy]);
  const dirty = JSON.stringify(answers) !== savedAnswers || !directContributor && assertedBy !== request.assertedBy;
  useEffect(() => { onDirtyChange(dirty); }, [dirty, onDirtyChange]);
  const systems = view.systems.filter(system => system.requestId === request.id);
  return <Panel title="Share what you know"><p>Answer only what you can support. “I do not know” or a referral is a useful response, but it does not establish a technical fact. Save a partial response and resume later.</p><form onSubmit={event => { event.preventDefault(); void command('intake_save_response', request.id, { answers, assertedBy: directContributor ? `synthetic-demo:${session.role}` : assertedBy }); }}><fieldset disabled={disabled}>{directContributor ? <p className="intake-attribution">These answers are supplied and recorded by your signed-in synthetic persona: <strong>{session.role}</strong>. If another function needs to answer, record a referral below.</p> : <Field label="Person or function supplying these answers" value={assertedBy} onChange={setAssertedBy} help="For coordinator-assisted entry, preserve the supplying function separately from your signed-in recorder identity. Do not enter credentials or private keys." />}
      <section className="intake-system-questions"><h3>First, help route this request</h3><p>Use these shared answers when you do not yet know the software or deployments. They also provide context for all system records below; a system-specific answer takes precedence.</p>{view.questions.map(question => <Field key={question.id} label={`${question.label} — Whole request`} multiline value={answers[`${request.id}/${question.id}`] || ''} onChange={value => { setAnswers(current => ({ ...current, [`${request.id}/${question.id}`]: value })); setConfirm(false); }} help={`${question.whyItMatters} Useful response: ${question.usefulResponse}`} />)}</section>
      {systems.map(system => <details className="intake-system-questions" key={system.id}><summary>Specific answers for {system.label}</summary><p>Leave blank to retain the shared request context. Add only what differs or is specifically known about this system.</p>{view.questions.map(question => <Field key={question.id} label={`${question.label} — ${system.label}`} multiline value={answers[`${system.id}/${question.id}`] || ''} onChange={value => { setAnswers(current => ({ ...current, [`${system.id}/${question.id}`]: value })); setConfirm(false); }} help={`${question.whyItMatters} Useful response: ${question.usefulResponse}`} />)}</details>)}<div className="intake-buttons"><button className="button primary">Save partial response</button><span className="intake-help">{dirty ? 'Unsaved edits—not yet in the assessment.' : 'Saved answers record what was shared—not independently verified facts.'}</span></div></fieldset></form>
    <div className="intake-submission"><h3>Ready to hand this response to the coordinator?</h3><p>The coordinator will route unresolved questions and arrange factual review. This handoff does not claim all questions are answered.</p>{confirm && <section className="intake-check" aria-label="Check your response before handoff"><strong>Check the saved response</strong><p>{systems.length} system records; {Object.values(request.answers).filter(value => value.trim()).length} recorded answers. Attributed to {request.assertedBy || `your signed-in ${session.role} persona`}.</p><p>Unknowns and limitations remain visible. This does not grant access, verify technical facts or accept a deliverable.</p><button className="text-button" onClick={() => setConfirm(false)}>Return to my answers</button></section>}<button className="button secondary" disabled={disabled || dirty || (!systems.length && !Object.values(request.answers).some(value => value.trim())) || request.status === 'returned'} onClick={() => { if (!confirm) setConfirm(true); else void command('intake_submit_response', request.id, {}).then(ok => { if (ok) setConfirm(false); }); }}>{confirm ? 'Confirm handoff to coordinator' : 'Check response before handoff'}</button>{dirty && <p className="intake-help">Save your edits before reviewing the handoff.</p>}</div>
    {request.status === 'returned' && <section className="intake-next-handoff" aria-label="Who acts after this handoff"><h3>Who acts next?</h3><p><strong>Coordinator / assessment lead:</strong> route the unresolved questions and arrange access follow-up.</p><p><strong>Technical reviewer:</strong> open this request and record a factual determination with its limitations.</p><p className="intake-help">In this local demonstration, sign out and use the Technical reviewer persona to inspect that task. No notification or enterprise decision is generated automatically.</p></section>}
    {request.recordedBy && <p className="intake-help">Recorded by {request.recordedBy}. Supplied by {request.assertedBy || 'not yet attributed'}.</p>}
  </Panel>;
}

function ImportPreview({ preview, systems, command, requestId, disabled }: { preview: IntakeImport; systems: IntakeSystem[]; command: Command; requestId: string; disabled: boolean }) {
  const [choices, setChoices] = useState<Record<string, 'returned' | 'current' | 'clear'>>({});
  const conflicts = preview.changes.filter(change => change.state === 'conflict');
  return <section className="intake-import-preview" aria-label="Returned Excel change preview"><h3>Review the returned answers</h3><p>No answers have changed yet. Blank cells leave current answers unchanged. Resolve every competing edit explicitly.</p><div className="intake-changes">{preview.changes.filter(change => change.state !== 'unchanged').map(change => <article key={change.key}><h4>{systems.find(system => change.key.startsWith(`${system.id}/`))?.label || 'Question'} · {humanize(change.key.split('/').at(-1) || change.key)}</h4><span className={`badge ${change.state === 'conflict' ? 'attention' : ''}`}>{change.state === 'conflict' ? 'Competing edit—choose the answer to keep' : 'Returned change'}</span><dl><div><dt>At export</dt><dd>{change.baseline || '(blank)'}</dd></div><div><dt>Saved now</dt><dd>{change.current || '(blank)'}</dd></div><div><dt>Returned in Excel</dt><dd>{change.returned || '(blank)'}</dd></div></dl><label className="intake-field"><span>Keep which answer for {humanize(change.key.split('/').at(-1) || change.key)}?</span><select disabled={disabled} value={choices[change.key] || (change.state === 'conflict' ? '' : 'returned')} onChange={event => setChoices(current => ({ ...current, [change.key]: event.target.value as 'returned' | 'current' | 'clear' }))}>{change.state === 'conflict' && <option value="">Choose before applying</option>}<option value="returned">Use returned answer</option><option value="current">Keep saved answer</option><option value="clear">Explicitly clear this answer</option></select></label></article>)}</div>{preview.changes.every(change => change.state === 'unchanged') && <p>No answer changes were found.</p>}<button disabled={disabled || conflicts.some(change => !choices[change.key])} className="button primary" onClick={() => void command('intake_commit_import', requestId, { previewId: preview.previewId, choices: Object.fromEntries(preview.changes.filter(change => change.state !== 'unchanged').map(change => [change.key, choices[change.key] || 'returned'])) })}>Apply reviewed changes only</button></section>;
}

function ReviewResponse({ request, command, disabled }: { request: IntakeRequest; command: Command; disabled: boolean }) {
  const [determination, setDetermination] = useState(''); const [limitation, setLimitation] = useState(request.limitation || ''); const [confirm, setConfirm] = useState(false);
  const reviewedWithLimitation = ['closed_with_limitation', 'qualified'].includes(request.status);
  return <Panel title="Factual review and next handoff"><p>The technical reviewer determines whether this response is usable with a recorded limitation, or needs clarification. Reviewing testimony does not verify cryptographic behavior.</p><form onSubmit={event => { event.preventDefault(); if (!confirm) setConfirm(true); else void command('intake_review_response', request.id, { determination, limitation }).then(ok => { if (ok) setConfirm(false); }); }}><fieldset disabled={disabled || request.status !== 'returned'}><label className="intake-field"><span>Response determination</span><select value={determination} onChange={event => { setDetermination(event.target.value); setConfirm(false); }} required><option value="">Choose the next outcome</option><option value="qualified">Usable with a recorded limitation</option><option value="needs_clarification">Return for clarification</option></select></label><Field label="Limitation, consequence and next responsible function" value={limitation} onChange={value => { setLimitation(value); setConfirm(false); }} required multiline help="Explain what the response supports, what it cannot establish and who should resolve the gap." />{confirm && <div className="intake-check" role="region" aria-label="Check reviewer determination"><strong>{statusLabel(determination)}</strong><p>{limitation}</p><p>This updates the response determination—not a formal gate, enterprise acceptance or migration authorization.</p></div>}<button className="button secondary">{confirm ? 'Record this response determination' : 'Check determination before recording'}</button></fieldset></form>{reviewedWithLimitation ? <p className="intake-help">Factual review is recorded with a limitation. The coordinator follows up with the responsible function named in that determination. The limitation remains a report input—not proof that the underlying gap is resolved or the assessment is complete.</p> : request.status === 'clarification_needed' ? <p className="intake-help">Clarification was requested. The assigned contributor supplies an updated response, then hands it off again for factual review.</p> : request.status !== 'returned' && <p className="intake-help">A saved response must be handed off before factual review.</p>}{request.determination && <p>Recorded determination: <strong>{statusLabel(request.determination)}</strong>. {request.limitation}</p>}</Panel>;
}
function EvidenceReadback({ view, request }: { view: IntakeView; request: IntakeRequest }) {
  const evidence = view.evidence.filter(item => request.systemIds.includes(item.systemId));
  return <Panel title="Technical evidence—not just answers"><p>Ownership testimony can establish a reported owner. Configured, observed and independently verified cryptography need their own supporting observations.</p>{evidence.length ? evidence.map(item => <article className="intake-evidence" key={item.id}><h3>{view.systems.find(system => system.id === item.systemId)?.label || 'Assessed system'}</h3><p>Source: {view.systems.find(system => system.id === item.sourceSystemId)?.label || 'Linked evidence source'} · {item.basis}</p><dl><div><dt>Host</dt><dd>{item.hostname}</dd></div><div><dt>Key establishment</dt><dd>{item.keyExchange}</dd></div><div><dt>Authentication</dt><dd>{item.authentication}</dd></div></dl><details><summary>Evidence provenance</summary><code>{item.contentSha256}</code></details></article>) : <p className="intake-empty">No technical evidence admitted for these systems. The report must retain this limitation even when the questionnaire is returned.</p>}<p className="intake-help">This development screen does not accept arbitrary enterprise exports or enable live collection.</p></Panel>;
}
function EvidenceIntake({ view, request, disabled, canStage, stage, command, onNavigate }: {
  view: IntakeView; request: IntakeRequest; disabled: boolean; canStage: boolean;
  stage: (file: File, systemId: string, sourceSystemId: string) => Promise<boolean>; command: Command; onNavigate: Navigate;
}) {
  const [systemId, setSystemId] = useState(''); const [sourceSystemId, setSourceSystemId] = useState('');
  const [file, setFile] = useState<File>(); const [confirmId, setConfirmId] = useState('');
  const systems = view.systems.filter(system => system.requestId === request.id);
  const pending = view.pendingEvidence.filter(batch => batch.requestId === request.id);
  return <Panel title="Stage a synthetic source observation"><p>A staged file is not admitted evidence. Bind the observation to its assessed deployment and the source supplying it, then review its admission separately.</p>{request.familyId === 'traffic-termination' ? <form onSubmit={event => { event.preventDefault(); if (file) void stage(file, systemId, sourceSystemId); }}><fieldset disabled={disabled || !canStage}><div className="intake-two-fields"><label className="intake-field"><span>Assessed deployment for this file</span><select value={systemId} onChange={event => setSystemId(event.target.value)} required><option value="">Choose the subject</option>{systems.filter(system => system.systemRole !== 'source').map(system => <option value={system.id} key={system.id}>{system.label}</option>)}</select></label><label className="intake-field"><span>Evidence source supplying this file</span><select value={sourceSystemId} onChange={event => setSourceSystemId(event.target.value)} required><option value="">Choose the evidence source</option>{systems.filter(system => system.systemRole !== 'subject').map(system => <option value={system.id} key={system.id}>{system.label}</option>)}</select></label></div><label className="intake-file"><span>Qualified synthetic TLS source-page JSON · maximum 32 KiB</span><input type="file" accept=".json" required onChange={event => setFile(event.target.files?.[0])} /></label><p className="intake-help">Use only the operator-provided synthetic TLS reference fixture. Recognizing a vendor name does not qualify that vendor’s export.</p><button className="button secondary" disabled={!file || !systemId || !sourceSystemId}>Stage for review—not admit to the report</button></fieldset></form> : <p className="intake-empty">Raw file admission for this source family is not qualified in this first slice. You can still identify its systems, save responses and record the evidence limitation.</p>}
    {pending.map(batch => <article className="intake-evidence" key={batch.id}><span className="badge attention">Staged only · not report evidence</span><h3>{systems.find(system => system.id === batch.systemId)?.label || 'Assessed deployment'}</h3><p>{batch.count} candidate observation(s), supplied by {systems.find(system => system.id === batch.sourceSystemId)?.label || 'evidence source'}.</p><details><summary>Staged file reference</summary><code>{batch.contentSha256}</code></details>{view.canCoordinate && <><p className="intake-help">This view shows the subject, source, observation count and file reference only—not the observation values or reported evidence basis. Inspect the operator-provided synthetic fixture before admitting it. Admission retains its supplied basis without independently verifying cryptography.</p>{confirmId === batch.id && <div className="intake-check" role="region" aria-label="Check evidence admission"><strong>Admit this exact staged reference fixture to the assessment?</strong><p>Confirm the metadata shown here and your review of the operator-provided fixture. The supplied observations will become map and draft-report inputs; this screen does not establish that their technical content was independently verified. This does not accept a report or authorize migration.</p></div>}<button className="button secondary" disabled={disabled || !view.canAdmit} onClick={() => { if (confirmId !== batch.id) setConfirmId(batch.id); else void command('intake_admit_evidence', request.id, { batchId: batch.id }).then(ok => { if (ok) setConfirmId(''); }); }}>{confirmId === batch.id ? 'Admit this synthetic reference batch' : 'Check batch before admission'}</button></>}</article>)}
    {view.canCoordinate && !view.canAdmit && <div className="intake-empty"><strong>Evidence admission is waiting on the assessment boundary and source-access gates.</strong><p>Establish and review G00 and P1-G01 in the guided assessment. A file upload cannot bypass those decisions.</p><button disabled={disabled} className="text-button" onClick={() => onNavigate('assessments', { assessment: view.assessmentId, stage: '2', from: 'intake' })}>Review assessment prerequisites →</button></div>}
  </Panel>;
}
function ReportEffect({ view, onNavigate, disabled }: { view: IntakeView; onNavigate: Navigate; disabled: boolean }) {
  const report = view.reportPreview;
  return <section className="intake-report" aria-label="Draft report consequence"><header><p className="eyebrow">WHY THE WORK MATTERS</p><h2>What this intake contributes to the report</h2><span className="badge attention">Live draft · not an accepted deliverable</span></header><p className="intake-report-summary">{report.summary}</p><div className="intake-report-columns"><div><h3>What we can currently conclude</h3>{report.conclusions.length ? <ul>{report.conclusions.map((item, index) => <li key={index}>{item}</li>)}</ul> : <p>No supported conclusion has been recorded.</p>}</div><div><h3>Limits on that conclusion</h3>{report.limitations.length ? <ul>{report.limitations.map((item, index) => <li key={index}>{item}</li>)}</ul> : <p>No limitation is returned in this view; that does not establish enterprise completeness.</p>}</div><div><h3>Next decisions and information needed</h3>{report.nextDecisions.length ? <ul>{report.nextDecisions.map((item, index) => <li key={index}>{item}</li>)}</ul> : <p>No next decision is currently recorded.</p>}</div></div><p className="intake-help">Phase 1 explains the mapped scope and its limitations. Phase 2 can rely only on the explicitly accepted or qualified input package—not on questionnaire completion alone.</p><div className="intake-report-destination"><h3>From this preview to a reviewable document</h3><p>This display is a live input preview, not the downloadable Phase 1 deliverable. The assessment lead prepares the immutable report in Guided assessment, stage 4, after its prerequisite reviews. That screen shows unmet requirements; opening it does not bypass them.</p>{view.canCoordinate && <button disabled={disabled} className="button secondary" onClick={() => onNavigate('assessments', { assessment: view.assessmentId, stage: '4', from: 'intake' })}>Open Phase 1 report preparation →</button>}</div></section>;
}
