import type { Report } from './contracts';
import type { Analysis, Narrative, ActionRecord } from './analysis-contracts';
import { dateLabel, humanize } from './api';
import { priorityLabel } from './AnalysisWorkspace';
import { DiscoveryReportSection } from './DiscoveryReportSection';
import { WorkspaceReportSection } from './WorkspaceReportSection';

export function NarrativeReport({ report, onInspect, onReview }: {
  report: Report; onInspect: (id: string) => void; onReview: (findingId: string) => void;
}) {
  const rawNarrative = report.content.narrative as Narrative;
  const narrative = { ...rawNarrative, sections: rawNarrative.sections.map(section => ({ ...section, findingIds: section.findingIds || [] })) };
  const analysis = report.content.analysis as Analysis | undefined;
  const actions = report.content.actionRecords as ActionRecord[] | undefined;
  const manifest = report.content.manifest as { selectedPhase1?: { reportId: string; contentSha256: string; inputFingerprint: string } } | undefined;
  return <article className="narrative-report">
    <div className="report-reader-banner"><span>{report.metadata.phase === 'phase1' ? 'PHASE 1 / CURRENT-STATE ASSESSMENT' : 'PHASE 2 / RISK & MIGRATION REVIEW'}</span><strong>SYNTHETIC SNAPSHOT · DECISION RECORDED SEPARATELY</strong></div>
    <p className="report-reader-intro">Generated {dateLabel(report.metadata.createdAt)} from an immutable evidence baseline. This is a report of mock enterprise records, not a statement about a real estate.</p>
    <section className="report-executive"><p className="eyebrow">EXECUTIVE READOUT</p><h2>What matters. Why. What next.</h2><div>{narrative.executiveSummary.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></article>)}</div></section>
    <nav className="report-contents" aria-label="Report contents">{narrative.sections.map(section => <a href={`#report-section-${section.id}`} key={section.id} onClick={event => { event.preventDefault(); document.getElementById(`report-section-${section.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }}>{section.title}</a>)}<a href="#report-next-steps" onClick={event => { event.preventDefault(); document.getElementById('report-next-steps')?.scrollIntoView({ block: 'start' }); }}>Decisions & next steps</a></nav>
    {narrative.sections.map((section, index) => <section className="report-narrative-section" id={`report-section-${section.id}`} key={section.id}><p className="eyebrow">SECTION {String(index + 1).padStart(2, '0')}</p><h2>{section.title}</h2><p className="report-section-summary">{section.summary}</p>{section.paragraphs.map((paragraph, item) => <p key={item}>{paragraph}</p>)}{section.findingIds.length > 0 && <div className="report-evidence-examples">{section.findingIds.map(id => analysis?.findings.find(finding => finding.id === id)).filter(finding => !!finding).map(finding => <article key={finding.id}><span className={`priority-signal priority-${finding.priority}`}>{priorityLabel(finding.priority)}</span><h3>{finding.title}</h3><p>{finding.observation}</p><dl><div><dt>Business / technical implication</dt><dd>{finding.implication}</dd></div><div><dt>Recommended treatment or investigation</dt><dd>{finding.recommendation}</dd></div><div><dt>Owner</dt><dd>{finding.owner || 'Not identified'}</dd></div></dl><div className="report-evidence-links"><button className="text-button" onClick={() => onInspect(finding.subjectId)}>Inspect {finding.subjectLabel} ↗</button><button className="text-button" onClick={() => onReview(finding.id)}>Open finding review →</button><span>{finding.observationRefs.length} evidence references</span></div></article>)}</div>}</section>)}
    <section className="report-narrative-section" id="report-next-steps"><p className="eyebrow">ACCOUNTABILITY & DELIVERY</p><h2>Decisions and next steps</h2><div className="report-next-steps">{narrative.nextSteps.map((step, index) => <article key={`${step.title}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{step.title}</h3><dl><div><dt>Accountable owner</dt><dd>{step.owner}</dd></div><div><dt>Action</dt><dd>{step.action}</dd></div><div><dt>Decision required</dt><dd>{step.decisionRequired}</dd></div>{step.dueAt && <div><dt>Required follow-up</dt><dd>{dateLabel(step.dueAt)}</dd></div>}<div><dt>If unresolved</dt><dd>{step.consequence}</dd></div></dl></div></article>)}</div></section>
    {manifest?.selectedPhase1 && <section className="report-narrative-section"><p className="eyebrow">EXPLICIT PHASE 1 HANDOFF</p><h2>The input this analysis relies on</h2><p>This report uses the selected Phase 1 snapshot below. Later reports do not silently replace it.</p><dl><div><dt>Phase 1 report</dt><dd><code>{manifest.selectedPhase1.reportId}</code></dd></div><div><dt>Content SHA-256</dt><dd><code>{manifest.selectedPhase1.contentSha256}</code></dd></div></dl></section>}
    <WorkspaceReportSection content={report.content} />
    <DiscoveryReportSection content={report.content} onInspect={onInspect} />
    {narrative.questions.length > 0 && <section className="report-narrative-section"><p className="eyebrow">FOR ACCOUNTABLE REVIEWERS</p><h2>Questions to resolve</h2><ul className="report-question-list">{narrative.questions.map(question => <li key={question}>{question}</li>)}</ul></section>}
    <section className="report-narrative-section report-caveats"><p className="eyebrow">BOUNDARIES & LIMITATIONS</p><h2>What this report does not establish</h2><ul>{narrative.caveats.map(caveat => <li key={caveat}>{caveat}</li>)}</ul></section>
    <details className="report-technical-appendix"><summary>Evidence appendix, method and immutable report provenance</summary><dl><div><dt>Report ID</dt><dd><code>{report.metadata.id}</code></dd></div><div><dt>Baseline ID</dt><dd><code>{report.metadata.baselineId}</code></dd></div><div><dt>Input SHA-256</dt><dd><code>{report.metadata.inputSha256}</code></dd></div><div><dt>Content SHA-256</dt><dd><code>{report.metadata.contentSha256}</code></dd></div><div><dt>Worker run</dt><dd><code>{report.metadata.workerRunId}</code></dd></div>{analysis && <><div><dt>Analysis method</dt><dd>{analysis.method.id} · {analysis.method.version} · {humanize(analysis.method.status)}</dd></div><div><dt>Full finding set</dt><dd>{analysis.findings.length} findings; download the complete HTML or JSON artifact for all supporting records.</dd></div></>}{!!report.content.phase1ReportId && <div><dt>Phase 1 input report</dt><dd><code>{String(report.content.phase1ReportId)}</code></dd></div>}{!!report.content.phase1ReportSha256 && <div><dt>Phase 1 input SHA-256</dt><dd><code>{String(report.content.phase1ReportSha256)}</code></dd></div>}{actions && <div><dt>Review state at generation</dt><dd>{actions.length} persisted local review records frozen in this report. Later reviews do not rewrite this snapshot.</dd></div>}</dl></details>
  </article>;
}
