#!/usr/bin/env python3
"""Create-only, offline fictional input for the complete browser walkthrough.

The distributed workbook definitions and their read-only cells remain intact.
Only response cells are populated using the existing validated template filler.
Source records are generated by the existing closed family models and actually
consumed by their normalizers. Business statements are separate attributed
scenario inputs, never injected into technical observations or report outputs.
This prepares files; it creates no assessments, decisions, reports or videos.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
import sys
from xml.etree import ElementTree as ET
from zipfile import ZIP_DEFLATED, ZipFile
from io import BytesIO

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.build_pqc_response_to_report_fixtures import edit, workbook, NS
from tools.pqc_reference.synthetic_estate import generate_estate, KIND_TO_FAMILY
from workers.pqc.assessment_sources import normalize_page
from workers.pqc.extended_sources import extended_page_digest

FIXTURES = ROOT / "tests/fixtures/pqc-operational-return-v1"
CATALOG = ROOT / "integrations/pqc/reference_assessment/catalog.v1.json"
CROSSWALK = ROOT / "integrations/pqc/reference_assessment/intake-crosswalk.v1.json"
AS_OF = "2026-09-16T12:00:00Z"
NORMALIZER = "workers.pqc.assessment_sources.normalize_page.v1"
FICTION = "Northstar Services — fictional synthetic enterprise"


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False).encode("ascii")


def sha(data):
    return hashlib.sha256(data).hexdigest()


def encoded(value):
    return (json.dumps(value, indent=2, ensure_ascii=True, allow_nan=False) + "\n").encode("ascii")


def new(path, data):
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    with path.open("xb") as handle:
        handle.write(data)
    path.chmod(0o600)


# Each item is deliberately business testimony, not a scanner-derived fact.
# Priorities are assessment attention categories, not approved risk scores.
BUSINESS = {
    "area-01": dict(service="Client portal and records service", owner="Synthetic service ownership function",
        information="Client service relationships and confidential account correspondence",
        lifetime="Correspondence confidentiality: seven years after creation; service-ownership accuracy: current operating cycle.",
        impact="Incorrect ownership or application links can send migration work to the wrong team and omit a critical records dependency.",
        scenario="An incomplete application-to-service map may cause a later cryptographic change to miss a relying service or its accountable reviewer.",
        finding="Context records establish a bounded service/application route, not a complete enterprise population or all relying parties.",
        recommendation="Confirm the portal service map and authoritative owner; reconcile orphaned references before selecting a migration cohort.",
        decision="Service owner to confirm the bounded portal cohort and unresolved relationships.", priority="prioritize_review",
        compatibility="Application identities from different repositories need explicit reconciliation.", vendor="CMDB/API interface is a closed synthetic dialect, not ServiceNow qualification.",
        operational="Source-owner review capacity and a maintained population register are prerequisites."),
    "area-02": dict(service="Portal trust and credential service", owner="Synthetic PKI and trust function",
        information="Portal authentication trust, certificate issuance records and signing-key custody metadata",
        lifetime="Relying-party trust is required throughout certificate validity and archival verification; record authenticity is required for seven years.",
        impact="An incompatible certificate or trust change could prevent legitimate portal connections or break verification of retained records.",
        scenario="Classical authentication dependencies remain even where hybrid key establishment is configured; relying-party compatibility must be understood separately.",
        finding="The modeled certificate/authority/HSM records describe classical signing and custody dependencies. Key exchange and authentication are distinct.",
        recommendation="Inventory relying-party trust, signing mechanisms and lifecycle dependencies; obtain exact-version capability evidence before proposing a trust change.",
        decision="PKI lead to approve the relying-party compatibility investigation, not certificate replacement.", priority="prioritize_review",
        compatibility="Older verifiers may not accept changed signatures or chains.", vendor="HSM/CA capability statements are synthetic assertions; installed firmware and licensing remain unqualified.",
        operational="Key ceremonies and trust distribution require separate controlled plans; no private keys are exported."),
    "area-03": dict(service="Client portal ingress", owner="Synthetic network platform function",
        information="Portal session contents and confidential customer correspondence",
        lifetime="Confidentiality of retained correspondence: seven years; interactive session integrity: the session plus retained audit use.",
        impact="Captured traffic may retain sensitive information beyond the connection. A poorly coordinated change could make the portal unavailable to older clients.",
        scenario="Gateway-east has configured hybrid key exchange but a modeled classical observation; gateway-west remains classical. This does not establish a malicious downgrade.",
        finding="Two of three declared ingress deployments have supporting records. East configuration and modeled observation conflict; west is classical; edge-third is blocked and unexamined.",
        recommendation="Reconcile east observation date/client scope, inventory the client cohort, and resolve the edge source route before proposing a bounded compatibility pilot.",
        decision="Network lead to commission a scoped verification plan and identify the edge source route.", priority="prioritize_review",
        compatibility="Client libraries, TLS termination, internal mesh and proxies must be considered independently.", vendor="F5 BIG-IP and NGINX are recognition examples; no product-specific integration or supported configuration is proved.",
        operational="No live endpoint is contacted. Unknown handling authority blocks the edge capture, not documentation research."),
    "area-04": dict(service="Privileged administration", owner="Synthetic infrastructure access function",
        information="Administrative commands, machine credentials and remote-access sessions",
        lifetime="Session confidentiality: one year for operational investigations; privileged audit authenticity: seven years.",
        impact="Loss of administrative access during a change could delay incident recovery; compromised session confidentiality could disclose privileged operations.",
        scenario="Classical SSH/VPN negotiation or incompatible client/server combinations may preserve quantum-vulnerable establishment or disrupt administration.",
        finding="Modeled machine-access records identify transport and peer-authentication dependencies; they do not prove the complete bastion or remote-user population.",
        recommendation="Build separate SSH and VPN client/server cohorts, test negotiated behavior and access preservation, and specify recovery before a later pilot.",
        decision="Access owner to nominate a disposable compatibility cohort and recovery reviewer.", priority="planned_review",
        compatibility="Key exchange, host/user signatures and VPN peer authentication require separate compatibility checks.", vendor="Operating-system and gateway versions are not product-qualified by reference dialects.",
        operational="Production SSH services and accounts are outside the demonstration; emergency access must remain independently available."),
    "area-05": dict(service="Software release and artifact verification", owner="Synthetic software delivery function",
        information="Released application artifacts, build provenance and software signatures",
        lifetime="Artifact authenticity: ten years for retained releases and recovery images; build metadata: seven years.",
        impact="Unverified or incompatible signing changes could prevent trusted releases or restoration from known software versions.",
        scenario="A dependency upgrade alone may leave application behavior and legacy verifiers unchanged; classical release signatures can persist beyond the build date.",
        finding="Source, dependency and signing metadata identify candidate implementations and verifier dependencies, not the cryptography actually executed in every deployed workload.",
        recommendation="Trace one release from source and library to deployed artifact; qualify signer/verifier rollout and legacy artifact handling with application-level tests.",
        decision="Engineering lead to select the release/verifier cohort and approve a synthetic build experiment.", priority="prioritize_review",
        compatibility="Existing installers, artifact stores and offline recovery verifiers may require staged support.", vendor="Scanner findings and library capability are not proof of deployed use or compatible PQC support.",
        operational="Release freeze windows and reproducible build ownership constrain subsequent migration planning."),
    "area-06": dict(service="Cloud identity and managed key consumers", owner="Synthetic cloud security function",
        information="Federation assertions, credential references and envelope-encryption key-consumer relationships",
        lifetime="Federation assertions: short-lived sessions; encrypted records: seven years; key-recovery ability: the complete retention period.",
        impact="Incorrect key-consumer mapping or trust changes may deny access to workloads or make retained information unreadable.",
        scenario="Replacing a key mechanism without understanding consumers, token verifiers and custody constraints can create outages even when the algorithm is available.",
        finding="Cloud, KMS, secrets and IAM records provide metadata and dependency assertions. No secret values or private keys are collected.",
        recommendation="Map key and identity consumers, distinguish rewrapping from re-encryption, and seek exact-service/edition support before designing change.",
        decision="Cloud security to confirm the selected consumer graph and acceptable recovery boundary.", priority="planned_review",
        compatibility="Issuer tokens, client SDKs, key formats and regional services can have different capabilities.", vendor="Service control-plane metadata is not proof of every workload or a service's PQC support.",
        operational="Nonexportable keys stay in custody; any later rewrap or policy action requires separate authorization."),
    "area-07": dict(service="Records archive and recovery", owner="Synthetic records and recovery function",
        information="Confidential statements, database records, backups and archive indexes",
        lifetime="Archive confidentiality and restoration requirement: fifteen years; the example is a fictional information-owner statement, not a regulatory rule.",
        impact="An inappropriate key change could leave long-lived archives exposed or prevent restoration when their business use is most important.",
        scenario="Long-lived protected information and classical key-wrapping or transport dependencies require separate analysis from the symmetric data cipher.",
        finding="Database/storage/governance records establish selected encryption and retention assertions; no complete backup restore or data classification is proved.",
        recommendation="Prioritize long-lived archive dependency review, distinguish data encryption from wrapping/transport, and define restoration acceptance criteria.",
        decision="Records owner to validate retention assumptions; recovery lead to define an isolated restore test.", priority="prioritize_review",
        compatibility="Historic backup formats and key versions may require long-lived decryption support.", vendor="Storage/database capability and vendor roadmap claims still require exact-version validation.",
        operational="Do not rewrite archives or destroy old keys as part of assessment; recovery evidence precedes future change."),
    "area-08": dict(service="Distributed workforce and document exchange", owner="Synthetic endpoint and communications function",
        information="Signed documents, endpoint update trust and workforce communications",
        lifetime="Document authenticity: ten years; firmware/update trust: device lifetime, modeled as eight years; email confidentiality varies and remains partly unresolved.",
        impact="A signature or trust change that excludes older devices can interrupt workforce access or leave unsupported endpoints outside a migration wave.",
        scenario="Long-lived endpoint and embedded verifiers may retain classical dependencies after centrally managed services add new algorithms.",
        finding="Modeled fleet and communications records describe selected versions and trust dependencies; the fleet denominator and some communication lifetimes remain unknown.",
        recommendation="Segment the fleet by verifier and update path; identify unsupported device cohorts and clarify email/document retention before prioritizing changes.",
        decision="Endpoint owner to confirm the fleet population and unsupported cohorts; information owner to resolve communication lifetime.", priority="planned_review",
        compatibility="Offline devices, embedded firmware and external document recipients may not update together.", vendor="Supported upgrade paths and end-of-support commitments must be evidenced by selected suppliers.",
        operational="Staged rollout, user disruption and recovery media matter; none is authorized by this report."),
    "area-09": dict(service="Settlement and specialist transaction processing", owner="Synthetic specialist platform function",
        information="Transaction messages, settlement authenticity and specialist key-custody references",
        lifetime="Transaction and settlement authenticity: ten years; message confidentiality: seven years in this fictional scenario.",
        impact="An incompatible specialist change could interrupt settlement or invalidate verification of retained transaction records.",
        scenario="Specialized protocols, hardware mechanisms and mainframe dependencies may prevent straightforward substitution and require vendor or ceremony changes.",
        finding="Modeled transaction/mainframe metadata provides a bounded specialist route. It does not establish regulatory compliance, device certification or live throughput.",
        recommendation="Request specialist protocol/mechanism constraints and supplier evidence; separate preparation and verification automation from manual ceremony steps.",
        decision="Specialist service owner to confirm required experts and supplier qualification route.", priority="planned_review",
        compatibility="Peer institutions, message formats and hardware-supported mechanisms must be coordinated.", vendor="No payment HSM, mainframe edition or specialized protocol is qualified by this demonstration.",
        operational="Settlement windows and dual-control ceremonies remain manual/human-authorized boundaries."),
    "area-10": dict(service="Assessment governance and vendor assurance", owner="Synthetic risk coordination function",
        information="Assessment decisions, exception rationale and supplier commitments",
        lifetime="Decision and exception traceability: seven years; vendor statements remain current only for their stated product/version and review date.",
        impact="Untraceable exceptions or stale vendor promises may lead leadership to rely on unsupported migration readiness or lose the rationale for deferred work.",
        scenario="A ticket marked closed or a vendor roadmap statement may be mistaken for independently verified migration completion.",
        finding="Governance records identify policy/exception and supplier routes. Missing policy documentation does not establish that no policy exists.",
        recommendation="Bind exceptions and vendor commitments to exact scope, version, decision owner and review date; distinguish proposed standards from adopted requirements.",
        decision="Risk coordination to obtain adoption authority and dated supplier evidence without treating roadmap promises as deployment proof.", priority="planned_review",
        compatibility="Canonical cases and evidence must survive changes of ticketing provider.", vendor="A roadmap is an attributed future claim, not an interoperable installed capability.",
        operational="Receipt, technical review, deliverable acceptance, risk acceptance and execution authorization remain separate decisions."),
}

FAMILY_ACTIONS = {
    "cmdb":"Confirm the selected application/service identity and owner against the authoritative context register; retain unresolved references.",
    "application-portfolio":"Reconcile the selected portfolio lifecycle and owner route with the application record; do not substitute portfolio membership for deployment proof.",
    "certificate-lifecycle":"Identify relying parties and deployment of the selected certificate before evaluating replacement and verifier compatibility.",
    "certificate-authorities":"Review the selected issuer, trust-distribution route and relying-party population; define the evidence needed for a future trust-chain change.",
    "hsm":"Confirm exact firmware, licensed mechanisms and actual consumers for the selected custody record; do not extract key material or infer use from capability.",
    "traffic-termination":"Reconcile east configuration and observation date/client scope, review the west client cohort, and establish the blocked edge source route before a compatibility pilot.",
    "api-and-mesh":"Verify the selected mesh route and mutual-TLS client/peer cohort; keep its classical transport use separate from edge-gateway findings.",
    "network-telemetry":"Confirm the selected flow's sensor, collection date and client population; do not generalize its hybrid observation to all traffic or authentication.",
    "ssh":"Define the selected SSH client/server cohort and test key exchange separately from host signatures, preserving an independently tested recovery path.",
    "vpn":"Confirm the selected IKE peer cohort and gateway versions; assess tunnel establishment and peer authentication before a separately authorized change.",
    "source-build":"Trace the selected source revision and build to the released application artifact; identify tests proving changed signer behavior rather than only a dependency bump.",
    "dependency-analysis":"Corroborate the selected cryptographic call site in a built and deployed artifact; distinguish a declared library capability from executed use.",
    "software-signing":"Identify the selected artifact's verifier cohort and legacy verification period; prepare staged signer/verifier compatibility tests.",
    "cloud-inventory":"Confirm the selected runtime deployment and referenced key-service consumer relationship; inventory metadata alone does not prove workload cryptography.",
    "kms":"Map the selected key's consumers and wrapping role; assess rewrapping versus re-encryption and recovery without exporting private keys.",
    "secrets":"Confirm the selected credential metadata's consumer and issuer routes; review rotation and signature dependencies without collecting secret values.",
    "iam":"Identify the selected assertion issuer and token verifier cohort; evaluate algorithm and trust changes independently of token lifetime.",
    "databases":"Retain the selected AES-256 at-rest fact; investigate separate transport, wrapping and client dependencies rather than treating the symmetric cipher as a PQC migration failure.",
    "storage-backup":"Confirm the selected archive's retained key versions and restoration route; define an isolated restore test before any later key or format change.",
    "data-governance":"Have the information owner reconcile the selected classification/lifetime declaration with attributed business retention needs and its proposed-policy status.",
    "communications":"Review the selected DNSSEC signer and consumer cohort; obtain separate evidence before drawing email or document-signing conclusions.",
    "endpoints":"Confirm the selected update verifier, trust profile and device cohort; identify unsupported endpoints before planning a staged rollout.",
    "embedded-ot":"Confirm the selected firmware verifier, update mechanism and maintenance window; investigate the difference between recorded trust horizon and business device lifetime.",
    "specialized-transactions":"Obtain specialist review of the selected transaction-signing and dual-control route; no ceremony or change is authorized by this assessment.",
    "mainframe":"Confirm the selected mainframe mechanism and key-store dependency with the specialist platform owner; qualify exact versions before designing automation.",
    "policy-exceptions":"Review the selected proposed policy and exception reference with the adoption authority; a work-item status cannot establish authorization or verified migration.",
    "vendor-assurance":"Refresh the stale selected supplier statement for the exact product/version and request independent validation evidence; a roadmap capability is not deployed use.",
}


def expand_row_heights(data, response_cells):
    """Preserve styles/layout and reserve readable height for filled response cells.

    This is a focused extension of the existing XML template filler, explicitly
    authorized for these copies; no new workbook library is introduced.
    """
    cells, paths, parts = workbook(data)
    for sheet, addresses in cells.items():
        if sheet not in {"Start here", "Five questions", "Products & deployments", "Version & return record"}:
            continue
        root = ET.fromstring(parts[paths[sheet]])
        for row in root.find(f"{{{NS}}}sheetData"):
            row_no = int(row.get("r"))
            texts = [text for address, text in addresses.items() if address in response_cells.get(sheet, {}) and int(''.join(filter(str.isdigit, address))) == row_no]
            if not texts:
                continue
            # Product columns are narrower; statement rows span merged columns.
            chars = 27 if sheet == "Products & deployments" else 92
            lines = max(sum(max(1, (len(line) + chars - 1) // chars) for line in text.splitlines()) for text in texts)
            minimum = 18 * lines + 12
            if minimum > float(row.get("ht", "15")):
                row.set("ht", str(min(300, minimum)))
                row.set("customHeight", "1")
        parts[paths[sheet]] = ET.tostring(root, encoding="utf-8", xml_declaration=True)
    output = BytesIO()
    with ZipFile(output, "w", ZIP_DEFLATED) as z:
        for name, content in parts.items():
            z.writestr(name, content)
    return output.getvalue()


def mark_synthetic_print_copy(data):
    """Mark every printed page without altering immutable questionnaire cells."""
    _, paths, parts = workbook(data)
    for sheet, path in paths.items():
        root = ET.fromstring(parts[path])
        margins = root.find(f"{{{NS}}}pageMargins")
        if margins is not None:
            margins.set("top", "0.65")
            margins.set("bottom", "0.65")
            margins.set("header", "0.2")
            margins.set("footer", "0.2")
        header_footer = root.find(f"{{{NS}}}headerFooter")
        if header_footer is None:
            header_footer = ET.SubElement(root, f"{{{NS}}}headerFooter")
        # Populate and enable every variant. LibreOffice can otherwise omit the
        # odd-only header on inherited first/even page styles despite false flags.
        header_footer.set("differentFirst", "true")
        header_footer.set("differentOddEven", "true")
        for child in list(header_footer):
            header_footer.remove(child)
        for variant in ("odd", "even", "first"):
            ET.SubElement(header_footer, f"{{{NS}}}{variant}Header").text = '&C&"Calibri,Bold"&11&K9C1C1CSYNTHETIC TRAINING COPY — DO NOT EMAIL'
            ET.SubElement(header_footer, f"{{{NS}}}{variant}Footer").text = '&L&"Calibri,Regular"&9Fictional training inputs only&C&"Calibri,Bold"&9DO NOT EMAIL&R&"Calibri,Regular"&9Page &P of &N'
        parts[path] = ET.tostring(root, encoding="utf-8", xml_declaration=True)
    output = BytesIO()
    with ZipFile(output, "w", ZIP_DEFLATED) as archive:
        for name, content in parts.items():
            archive.writestr(name, content)
    return output.getvalue()


def workspace_purpose(uses):
    """Map a primary raw use to the existing coarse workspace categories.

    Preserve all original purposes in technicalBasis. Do not invent a signing
    purpose for generic custodians or application-signature records whose
    business operation is unspecified by the closed fixture.
    """
    if not uses:
        return "context"
    use = uses[0]
    purpose, role = use["purpose"], use.get("role", "")
    if purpose in {"key_establishment", "authentication"}:
        return purpose
    if purpose in {"data_encryption", "key_wrapping"}:
        return "data_protection"
    if purpose == "digital_signature":
        if role in {"code_signer", "firmware_verifier"}:
            return "software_signing"
        if role in {"certificate_issuer", "peer_authentication", "token_issuer", "credential_issuer", "dnssec_signer"}:
            return "authentication"
    return "context"


def make_bundle(page, records, *, suffix, observed_at, label):
    raw = copy.deepcopy(page["payload"])
    raw["records"] = copy.deepcopy(records)
    if "content_sha256" in raw:
        raw["content_sha256"] = extended_page_digest(raw)
    normalized = normalize_page(page["kind"], raw, tenant_id="synthetic-enterprise", source_instance_id=page["source"], observed_at=observed_at)
    family = KIND_TO_FAMILY.get(page["kind"], page["kind"])
    bundle = dict(schemaVersion="pqc.workspace.registered-source-bundle.v1", synthetic=True,
        tenantId="synthetic-enterprise", familyId=family, sourceInstanceId=page["source"], sourceLabel=label,
        observedAt=observed_at, collectedAt=AS_OF, normalizerVersion=NORMALIZER,
        rawSourceSha256=sha(canonical(raw)), rawSource=raw, records=normalized)
    data = encoded(bundle)
    assert len(data) <= 32768 and 0 < len(normalized) <= 32
    return f"bundles/{family}-{suffix}.json", bundle


def technical_position(family, name, bundle):
    """Produce a bounded descriptive position only from that family's record.

    This is scenario-authoring input for review, not a pre-admitted finding.
    Business hypotheses are separately qualified rather than disguised as
    observations. Cross-family links still require the application's review.
    """
    observation=bundle["records"][0]; facts=observation["facts"]
    uses=facts.get("cryptographic_uses",[])
    if family=="certificate-lifecycle":
        uses=[dict(purpose="authentication",role="certificate signature",algorithm=facts.get("signature_algorithm"),basis=observation["assertion_kind"])]
    elif family=="traffic-termination":
        uses=[dict(purpose="key_establishment",role="transport key exchange",algorithm=facts.get("key_exchange_group"),basis=observation["assertion_kind"]),
            dict(purpose="authentication",role="certificate signature",algorithm=facts.get("certificate_signature_algorithm"),basis=observation["assertion_kind"])]
    selected=[]
    for key,value in facts.items():
        if key in {"native_id","name"} or key.endswith("_ref") or isinstance(value,(dict,list)) or value is None or key.endswith(("_present","_basis","_key_bits","_protocol_version","_trust_until","_algorithm")):
            continue
        selected.append((key,value))
        if len(selected)==3:break
    readable="; ".join(f"{key.replace('_',' ')} = {str(value).lower() if isinstance(value,bool) else value}" for key,value in selected)
    use_text="; ".join(f"{u['role'].replace('_',' ')}: {u.get('algorithm') or 'unknown algorithm'} ({u.get('basis') or 'unknown basis'})" for u in uses)
    finding=f"Selected {name.lower()} record {facts['native_id']} reports {readable or 'context references only'}."
    finding += " Modeled cryptographic uses: " + use_text + "." if uses else " It contains no asserted cryptographic-use observation; it supplies context, not a direct algorithm-exposure finding."
    finding += " These are closed synthetic record assertions, not live enterprise verification."
    if family=="traffic-termination":
        finding=BUSINESS["area-03"]["finding"]+" The supporting rows separately retain key-exchange and certificate-authentication algorithms."
        scenario=BUSINESS["area-03"]["scenario"]
    elif not uses:
        scenario=f"Incorrect, stale or incomplete {name.lower()} context can misdirect cohort selection or create unsupported readiness claims. This source alone establishes no cryptographic algorithm exposure."
    elif all(u["purpose"]=="data_encryption" and (u.get("algorithm") or "").startswith("AES-256") for u in uses):
        scenario=f"The selected {name.lower()} record describes AES-256 data encryption. That fact alone does not establish quantum-vulnerable data encryption; investigate the separate key-wrapping, transport and recovery dependencies before drawing a stronger conclusion."
    elif any("MLKEM" in (u.get("algorithm") or "") or "ML-KEM" in (u.get("algorithm") or "") for u in uses):
        scenario=f"Hybrid establishment appears in the selected {name.lower()} reference record. Its limited observation scope does not establish PQC authentication, all-client interoperability or deployment-wide readiness."
    else:
        scenario=f"The selected {name.lower()} source describes {use_text}. If the relying business service depends on these uses over the stated lifetime, separately investigate compatibility, exposure and recovery; no whole-service PQC-readiness claim follows."
    return dict(conclusion=finding,scenario=scenario,sourceFacts=[dict(field=k,value=v) for k,v in selected],uses=uses)


def build(output: Path, *, with_forms=True):
    output = output.absolute()
    if any(p.is_symlink() for p in (output, *output.parents)):
        raise ValueError("symlink_output_denied")
    if output.exists():
        raise ValueError("create_only_output_exists")
    catalog = json.loads(CATALOG.read_text())
    definitions = json.loads((FIXTURES / "catalog.json").read_text())
    crosswalk = json.loads(CROSSWALK.read_text())
    estate = generate_estate(seed=7, application_count=12, source_scope="all")
    families = {row["id"]: row for row in catalog["source_families"]}
    forms = {row["familyId"]: row for row in definitions["forms"]}
    assert len(forms) == len(families) == 27 and set(forms) == set(families)
    assert all(forms[f]["domainId"] == families[f]["area_ref"] for f in forms)
    output.mkdir(mode=0o700, parents=True)
    files = {}
    def store(name, value, raw=False):
        data = value if raw else encoded(value)
        new(output / name, data)
        files[name] = dict(name=name, sha256=sha(data), bytes=len(data))
    registry = []
    bundle_refs = {f: [] for f in families}
    selected_bundles={}
    pages = {KIND_TO_FAMILY.get(p["kind"], p["kind"]): p for p in reversed(estate["pages"])}
    for family, profile in families.items():
        page = pages[family]
        row = copy.deepcopy(page["payload"]["records"][0])
        observed = "2026-09-14T10:00:00Z"
        if family == "vendor-assurance":
            observed = "2026-07-01T10:00:00Z"
        if family == "cmdb":
            row.update(name="Synthetic Client Portal", owner_id="synthetic-service-team", business_service_id="service-001", criticality="high", confidentiality_until="2033-09-16")
        if family == "traffic-termination":
            row.update(hostname="portal-east.example", key_exchange_group="X25519MLKEM768", protocol="TLSv1.3", evidence_basis="configured")
        samples = [("selected", row, observed, "gateway-east" if family == "traffic-termination" else f"{family}-selected")]
        if family == "traffic-termination":
            observed_row = copy.deepcopy(row); observed_row.update(evidence_basis="observed", key_exchange_group="X25519")
            west = copy.deepcopy(page["payload"]["records"][1]); west.update(hostname="portal-west.example", key_exchange_group="X25519", protocol="TLSv1.3")
            samples += [("observed-conflict", observed_row, "2026-09-13T10:00:00Z", "gateway-east"), ("west", west, observed, "gateway-west")]
        for suffix, record, date, deployment in samples:
            name, bundle = make_bundle(page, [record], suffix=suffix, observed_at=date, label=f"Synthetic {profile['name']} — {deployment}")
            if suffix=="selected":selected_bundles[family]=bundle
            store(name, bundle)
            store(name.replace("bundles/", "raw/"), bundle["rawSource"])
            registry.append({key: bundle[key] for key in ("familyId", "sourceInstanceId", "normalizerVersion", "rawSourceSha256")} | {"sha256": files[name]["sha256"]})
            bundle_refs[family].append(dict(path=name, deployment=deployment, nativeId=record["id"],
                basis=record["evidence_basis"], technicalDetermination="conflict" if family == "traffic-termination" and deployment == "gateway-east" else "supports_claim"))
    store("bundle-registry.json", dict(schemaVersion="pqc.workspace.synthetic-bundle-registry.v1", synthetic=True, entries=registry))
    domain_rows = []
    for area in catalog["estate_areas"]:
        b = BUSINESS[area["id"]]
        domain_rows.append(dict(domainId=area["id"], domainName=area["name"], synthetic=True,
            statementId=f"synthetic-business-{area['id']}", assertedBy=b["owner"], recordedBy="Scenario author (not a business approval)",
            statementDate="2026-09-16", evidenceBasis="attributed_synthetic_business_statement", reviewStatus="pending_simulated_business_review", **b))
    store("business-context.json", dict(schemaVersion="pqc.walkthrough.business-context.v1", synthetic=True, enterprise=FICTION, domains=domain_rows))
    responses, cases = [], []
    for family, spec in sorted(forms.items()):
        profile = families[family]; area = profile["area_ref"]; b = BUSINESS[area]
        example = profile["recognition_examples"][0]
        deployment = f"{family}-selected"
        products = [dict(product=example, deployment=deployment, environment="synthetic_lab", applicationService="Synthetic Client Portal / " + b["service"],
            owner=b["owner"], dependencies="app-001; selected reference only", reference=f"synthetic:{family}:selected", notes="Fictional example; exact product/edition/API not qualified")]
        if family == "traffic-termination":
            products = [dict(product=p, deployment=d, environment=e, applicationService="Synthetic Client Portal", owner=o,
                dependencies="app-001", reference=r, notes=n) for p,d,e,o,r,n in [
                ("F5 BIG-IP", "gateway-east", "synthetic-test-east", b["owner"], "synthetic:configuration-east", "First retained reference; no installed-product claim"),
                ("F5 BIG-IP", "gateway-west", "synthetic-test-west", b["owner"], "synthetic:configuration-west", "Separate deployment; not the east gateway"),
                ("NGINX", "edge-third", "synthetic-test-edge", "Unknown", "", "Blocked supporting-information route; do not infer cryptography"),
                ("F5 BIG-IP", "gateway-east", "synthetic-test-east", b["owner"], "synthetic:second-reference-east", "Suspected duplicate; explicit coordinator decision required")]]
        values = {
            "DQ-01": ("Answered", "; ".join(dict.fromkeys(p["product"] for p in products)) + ". Fictional recognition examples; see product/deployment rows.", ""),
            "DQ-02": ("Referral", b["owner"] + " can route the request; named accountability still needs confirmation.", b["owner"]),
            "DQ-03": ("Answered", "Examine the selected closed synthetic source record(s). No sensitive upload or live collection is requested.", ""),
            "DQ-04": ("Answered", "Synthetic Client Portal; " + b["service"] + ". This is a selected cohort, not enterprise enumeration.", ""),
            "DQ-05": ("Unknown", "The respondent cannot confirm every applicable policy. Missing documentation is not evidence of absent policy.", "Coordinator to confirm the handling authority"),
        }
        if family == "traffic-termination":
            values["DQ-03"] = ("Blocked", "East/west modeled records available; edge-third supporting-information route is blocked pending handling clarification.", "Synthetic partner service function")
            values["DQ-04"] = ("Unanswered", "", "")
        if family == "vendor-assurance":
            values["DQ-03"] = ("Disputed", "The supplier capability statement is stale; it is not exact-version qualification or proof of deployment.", "Synthetic supplier relationship function")
        respondent = dict(intendedTeam=b["owner"], respondent="Synthetic respondent / " + b["owner"], owner="Proposed: " + b["owner"],
            responseDate="2026-09-16", scope="Synthetic practice only — DO NOT EMAIL. Fictional Client Portal dependency cohort; not enterprise-wide discovery", jiraIssueKey="")
        response = dict(familyId=family, questionnaireId=spec["questionnaireId"], domainId=area, sourceTemplateVersion=spec["templateVersion"],
            sourceTemplateSha256=spec["templateSha256"], blankSha256=spec["blankSha256"], respondent=respondent,
            questions=[dict(id=q["id"], prompt=q["prompt"], status=values[q["id"]][0], text=values[q["id"]][1], reference="synthetic:" + family,
                attribution=respondent["respondent"], followUp=values[q["id"]][2]) for q in spec["questions"]], products=products)
        responses.append(response)
        mapped = [dict(questionnaireId=r["id"], relationship=m["relationship"], rationale=m["rationale"]) for r in crosswalk["rfi_profiles"] for m in r["mappings"] if m["family_id"] == family]
        position=technical_position(family,profile["name"],selected_bundles[family])
        purpose="; ".join(dict.fromkeys(use["purpose"] for use in position["uses"])) or "context"
        assert len(purpose) <= 40, "explicit_supported_purpose_length_required"
        case = dict(familyId=family, domainId=area, domainName=next(a["name"] for a in catalog["estate_areas"] if a["id"] == area),
            name=profile["name"], questionnaireId=spec["questionnaireId"], formPath=f"forms/{area}/{family}-synthetic-completed.xlsx",
            products=products, bundles=bundle_refs[family], detailedQuestionnaireCrosswalk=mapped,
            phase1Conclusion=position["conclusion"],technicalBasis=position,cryptographicPurpose=purpose,
            limitation="Selected reference records only; enterprise population and exact-product compatibility unproved. " + ("Edge-third remains blocked; east observations conflict." if family == "traffic-termination" else "No independent enterprise runtime verification.") + " Source-record lifetimes and attributed business lifetimes require scoped reconciliation; neither silently overrides the other.",
            businessStatementId=f"synthetic-business-{area}", analysis=dict(scenario=position["scenario"], businessImpact=b["impact"], recommendation=b["recommendation"],
                priority=b["priority"], rationale="Prioritize assessment attention based on the recorded information lifetime, service dependencies and consequential unknowns; no numerical loss or quantum-arrival estimate.", confidence="limited",
                protectedInformation=b["information"], lifetime=b["lifetime"], assertedBy=b["owner"], statementDate="2026-09-16",
                compatibilityConstraints=b["compatibility"], vendorConstraints=b["vendor"], operationalConstraints=b["operational"], responsibleFunction=b["owner"], nextDecision=b["owner"]+" to confirm the next investigation for "+profile["name"].lower()+"; no execution is authorized."))
        case["analysis"]["recommendation"]=FAMILY_ACTIONS[family]
        cases.append(case)
        if with_forms:
            blank = (FIXTURES / "blanks" / spec["filename"]).read_bytes()
            assert sha(blank) == spec["blankSha256"]
            question_cells = {}
            for q in spec["questions"]:
                status, text, follow = values[q["id"]]
                question_cells.update({q["status"]: status, q["text"]: text, q["reference"]: "synthetic:" + family,
                    q["attribution"]: respondent["respondent"], q["followUp"]: follow})
            product_fields = ["product", "deployment", "environment", "applicationService", "owner", "dependencies", "reference", "notes"]
            changes = {"Start here": {spec["respondentCells"][k]: v for k,v in respondent.items()}, "Five questions": question_cells,
                "Products & deployments": {f"{chr(65+c)}{r+4}": row[k] for r,row in enumerate(products) for c,k in enumerate(product_fields)},
                "Version & return record": {spec["coordinatorCell"]: "SYNTHETIC TRAINING COPY — fictional Northstar Services. Do not email or treat these answers as enterprise testimony. Scenario inputs await simulated review; no owner outcome or execution authority is recorded."}}
            data = mark_synthetic_print_copy(expand_row_heights(edit(blank, changes), changes))
            actual, _, _ = workbook(data)
            assert all(actual[s].get(cell) == value for s, edits in changes.items() for cell,value in edits.items() if value)
            assert all(actual[s].get(cell) == value for s, cells in spec["readonlyCells"].items() for cell,value in cells.items())
            store(case["formPath"], data, raw=True)
            if family == "traffic-termination":
                store("forms/area-03/traffic-termination-synthetic-duplicate.xlsx", data, raw=True)
                revised = edit(data, {"Five questions": {spec["questions"][0]["text"]: "Revised synthetic return: east is configured hybrid; earlier observation is classical. This statement needs scope/date/client review and does not establish successful migration."}})
                store("forms/area-03/traffic-termination-synthetic-revised.xlsx", expand_row_heights(revised, changes), raw=True)
    store("form-responses.json", dict(schemaVersion="pqc.walkthrough.operational-responses.v1", synthetic=True, responses=responses))
    store("catalog-crosswalk.json", crosswalk)
    store("blocked-source.json", dict(schemaVersion="pqc.response-to-report.blocked-source.v1", synthetic=True, deployment="edge-third", state="blocked",
        reason="handling_route_unresolved", causeBasis="Scenario assumption, not an inferred enterprise restriction", nextFunction="Synthetic partner service function", observations=[], executionAuthorized=False))
    scenario = dict(schemaVersion="pqc.complete-walkthrough.scenario.v1", synthetic=True, enterprise=FICTION, asOf=AS_OF,
        normalizerVersion=NORMALIZER, seed=7, sourceFixtureDefinitionSha256=estate["content_sha256"], catalogSha256=sha(CATALOG.read_bytes()),
        crosswalkId=crosswalk["crosswalk_id"], classification="synthetic_training_only_no_enterprise_facts", cases=cases,
        expected=dict(domains=10, questionnaireTemplates=27, primaryCompletedForms=27 if with_forms else 0, bundles=len(registry), blockedDeployments=1,
            duplicateReturns=1 if with_forms else 0, competingReturns=1 if with_forms else 0, enterpriseCoveragePercent=None, qualifiedVendorAdapters=0, liveConnections=0),
        authority=dict(ownerObservation=None, businessAcceptance="not_recorded", enterpriseAcceptance=False, executionAuthorized=False), files=list(files.values()))
    store("scenario.json", scenario)
    return dict(output=str(output), domains=10, templates=27, bundles=len(registry), forms=27 if with_forms else 0, sha256=files["scenario.json"]["sha256"])


def audit_layout(inputs: Path):
    """Conservative line-budget check, supplementary to actual office rendering."""
    scenario=json.loads((inputs/"scenario.json").read_text())
    specs={row["familyId"]:row for row in json.loads((FIXTURES/"catalog.json").read_text())["forms"]}
    audited=[]
    for case in scenario["cases"]:
        spec=specs[case["familyId"]]
        data=(inputs/case["formPath"]).read_bytes()
        cells,paths,parts=workbook(data)
        selected={"Start here":list(spec["respondentCells"].values()),"Five questions":[q[k] for q in spec["questions"] for k in ("status","text","reference","attribution","followUp")],
            "Products & deployments":[f"{chr(65+c)}{r+4}" for r in range(len(case["products"])) for c in range(8)],"Version & return record":[spec["coordinatorCell"]]}
        checked=[]
        for sheet,addresses in selected.items():
            row_heights={int(row.get("r")):float(row.get("ht","15")) for row in ET.fromstring(parts[paths[sheet]]).find(f"{{{NS}}}sheetData")}
            width=27 if sheet=="Products & deployments" else 92
            for address in addresses:
                text=cells[sheet].get(address,"")
                if not text:continue
                row=int(''.join(filter(str.isdigit,address)))
                required=18*sum(max(1,(len(line)+width-1)//width) for line in text.splitlines())+12
                checked.append(dict(sheet=sheet,cell=address,characters=len(text),estimatedMinimumHeightPoints=required,actualHeightPoints=row_heights[row],passes=row_heights[row]>=required))
        audited.append(dict(familyId=case["familyId"],filename=case["formPath"],sha256=sha(data),cells=checked,passes=all(row["passes"] for row in checked)))
    return dict(schemaVersion="pqc.walkthrough.workbook-layout-audit.v1",synthetic=True,forms=27,checks=audited,passes=all(row["passes"] for row in audited),
        boundary="Heuristic line-height budget, not an office renderer or proof of pixel-perfect layout. Render representative long forms before delivery.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--without-forms", action="store_true", help="Prepare JSON only; does not substitute for the completed XLSX deliverable.")
    parser.add_argument("--audit-existing", type=Path)
    parser.add_argument("--audit-output", type=Path)
    args = parser.parse_args()
    os.umask(0o077)
    if args.audit_existing:
        if args.audit_output is None: parser.error("--audit-output required for separate create-only audit artifact")
        result=audit_layout(args.audit_existing)
        new(args.audit_output,encoded(result))
        print(json.dumps({"forms":result["forms"],"passes":result["passes"],"output":str(args.audit_output)}))
    else:
        if args.output is None: parser.error("--output required")
        print(json.dumps(build(args.output, with_forms=not args.without_forms), sort_keys=True))
